import { describe, expect, it } from 'vitest'
import { getVisibleNavigation } from '@/app/navigation'

describe('getVisibleNavigation', () => {
  it('removes a disabled stable navigation id without removing other live routes', () => {
    const visible = getVisibleNavigation({
      role: 'ADMIN',
      industry: null,
      country: null,
      disabledIds: ['contacts'],
    })

    expect(visible.map((item) => item.id)).toEqual([
      'dashboard',
      'inventory.items',
      'inventory.picklists',
      'inventory.transfers',
      'inventory.counts',
      'inventory.warehouses',
      'inventory.price_lists',
      'inventory.batch_trace',
      'inventory.shortbook',
      'inventory.consignments',
      'inventory.barcode_labels',
      'sales.orders',
      'sales.challans',
      'sales.invoices',
      'sales.payments',
      'sales.credit_notes',
      'sales.estimates',
      'sales.recurring_invoices',
      'pos.checkout',
      'pos.cash_registers',
    'pos.offline_sync',
    'pos.receipt_settings',
    'sales.receipts',
      'crm.loyalty',
      'purchases.orders',
      'purchases.receipts',
      'purchases.bills',
      'purchases.three_way_match',
      'purchases.vendor_credits',
      'purchases.payments',
      'purchases.debit_notes',
      'purchases.recurring_bills',
      'manufacturing.work_orders',
      'manufacturing.bom',
      'manufacturing.routings',
      'manufacturing.mrp',
      'manufacturing.job_work',
      'manufacturing.qc',
      'manufacturing.qc_templates',
      'manufacturing.ncr',
      'manufacturing.capa',
      'manufacturing.work_centers',
      'manufacturing.maintenance_schedules',
      'manufacturing.maintenance_orders',
      'manufacturing.reports',
      'fieldsales.beats',
      'fieldsales.routes',
      'fieldsales.vans',
      'fieldsales.executions',
      'fieldsales.day_close',
      'fieldsales.targets',
      'fieldsales.merchandising',
      'mr.dcr',
      'mr.tour_plans',
      'mr.detail_aids',
      'mr.samples',
      'mr.rcpa',
      'mr.secondary_sales',
      'mr.approvals',
      'accounting.accounts',
      'accounting.journals',
      'accounting.budgets',
      'accounting.fiscal_periods',
      'accounting.fixed_assets',
      'accounting.amortization',
      'accounting.recurring_journals',
      'banking.accounts',
      'payroll.employees',
      'payroll.runs',
      'hr.attendance',
      'hr.leaves',
      'hr.shifts',
      'hr.timesheets',
      'hr.tickets',
      'hr.offboarding',
      'hr.biometrics',
      'payroll.settings',
      'reporting.hub',
      'reporting.saved',
      'reporting.cash_runway',
      'reporting.flux_commentary',
      'settings.users',
      'settings.pdf_templates',
      'franchise.stores',
      'settings.tax_accounts',
      'pharmacy.masters',
      'pharmacy.near_expiry',
      'transport.courier_shipments',
      'transport.cod_remittances',
      'transport.lorry_receipts',
      'transport.rate_cards',
      'transport.vehicle_logs',
      'transport.courier_settings',
    ])
  })
})

