import {
  TrendingUp,
  Palette,
  Globe,
  Store,
  AlertOctagon,
  ArrowLeftRight,
  ArrowUpRight,
  Award,
  Banknote,
  BarChart3,
  Bookmark,
  BookOpen,
  Boxes,
  Briefcase,
  Building,
  Building2,
  CalendarClock,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cpu,
  DollarSign,
  Factory,
  FileBadge,
  FileMinus,
  FileSpreadsheet,
  FileText,
  Landmark,
  Layers,
  LifeBuoy,
  ListChecks,
  MapPin,
  PackageCheck,
  Pill,
  Printer,
  ReceiptText,
  RefreshCw,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  Tag,
  Truck,
  type LucideIcon,
  UserMinus,
  Users,
  UsersRound,
  Compass,
  Gift,
  Navigation,
  Stethoscope,
  Target,
  Wrench,
} from 'lucide-react'

export const appRoutes = {
  overview: '/',
  contacts: '/contacts',
  items: '/items',
  itemDetail: (id: string) => `/items/${id}`,
  batchTrace: '/batch-trace',
  shortbook: '/shortbook',
  consignments: '/consignments',
  barcodeLabels: '/barcode-labels',
  picklists: '/picklists',
  picklistDetail: (id: string) => `/picklists/${id}`,
  transferOrders: '/transfer-orders',
  transferOrderDetail: (id: string) => `/transfer-orders/${id}`,
  stockCounts: '/stock-counts',
  stockCountDetail: (id: string) => `/stock-counts/${id}`,
  warehouses: '/warehouses',
  warehouseDetail: (id: string) => `/warehouses/${id}`,
  priceLists: '/price-lists',
  priceListDetail: (id: string) => `/price-lists/${id}`,
  salesOrders: '/sales-orders',
  salesOrderDetail: (id: string) => `/sales-orders/${id}`,
  deliveryChallans: '/delivery-challans',
  deliveryChallanDetail: (id: string) => `/delivery-challans/${id}`,
  invoices: '/invoices',
  invoiceDetail: (id: string) => `/invoices/${id}`,
  payments: '/payments',
  paymentDetail: (id: string) => `/payments/${id}`,
  creditNotes: '/credit-notes',
  creditNoteDetail: (id: string) => `/credit-notes/${id}`,
  purchaseOrders: '/purchase-orders',
  purchaseOrderDetail: (id: string) => `/purchase-orders/${id}`,
  stockReceipts: '/stock-receipts',
  stockReceiptDetail: (id: string) => `/stock-receipts/${id}`,
  bills: '/bills',
  billDetail: (id: string) => `/bills/${id}`,
  threeWayMatch: '/three-way-match',
  threeWayMatchWorkbench: (billId: string) => `/bills/${billId}/three-way-match`,
  vendorCredits: '/vendor-credits',
  vendorCreditDetail: (id: string) => `/vendor-credits/${id}`,
  apAgingReport: '/reports/ap-aging',
  vendorPayments: '/vendor-payments',
  vendorPaymentDetail: (id: string) => `/vendor-payments/${id}`,
  debitNotes: '/debit-notes',
  debitNoteDetail: (id: string) => `/debit-notes/${id}`,
  workOrders: '/work-orders',
  workOrderDetail: (id: string) => `/work-orders/${id}`,
  bomManager: '/bom-manager',
  bomManagerItem: (itemId: string) => `/bom-manager/${itemId}`,
  routings: '/routings',
  mrp: '/mrp',
  jobWork: '/job-work',
  jobWorkDetail: (id: string) => `/job-work/${id}`,
  qcInspections: '/qc-inspections',
  qcInspectionDetail: (id: string) => `/qc-inspections/${id}`,
  qcTemplates: '/qc-templates',
  ncrs: '/ncrs',
  ncrDetail: (id: string) => `/ncrs/${id}`,
  capa: '/capa',
  capaDetail: (id: string) => `/capa/${id}`,
  workCenters: '/work-centers',
  workCenterDetail: (id: string) => `/work-centers/${id}`,
  maintenanceSchedules: '/maintenance-schedules',
  maintenanceWorkOrders: '/maintenance-work-orders',
  maintenanceWorkOrderDetail: (id: string) => `/maintenance-work-orders/${id}`,
  manufacturingReports: '/reports/manufacturing',
  budgets: '/budgets',
  fiscalPeriods: '/fiscal-periods',
  accounts: '/accounts',
  accountDetail: (id: string) => `/accounts/${id}`,
  journals: '/journals',
  journalDetail: (id: string) => `/journals/${id}`,
  fixedAssets: '/fixed-assets',
  fixedAssetDetail: (id: string) => `/fixed-assets/${id}`,
  amortization: '/amortization',
  amortizationDetail: (id: string) => `/amortization/${id}`,
  beats: '/beats',
  beatDetail: (id: string) => `/beats/${id}`,
  routes: '/routes',
  routeDetail: (id: string) => `/routes/${id}`,
  vans: '/vans',
  vanDetail: (id: string) => `/vans/${id}`,
  routeExecutions: '/field-sales/executions',
  routeExecutionDetail: (id: string) => `/field-sales/executions/${id}`,
  dayClose: '/field-sales/day-close',
  salesmanTargets: '/field-sales/targets',
  storeMerchandising: '/field-sales/merchandising',
  dcr: '/mr/dcr',
  dcrDetail: (id: string) => `/mr/dcr/${id}`,
  tourPlans: '/mr/tour-plans',
  tourPlanDetail: (id: string) => `/mr/tour-plans/${id}`,
  detailAids: '/mr/detail-aids',
  fieldSamples: '/mr/samples',
  rcpa: '/mr/rcpa',
  secondarySales: '/mr/secondary-sales',
  mrApprovals: '/mr/approvals',
  employees: '/employees',
  employeeDetail: (id: string) => `/employees/${id}`,
  payrollRuns: '/payroll-runs',
  payrollRunDetail: (id: string) => `/payroll-runs/${id}`,
  payrollSettings: '/settings/payroll',
  attendance: '/attendance',
  leaves: '/leaves',
  shifts: '/shifts',
  timesheets: '/timesheets',
  hrTickets: '/hr-tickets',
  hrTicketDetail: (id: string) => `/hr-tickets/${id}`,
  offboarding: '/offboarding',
  offboardingDetail: (id: string) => `/offboarding/${id}`,
  biometricDevices: '/biometric-devices',
  reports: '/reports',
  reportViewer: (key: string) => `/reports/${key}`,
  savedReports: '/saved-reports',
  savedReportDetail: (id: string) => `/saved-reports/${id}`,
  pharmacyMasters: '/pharmacy-masters',
  nearExpiry: '/near-expiry',
  pos: '/pos',
  posCashRegisters: '/pos/cash-registers',
  posOfflineSync: '/pos/offline-sync',
  posReceiptSettings: '/settings/pos-receipt',
  salesReceipts: '/sales-receipts',
  salesReceiptDetail: (id: string) => `/sales-receipts/${id}`,
  estimates: '/estimates',
  estimateCreate: '/estimates/new',
  estimateDetail: (id: string) => `/estimates/${id}`,
  recurringInvoices: '/recurring-invoices',
  recurringInvoiceDetail: (id: string) => `/recurring-invoices/${id}`,
  recurringBills: '/recurring-bills',
  recurringBillDetail: (id: string) => `/recurring-bills/${id}`,
  recurringJournals: '/recurring-journals',
  recurringJournalDetail: (id: string) => `/recurring-journals/${id}`,
  loyalty: '/loyalty',
  gst: '/gst',
  banking: '/banking',
  courierShipments: '/courier/shipments',
  courierShipmentDetail: (id: string) => `/courier/shipments/${id}`,
  codRemittances: '/courier/cod-remittances',
  codRemittanceDetail: (id: string) => `/courier/cod-remittances/${id}`,
  courierSettings: '/settings/couriers',
  lorryReceipts: '/transport/lorry-receipts',
  lorryReceiptDetail: (id: string) => `/transport/lorry-receipts/${id}`,
  freightRateCards: '/transport/rate-cards',
  vehicleLogs: '/transport/vehicle-logs',
  tds: '/compliance/tds',
  tcs: '/compliance/tcs',
  taxAccountMappings: '/settings/tax-accounts',
  franchise: '/franchise',
  franchiseDetail: (nodeId: string) => `/franchise/${nodeId}`,
  kenyaCompliance: '/compliance/kenya',
  cashRunway: '/reports/cash-runway',
  fluxCommentary: '/reports/flux-commentary',
  users: '/settings/users',
  pdfTemplates: '/settings/pdf-templates',
} as const

export type NavigationContext = {
  role: string | null | undefined
  industry: string | null | undefined
  country: string | null | undefined
  capabilities?: readonly string[]
  disabledIds?: readonly string[]
}

export type NavigationItem = {
  id: string
  label: string
  description: string
  icon: LucideIcon
  to: string
  roles?: readonly string[]
  industries?: readonly string[]
  countries?: readonly string[]
  capability?: string
}

const navigationItems: readonly NavigationItem[] = [
  {
    id: 'dashboard',
    label: 'Overview',
    description: 'Live business snapshot',
    icon: BarChart3,
    to: appRoutes.overview,
  },
  {
    id: 'contacts',
    label: 'Contacts',
    description: 'Customers, vendors, and suppliers',
    icon: UsersRound,
    to: appRoutes.contacts,
  },
  {
    id: 'inventory.items',
    label: 'Items',
    description: 'Item master and on-hand stock',
    icon: Boxes,
    to: appRoutes.items,
  },
  {
    id: 'inventory.picklists',
    label: 'Picklists',
    description: 'Warehouse picking progress',
    icon: ListChecks,
    to: appRoutes.picklists,
  },
  {
    id: 'inventory.transfers',
    label: 'Transfer Orders',
    description: 'Inter-warehouse stock movements',
    icon: ArrowLeftRight,
    to: appRoutes.transferOrders,
  },
  {
    id: 'inventory.counts',
    label: 'Stock Counts',
    description: 'Physical counts & cycle audits',
    icon: ClipboardCheck,
    to: appRoutes.stockCounts,
  },
  {
    id: 'inventory.warehouses',
    label: 'Warehouses',
    description: 'Facilities & branch locations',
    icon: Building2,
    to: appRoutes.warehouses,
  },
  {
    id: 'inventory.price_lists',
    label: 'Price Lists',
    description: 'Tier pricing & volume rates',
    icon: Tag,
    to: appRoutes.priceLists,
  },
  {
    id: 'inventory.batch_trace',
    label: 'Batch Traceability',
    description: 'Genealogy & recall console',
    icon: ShieldAlert,
    to: appRoutes.batchTrace,
  },
  {
    id: 'inventory.shortbook',
    label: 'Shortbook Console',
    description: 'Low stock & auto PO generation',
    icon: Bookmark,
    to: appRoutes.shortbook,
  },
  {
    id: 'inventory.consignments',
    label: 'Consignments & VMI',
    description: 'Vendor managed inventory',
    icon: Briefcase,
    to: appRoutes.consignments,
  },
  {
    id: 'inventory.barcode_labels',
    label: 'Barcode Labels Hub',
    description: 'Thermal & sheet label designer',
    icon: Tag,
    to: appRoutes.barcodeLabels,
  },
  {
    id: 'sales.orders',
    label: 'Sales Orders',
    description: 'Customer commitments and fulfilment',
    icon: ClipboardList,
    to: appRoutes.salesOrders,
  },
  {
    id: 'sales.challans',
    label: 'Delivery Challans',
    description: 'Dispatches and shipment progress',
    icon: Truck,
    to: appRoutes.deliveryChallans,
  },
  {
    id: 'sales.invoices',
    label: 'Invoices',
    description: 'Receivables and payment progress',
    icon: ReceiptText,
    to: appRoutes.invoices,
  },
  {
    id: 'sales.payments',
    label: 'Customer Payments',
    description: 'Customer collections and receipts',
    icon: Landmark,
    to: appRoutes.payments,
  },
  {
    id: 'sales.credit_notes',
    label: 'Credit Notes',
    description: 'Sales returns & credit adjustments',
    icon: FileBadge,
    to: appRoutes.creditNotes,
  },
  {
    id: 'sales.estimates',
    label: 'Estimates & Quotes',
    description: 'Commercial proposals & quote conversion',
    icon: FileSpreadsheet,
    to: appRoutes.estimates,
  },
  {
    id: 'sales.recurring_invoices',
    label: 'Recurring Invoices',
    description: 'Subscription & scheduled customer billing',
    icon: RefreshCw,
    to: appRoutes.recurringInvoices,
  },
  {
    id: 'pos.checkout',
    label: 'Point of Sale',
    description: 'Express counter billing & POS register',
    icon: ShoppingBag,
    to: appRoutes.pos,
  },
  {
    id: 'pos.cash_registers',
    label: 'Cash Registers',
    description: 'Drawer float, petty expenses & shift closing',
    icon: DollarSign,
    to: appRoutes.posCashRegisters,
  },
  {
    id: 'pos.offline_sync',
    label: 'Offline Sync',
    description: 'Local bill buffer & product catalog cache',
    icon: RefreshCw,
    to: appRoutes.posOfflineSync,
  },
  {
    id: 'pos.receipt_settings',
    label: 'Thermal Receipt Settings',
    description: 'Branding, paper width & printer layout',
    icon: Printer,
    to: appRoutes.posReceiptSettings,
  },
  {
    id: 'sales.receipts',
    label: 'Sales Receipts',
    description: 'POS receipts & shift counter sales',
    icon: ReceiptText,
    to: appRoutes.salesReceipts,
  },
  {
    id: 'crm.loyalty',
    label: 'Loyalty & Rewards',
    description: 'Customer wallets & points ledger',
    icon: Award,
    to: appRoutes.loyalty,
  },
  {
    id: 'purchases.orders',
    label: 'Purchase Orders',
    description: 'Supplier commitments & tracking',
    icon: ShoppingBag,
    to: appRoutes.purchaseOrders,
  },
  {
    id: 'purchases.receipts',
    label: 'Stock Receipts (GRN)',
    description: 'Inbound shipments & landed costs',
    icon: PackageCheck,
    to: appRoutes.stockReceipts,
  },
  {
    id: 'purchases.bills',
    label: 'Bills',
    description: 'Vendor bills and payables',
    icon: FileSpreadsheet,
    to: appRoutes.bills,
  },
  {
    id: 'purchases.three_way_match',
    label: '3-Way Match Inbox',
    description: 'PO vs GRN vs Bill variance inspector',
    icon: Layers,
    to: appRoutes.threeWayMatch,
  },
  {
    id: 'purchases.vendor_credits',
    label: 'Vendor Credits',
    description: 'Unapplied supplier credits & debit notes',
    icon: FileBadge,
    to: appRoutes.vendorCredits,
  },
  {
    id: 'purchases.payments',
    label: 'Vendor Payments',
    description: 'Disbursements and AP settlements',
    icon: ArrowUpRight,
    to: appRoutes.vendorPayments,
  },
  {
    id: 'purchases.debit_notes',
    label: 'Debit Notes',
    description: 'Purchase returns & chargebacks',
    icon: FileMinus,
    to: appRoutes.debitNotes,
  },
  {
    id: 'purchases.recurring_bills',
    label: 'Recurring Bills',
    description: 'Automated periodic supplier vendor bills',
    icon: RefreshCw,
    to: appRoutes.recurringBills,
  },
  {
    id: 'manufacturing.work_orders',
    label: 'Work Orders',
    description: 'Production floor build orders',
    icon: Factory,
    to: appRoutes.workOrders,
  },
  {
    id: 'manufacturing.bom',
    label: 'BOM & Recipes',
    description: 'Engineering bills of material & diffs',
    icon: Layers,
    to: appRoutes.bomManager,
  },
  {
    id: 'manufacturing.routings',
    label: 'Routings & Operations',
    description: 'Floor routing steps & operations library',
    icon: ListChecks,
    to: appRoutes.routings,
  },
  {
    id: 'manufacturing.mrp',
    label: 'MRP Simulation',
    description: 'Material requirements planning engine',
    icon: Cpu,
    to: appRoutes.mrp,
  },
  {
    id: 'manufacturing.job_work',
    label: 'Job Work & Challan 45',
    description: 'Subcontracting dispatches & ITC-04',
    icon: Briefcase,
    to: appRoutes.jobWork,
  },
  {
    id: 'manufacturing.qc',
    label: 'QC Inspections',
    description: 'Quality checks & parameter audits',
    icon: ShieldCheck,
    to: appRoutes.qcInspections,
  },
  {
    id: 'manufacturing.qc_templates',
    label: 'QC Templates',
    description: 'Configurable inspection test parameters',
    icon: ClipboardCheck,
    to: appRoutes.qcTemplates,
  },
  {
    id: 'manufacturing.ncr',
    label: 'Non-Conformance Reports',
    description: 'Defect remediation & root causes',
    icon: ShieldAlert,
    to: appRoutes.ncrs,
  },
  {
    id: 'manufacturing.capa',
    label: 'CAPA Management',
    description: 'Corrective & preventive actions hub',
    icon: AlertOctagon,
    to: appRoutes.capa,
  },
  {
    id: 'manufacturing.work_centers',
    label: 'Work Centers',
    description: 'Plant machinery & capacity',
    icon: Cpu,
    to: appRoutes.workCenters,
  },
  {
    id: 'manufacturing.maintenance_schedules',
    label: 'Maintenance Schedules',
    description: 'Preventive PM routines & calendar',
    icon: CalendarClock,
    to: appRoutes.maintenanceSchedules,
  },
  {
    id: 'manufacturing.maintenance_orders',
    label: 'Maintenance Orders',
    description: 'Breakdowns & service dispatches',
    icon: Wrench,
    to: appRoutes.maintenanceWorkOrders,
  },
  {
    id: 'manufacturing.reports',
    label: 'Manufacturing Analytics',
    description: 'WIP valuation, bottleneck & scrap reports',
    icon: BarChart3,
    to: appRoutes.manufacturingReports,
  },
  {
    id: 'fieldsales.beats',
    label: 'Sales Beats',
    description: 'Territory stops & visit sequences',
    icon: MapPin,
    to: appRoutes.beats,
  },
  {
    id: 'fieldsales.routes',
    label: 'Sales Routes',
    description: 'Scheduled multi-beat route lines',
    icon: Navigation,
    to: appRoutes.routes,
  },
  {
    id: 'fieldsales.vans',
    label: 'Mobile Vans',
    description: 'Van fleet & on-board stock',
    icon: Truck,
    to: appRoutes.vans,
  },
  {
    id: 'fieldsales.executions',
    label: 'Route Executions',
    description: 'Daily field visits & order booking',
    icon: Navigation,
    to: appRoutes.routeExecutions,
  },
  {
    id: 'fieldsales.day_close',
    label: 'Day Close & Settlement',
    description: 'Cash reconciliation & manager signoff',
    icon: Banknote,
    to: appRoutes.dayClose,
  },
  {
    id: 'fieldsales.targets',
    label: 'Sales Targets',
    description: 'Salesperson quotas & achievements',
    icon: Target,
    to: appRoutes.salesmanTargets,
  },
  {
    id: 'fieldsales.merchandising',
    label: 'Store Merchandising',
    description: 'Shelf audits & planogram compliance',
    icon: ShoppingBag,
    to: appRoutes.storeMerchandising,
  },
  {
    id: 'mr.dcr',
    label: 'Daily Call Reports (DCR)',
    description: 'Doctor calls & personal order booking',
    icon: Stethoscope,
    to: appRoutes.dcr,
  },
  {
    id: 'mr.tour_plans',
    label: 'Monthly Tour Plans',
    description: 'MR monthly travel itineraries & MTP',
    icon: Compass,
    to: appRoutes.tourPlans,
  },
  {
    id: 'mr.detail_aids',
    label: 'Visual Detailing Aids',
    description: 'Digital brochures & clinical presentations',
    icon: BookOpen,
    to: appRoutes.detailAids,
  },
  {
    id: 'mr.samples',
    label: 'Physician Samples',
    description: 'Sample batches & promotional inputs',
    icon: Gift,
    to: appRoutes.fieldSamples,
  },
  {
    id: 'mr.rcpa',
    label: 'Prescription Audit (RCPA)',
    description: 'Retail chemist audit & doctor brand share',
    icon: BarChart3,
    to: appRoutes.rcpa,
  },
  {
    id: 'mr.secondary_sales',
    label: 'Stockist Secondary Sales',
    description: 'Wholesale sales statements & off-take',
    icon: FileSpreadsheet,
    to: appRoutes.secondarySales,
  },
  {
    id: 'mr.approvals',
    label: 'MR Approvals Hub',
    description: 'Manager sign-offs for MTP, DCR & claims',
    icon: ClipboardCheck,
    to: appRoutes.mrApprovals,
  },
  {
    id: 'accounting.accounts',
    label: 'Chart of Accounts',
    description: 'General ledger & account hierarchy',
    icon: BookOpen,
    to: appRoutes.accounts,
  },
  {
    id: 'accounting.journals',
    label: 'Journal Entries',
    description: 'General ledger postings & adjustments',
    icon: FileText,
    to: appRoutes.journals,
  },
  {
    id: 'accounting.budgets',
    label: 'Budgets & Variance',
    description: 'Operating limits vs GL actuals',
    icon: BarChart3,
    to: appRoutes.budgets,
  },
  {
    id: 'accounting.fiscal_periods',
    label: 'Fiscal Periods & Close',
    description: 'Period boundaries & continuous close',
    icon: ShieldCheck,
    to: appRoutes.fiscalPeriods,
  },
  {
    id: 'accounting.fixed_assets',
    label: 'Fixed Assets',
    description: 'Capitalized assets & depreciation',
    icon: Building,
    to: appRoutes.fixedAssets,
  },
  {
    id: 'accounting.amortization',
    label: 'Amortization & Prepaids',
    description: 'Straight-line periodic recognition',
    icon: CalendarClock,
    to: appRoutes.amortization,
  },
  {
    id: 'accounting.recurring_journals',
    label: 'Recurring Journals',
    description: 'Scheduled periodic adjustments & accruals',
    icon: RefreshCw,
    to: appRoutes.recurringJournals,
  },
  {
    id: 'banking.accounts',
    label: 'Banking & Feeds',
    description: 'Bank statements & AI reconciliation',
    icon: Landmark,
    to: appRoutes.banking,
  },
  {
    id: 'payroll.employees',
    label: 'Employees',
    description: 'Staff master & salary structures',
    icon: Users,
    to: appRoutes.employees,
  },
  {
    id: 'payroll.runs',
    label: 'Payroll Runs',
    description: 'Monthly salary cycles & payslips',
    icon: Banknote,
    to: appRoutes.payrollRuns,
  },
  {
    id: 'hr.attendance',
    label: 'Attendance & Clock',
    description: 'Punches, overtime & regularization',
    icon: CalendarClock,
    to: appRoutes.attendance,
  },
  {
    id: 'hr.leaves',
    label: 'Leaves & Holidays',
    description: 'Leave balances, applications & quotas',
    icon: CalendarClock,
    to: appRoutes.leaves,
  },
  {
    id: 'hr.shifts',
    label: 'Shifts & Rosters',
    description: 'Work schedules & night shift planning',
    icon: Clock,
    to: appRoutes.shifts,
  },
  {
    id: 'hr.timesheets',
    label: 'Timesheets',
    description: 'Project hours & billable logs',
    icon: FileSpreadsheet,
    to: appRoutes.timesheets,
  },
  {
    id: 'hr.tickets',
    label: 'HR Helpdesk',
    description: 'Employee queries & grievance tickets',
    icon: LifeBuoy,
    to: appRoutes.hrTickets,
  },
  {
    id: 'hr.offboarding',
    label: 'Offboarding & FnF',
    description: 'Exit clearance, settlements & gratuity',
    icon: UserMinus,
    to: appRoutes.offboarding,
  },
  {
    id: 'hr.biometrics',
    label: 'Biometric Terminals',
    description: 'ZKTeco TCP & ADMS live push telemetry',
    icon: Cpu,
    to: appRoutes.biometricDevices,
  },
  {
    id: 'payroll.settings',
    label: 'Payroll Settings',
    description: 'Pay rules, GL accounts & statutory toggles',
    icon: Settings,
    to: appRoutes.payrollSettings,
  },
  {
    id: 'reporting.hub',
    label: 'Reports Hub',
    description: 'Financial statements & tax ledgers',
    icon: BarChart3,
    to: appRoutes.reports,
  },
  {
    id: 'reporting.saved',
    label: 'Saved Reports',
    description: 'Customized queries & schedules',
    icon: Bookmark,
    to: appRoutes.savedReports,
  },
  {
    id: 'reporting.cash_runway',
    label: '13-Week Cash Runway',
    description: 'Rolling liquidity forecast & stress testing',
    icon: TrendingUp,
    to: appRoutes.cashRunway,
  },
  {
    id: 'reporting.flux_commentary',
    label: 'Flux Commentary',
    description: 'MoM/YoY balance sheet variance analytics',
    icon: BarChart3,
    to: appRoutes.fluxCommentary,
  },
  {
    id: 'settings.users',
    label: 'Team & User Roles',
    description: 'Invite members & manage permissions',
    icon: Users,
    to: appRoutes.users,
  },
  {
    id: 'settings.pdf_templates',
    label: 'PDF Document Designer',
    description: 'Brand colors, logos, QR codes & terms',
    icon: Palette,
    to: appRoutes.pdfTemplates,
  },
  {
    id: 'compliance.gst',
    label: 'GST Compliance Suite',
    description: 'GSTR-1, GSTR-3B, IMS & e-Way bills',
    icon: ShieldCheck,
    to: appRoutes.gst,
    countries: ['IN'],
  },
  {
    id: 'compliance.tds',
    label: 'TDS Compliance (26Q/24Q)',
    description: 'Vendor & salary TDS registers & Form 16',
    icon: FileText,
    to: appRoutes.tds,
    countries: ['IN'],
  },
  {
    id: 'compliance.tcs',
    label: 'TCS Section 206C(1H)',
    description: '₹50L turnover tracker & Form 27EQ',
    icon: Layers,
    to: appRoutes.tcs,
    countries: ['IN'],
  },
  {
    id: 'compliance.kenya',
    label: 'Kenya eTIMS & M-Pesa',
    description: 'KRA electronic tax invoices & Daraja mobile money',
    icon: Globe,
    to: appRoutes.kenyaCompliance,
    countries: ['KE'],
  },
  {
    id: 'franchise.stores',
    label: 'Franchise Network',
    description: 'FOFO/COCO branches, catalog push & royalties',
    icon: Store,
    to: appRoutes.franchise,
  },
  {
    id: 'settings.tax_accounts',
    label: 'Tax Account Mappings',
    description: 'GST/VAT input/output GL account bindings',
    icon: Building2,
    to: appRoutes.taxAccountMappings,
  },
  {
    id: 'pharmacy.masters',
    label: 'Pharmacy Masters',
    description: 'Drug catalog, HSN & rack layout',
    icon: Pill,
    to: appRoutes.pharmacyMasters,
  },
  {
    id: 'pharmacy.near_expiry',
    label: 'Near Expiry Alerts',
    description: 'Batch shelf life & FEFO tracking',
    icon: AlertOctagon,
    to: appRoutes.nearExpiry,
  },
  {
    id: 'transport.courier_shipments',
    label: 'Courier Shipments',
    description: 'Parcel dispatches & live tracking',
    icon: Truck,
    to: appRoutes.courierShipments,
  },
  {
    id: 'transport.cod_remittances',
    label: 'COD Remittances',
    description: 'Cash-on-delivery reconciliation',
    icon: Banknote,
    to: appRoutes.codRemittances,
  },
  {
    id: 'transport.lorry_receipts',
    label: 'Lorry Receipts (LR)',
    description: 'Consignment notes & freight billing',
    icon: FileSpreadsheet,
    to: appRoutes.lorryReceipts,
  },
  {
    id: 'transport.rate_cards',
    label: 'Freight Rate Cards',
    description: 'Lane rate matrix & quote calculator',
    icon: Tag,
    to: appRoutes.freightRateCards,
  },
  {
    id: 'transport.vehicle_logs',
    label: 'Vehicle Logs & TCO',
    description: 'Fleet expenses & cost-per-km analytics',
    icon: Compass,
    to: appRoutes.vehicleLogs,
  },
  {
    id: 'transport.courier_settings',
    label: 'Courier Gateways',
    description: 'BlueDart, Delhivery, DTDC & Shiprocket credentials',
    icon: Settings,
    to: appRoutes.courierSettings,
  },
]

export function getVisibleNavigation(context: NavigationContext): NavigationItem[] {
  const disabledIds = new Set(context.disabledIds ?? [])
  const capabilities = new Set(context.capabilities ?? [])

  return navigationItems.filter((item) => {
    if (disabledIds.has(item.id)) return false
    if (item.roles && (!context.role || !item.roles.includes(context.role))) return false
    if (item.industries && (!context.industry || !item.industries.includes(context.industry))) return false
    if (item.countries && (!context.country || !item.countries.includes(context.country))) return false
    if (item.capability && !capabilities.has(item.capability)) return false
    return true
  })
}
