-- V20: Global medicine database expansion.
--
-- Grows the platform reference masters (salt_master / manufacturer_master /
-- drug_master) beyond the India-centric V2 seed, curated from public retail
-- catalogues the trade actually uses:
--   * Indian retail lists (Marg-style distributor lists, 1mg / Apollo
--     bestsellers, 2024-25 launches such as Wegovy / Mounjaro / Vymada),
--   * Jan Aushadhi (PMBI) and DavaIndia (Zota Healthcare) generic ranges,
--   * Gulf / GCC retail brands (UAE, Saudi, Oman) for the AE/OM expansion,
--   * East & South Africa staples (Kenya focus) for the KE expansion,
--   * Global US/EU brands for cross-border reference completeness.
--
-- Conventions:
--   * salt_master / manufacturer_master: ON CONFLICT (name) DO NOTHING —
--     both tables carry UNIQUE(name), so re-runs and V2 overlaps are no-ops.
--   * drug_master has NO unique key on brand_name, so every batch inserts
--     through a VALUES CTE guarded by a case-insensitive NOT EXISTS on
--     brand_name plus DISTINCT ON to collapse intra-batch duplicates.
--     Brands already present from the V2 seed are silently skipped.
--   * salt_id resolves by case-insensitive name match on salt_master
--     (same shape as the V2 rows); combos that have no salt row keep a
--     NULL salt_id with the full salt_composition text.
--   * MRP is the approximate local retail price for Indian rows (INR) and
--     NULL for non-Indian market rows — orgs set their own price when they
--     add the item (PosCatalogService passes MRP straight into salePrice,
--     and a NULL there is safer than a fabricated cross-currency number).
--   * drug_schedule uses the Indian buckets that drive the POS prescription
--     dialog + statutory registers: GENERAL / H / H1 / X. Foreign Rx brands
--     carry H (or H1/X where the molecule is on the Indian H1/X lists, e.g.
--     cefixime, azithromycin, alprazolam, zolpidem → H1; methylphenidate → X)
--     so prescription_required behaves for any org that stocks them.
--   * GST/HSN per post-GST-2.0 rates: 3004 medicines 5%, 9018/9019 devices
--     5%, 3822 test strips/kits 5%, 3005 dressings 5%, 1901 infant/malt
--     foods 5%, 1702 glucose 5%, 4014 condoms 0%, 2106 supplements 18%,
--     3304 dermo-cosmetics 18%, 3808 antiseptic liquids 18%, 9025
--     thermometers 18%.

-- ---------------------------------------------------------------------------
-- 1) salt_master — additional molecules (newer classes + gaps in V2)
-- ---------------------------------------------------------------------------
INSERT INTO public.salt_master (name, category) VALUES
	('Semaglutide', 'Antidiabetic'),
	('Tirzepatide', 'Antidiabetic'),
	('Liraglutide', 'Antidiabetic'),
	('Dulaglutide', 'Antidiabetic'),
	('Insulin Aspart', 'Antidiabetic'),
	('Insulin Lispro', 'Antidiabetic'),
	('Insulin Degludec', 'Antidiabetic'),
	('Insulin Detemir', 'Antidiabetic'),
	('Pioglitazone', 'Antidiabetic'),
	('Voglibose', 'Antidiabetic'),
	('Acarbose', 'Antidiabetic'),
	('Repaglinide', 'Antidiabetic'),
	('Canagliflozin', 'Antidiabetic'),
	('Remogliflozin Etabonate', 'Antidiabetic'),
	('Saxagliptin', 'Antidiabetic'),
	('Sacubitril + Valsartan', 'Cardiac'),
	('Ivabradine', 'Cardiac'),
	('Ranolazine', 'Cardiac'),
	('Trimetazidine', 'Cardiac'),
	('Nicorandil', 'Cardiac'),
	('Isosorbide Mononitrate', 'Cardiac'),
	('Isosorbide Dinitrate', 'Cardiac'),
	('Glyceryl Trinitrate', 'Cardiac'),
	('Digoxin', 'Cardiac'),
	('Amiodarone', 'Cardiac'),
	('Propranolol', 'Antihypertensive'),
	('Diltiazem', 'Antihypertensive'),
	('Verapamil', 'Antihypertensive'),
	('Cilnidipine', 'Antihypertensive'),
	('Lercanidipine', 'Antihypertensive'),
	('Nifedipine', 'Antihypertensive'),
	('Labetalol', 'Antihypertensive'),
	('Methyldopa', 'Antihypertensive'),
	('Clonidine', 'Antihypertensive'),
	('Chlorthalidone', 'Antihypertensive'),
	('Indapamide', 'Antihypertensive'),
	('Torsemide', 'Antihypertensive'),
	('Eplerenone', 'Antihypertensive'),
	('Amlodipine + Valsartan', 'Antihypertensive'),
	('Valsartan + Hydrochlorothiazide', 'Antihypertensive'),
	('Pitavastatin', 'Lipid-lowering'),
	('Bempedoic Acid', 'Lipid-lowering'),
	('Saroglitazar', 'Lipid-lowering'),
	('Omega-3 Fatty Acids', 'Lipid-lowering'),
	('Warfarin', 'Anticoagulant'),
	('Apixaban', 'Anticoagulant'),
	('Rivaroxaban', 'Anticoagulant'),
	('Dabigatran Etexilate', 'Anticoagulant'),
	('Enoxaparin', 'Anticoagulant'),
	('Ticagrelor', 'Antiplatelet'),
	('Prasugrel', 'Antiplatelet'),
	('Cilostazol', 'Antiplatelet'),
	('Tranexamic Acid', 'Haemostatic'),
	('Ceftriaxone', 'Antibiotic'),
	('Cefotaxime', 'Antibiotic'),
	('Ceftazidime', 'Antibiotic'),
	('Cefepime', 'Antibiotic'),
	('Cefadroxil', 'Antibiotic'),
	('Cefaclor', 'Antibiotic'),
	('Cloxacillin', 'Antibiotic'),
	('Ampicillin + Cloxacillin', 'Antibiotic'),
	('Cefoperazone + Sulbactam', 'Antibiotic'),
	('Piperacillin + Tazobactam', 'Antibiotic'),
	('Meropenem', 'Antibiotic'),
	('Imipenem + Cilastatin', 'Antibiotic'),
	('Ertapenem', 'Antibiotic'),
	('Faropenem', 'Antibiotic'),
	('Vancomycin', 'Antibiotic'),
	('Teicoplanin', 'Antibiotic'),
	('Colistin', 'Antibiotic'),
	('Polymyxin B', 'Antibiotic'),
	('Tigecycline', 'Antibiotic'),
	('Clarithromycin', 'Antibiotic'),
	('Roxithromycin', 'Antibiotic'),
	('Moxifloxacin', 'Antibiotic'),
	('Gemifloxacin', 'Antibiotic'),
	('Nitrofurantoin', 'Antibiotic'),
	('Fosfomycin', 'Antibiotic'),
	('Chloramphenicol', 'Antibiotic'),
	('Amikacin', 'Antibiotic'),
	('Gentamicin', 'Antibiotic'),
	('Tobramycin', 'Antibiotic'),
	('Fusidic Acid', 'Antibiotic'),
	('Rifaximin', 'Antibiotic'),
	('Nitazoxanide', 'Antiprotozoal'),
	('Ornidazole', 'Antiprotozoal'),
	('Tinidazole', 'Antiprotozoal'),
	('Secnidazole', 'Antiprotozoal'),
	('Dapsone', 'Antibiotic'),
	('Rifampicin', 'Anti-TB'),
	('Isoniazid', 'Anti-TB'),
	('Pyrazinamide', 'Anti-TB'),
	('Ethambutol', 'Anti-TB'),
	('Bedaquiline', 'Anti-TB'),
	('Artemether + Lumefantrine', 'Antimalarial'),
	('Artesunate', 'Antimalarial'),
	('Dihydroartemisinin + Piperaquine', 'Antimalarial'),
	('Chloroquine', 'Antimalarial'),
	('Primaquine', 'Antimalarial'),
	('Mefloquine', 'Antimalarial'),
	('Quinine', 'Antimalarial'),
	('Sulfadoxine + Pyrimethamine', 'Antimalarial'),
	('Valacyclovir', 'Antiviral'),
	('Famciclovir', 'Antiviral'),
	('Valganciclovir', 'Antiviral'),
	('Remdesivir', 'Antiviral'),
	('Favipiravir', 'Antiviral'),
	('Molnupiravir', 'Antiviral'),
	('Nirmatrelvir + Ritonavir', 'Antiviral'),
	('Baloxavir Marboxil', 'Antiviral'),
	('Sofosbuvir', 'Antiviral'),
	('Sofosbuvir + Velpatasvir', 'Antiviral'),
	('Entecavir', 'Antiviral'),
	('Dolutegravir', 'Antiretroviral'),
	('Tenofovir + Lamivudine + Dolutegravir', 'Antiretroviral'),
	('Emtricitabine + Tenofovir', 'Antiretroviral'),
	('Voriconazole', 'Antifungal'),
	('Posaconazole', 'Antifungal'),
	('Amphotericin B', 'Antifungal'),
	('Griseofulvin', 'Antifungal'),
	('Nystatin', 'Antifungal'),
	('Sertaconazole', 'Antifungal'),
	('Miconazole', 'Antifungal'),
	('Praziquantel', 'Anthelmintic'),
	('Pyrantel Pamoate', 'Anthelmintic'),
	('Diethylcarbamazine', 'Anthelmintic'),
	('Risperidone', 'Antipsychotic'),
	('Olanzapine', 'Antipsychotic'),
	('Quetiapine', 'Antipsychotic'),
	('Aripiprazole', 'Antipsychotic'),
	('Clozapine', 'Antipsychotic'),
	('Haloperidol', 'Antipsychotic'),
	('Amisulpride', 'Antipsychotic'),
	('Lithium Carbonate', 'Mood Stabilizer'),
	('Oxcarbazepine', 'Anticonvulsant'),
	('Topiramate', 'Anticonvulsant'),
	('Lacosamide', 'Anticonvulsant'),
	('Brivaracetam', 'Anticonvulsant'),
	('Clobazam', 'Anticonvulsant'),
	('Divalproex Sodium', 'Anticonvulsant'),
	('Lorazepam', 'Anxiolytic'),
	('Bromazepam', 'Anxiolytic'),
	('Paroxetine', 'Antidepressant'),
	('Desvenlafaxine', 'Antidepressant'),
	('Bupropion', 'Antidepressant'),
	('Trazodone', 'Antidepressant'),
	('Buspirone', 'Anxiolytic'),
	('Vortioxetine', 'Antidepressant'),
	('Donepezil', 'Neurology'),
	('Memantine', 'Neurology'),
	('Rivastigmine', 'Neurology'),
	('Levodopa + Carbidopa', 'Neurology'),
	('Pramipexole', 'Neurology'),
	('Ropinirole', 'Neurology'),
	('Rasagiline', 'Neurology'),
	('Betahistine', 'Neurology'),
	('Cinnarizine', 'Neurology'),
	('Flunarizine', 'Neurology'),
	('Sumatriptan', 'Antimigraine'),
	('Rizatriptan', 'Antimigraine'),
	('Methylphenidate', 'CNS Stimulant'),
	('Atomoxetine', 'CNS Stimulant'),
	('Modafinil', 'CNS Stimulant'),
	('Nicotine', 'De-addiction'),
	('Doxofylline', 'Respiratory'),
	('Acebrophylline', 'Respiratory'),
	('Terbutaline', 'Respiratory'),
	('Salmeterol + Fluticasone', 'Respiratory'),
	('Fluticasone Furoate + Umeclidinium + Vilanterol', 'Respiratory'),
	('Glycopyrronium', 'Respiratory'),
	('Roflumilast', 'Respiratory'),
	('N-Acetylcysteine', 'Mucolytic'),
	('Levodropropizine', 'Antitussive'),
	('Fluticasone Propionate', 'Corticosteroid'),
	('Fluticasone Furoate', 'Corticosteroid'),
	('Beclomethasone', 'Corticosteroid'),
	('Xylometazoline', 'Nasal Decongestant'),
	('Oxymetazoline', 'Nasal Decongestant'),
	('Azelastine + Fluticasone', 'Respiratory/Allergy'),
	('Rupatadine', 'Antihistamine'),
	('Ebastine', 'Antihistamine'),
	('Ketotifen', 'Antihistamine'),
	('Olopatadine', 'Antihistamine'),
	('Loratadine + Pseudoephedrine', 'Antihistamine'),
	('Mosapride', 'GI/Prokinetic'),
	('Levosulpiride', 'GI/Prokinetic'),
	('Polyethylene Glycol', 'Laxative'),
	('Ispaghula Husk', 'Laxative'),
	('Mesalamine', 'GI/Anti-inflammatory'),
	('Sulfasalazine', 'GI/Anti-inflammatory'),
	('Ursodeoxycholic Acid', 'Hepatoprotective'),
	('Silymarin', 'Hepatoprotective'),
	('L-Ornithine L-Aspartate', 'Hepatoprotective'),
	('Racecadotril', 'Antidiarrhoeal'),
	('Saccharomyces Boulardii', 'Probiotic'),
	('Bacillus Clausii', 'Probiotic'),
	('Misoprostol', 'Gynaecology'),
	('Pancreatin', 'Digestive Enzyme'),
	('Simethicone', 'GI/Antiflatulent'),
	('Dicyclomine', 'GI/Antispasmodic'),
	('Mebeverine', 'GI/Antispasmodic'),
	('Hyoscine Butylbromide', 'GI/Antispasmodic'),
	('Doxylamine + Pyridoxine', 'Antiemetic'),
	('Aprepitant', 'Antiemetic'),
	('Diosmin + Hesperidin', 'Vascular'),
	('Bismuth Subsalicylate', 'GI/Antacid'),
	('Sodium Alginate', 'GI/Antacid'),
	('Deflazacort', 'Corticosteroid'),
	('Testosterone', 'Hormone'),
	('Medroxyprogesterone', 'Hormone'),
	('Levonorgestrel', 'Contraceptive'),
	('Ethinylestradiol + Levonorgestrel', 'Contraceptive'),
	('Desogestrel + Ethinylestradiol', 'Contraceptive'),
	('Drospirenone + Ethinylestradiol', 'Contraceptive'),
	('Clomiphene Citrate', 'Fertility'),
	('Dydrogesterone', 'Hormone'),
	('Alendronate', 'Bone/Calcium'),
	('Ibandronate', 'Bone/Calcium'),
	('Zoledronic Acid', 'Bone/Calcium'),
	('Teriparatide', 'Bone/Calcium'),
	('Denosumab', 'Bone/Calcium'),
	('Imatinib', 'Oncology'),
	('Gefitinib', 'Oncology'),
	('Osimertinib', 'Oncology'),
	('Lenalidomide', 'Oncology'),
	('Bortezomib', 'Oncology'),
	('Anastrozole', 'Oncology'),
	('Letrozole', 'Oncology'),
	('Tamoxifen', 'Oncology'),
	('Bicalutamide', 'Oncology'),
	('Abiraterone Acetate', 'Oncology'),
	('Enzalutamide', 'Oncology'),
	('Palbociclib', 'Oncology'),
	('Ribociclib', 'Oncology'),
	('Ibrutinib', 'Oncology'),
	('Capecitabine', 'Oncology'),
	('Methotrexate', 'Oncology/Immunology'),
	('Hydroxyurea', 'Oncology'),
	('Trastuzumab', 'Oncology/Biologic'),
	('Bevacizumab', 'Oncology/Biologic'),
	('Rituximab', 'Oncology/Biologic'),
	('Pembrolizumab', 'Oncology/Biologic'),
	('Nivolumab', 'Oncology/Biologic'),
	('Tacrolimus', 'Immunosuppressant'),
	('Cyclosporine', 'Immunosuppressant'),
	('Azathioprine', 'Immunosuppressant'),
	('Mycophenolate Mofetil', 'Immunosuppressant'),
	('Leflunomide', 'Immunosuppressant'),
	('Adalimumab', 'Biologic'),
	('Tofacitinib', 'Immunology'),
	('Upadacitinib', 'Immunology'),
	('Apremilast', 'Immunology'),
	('Secukinumab', 'Biologic'),
	('Omalizumab', 'Biologic'),
	('Dupilumab', 'Biologic'),
	('Mirabegron', 'Urology'),
	('Solifenacin', 'Urology'),
	('Alfuzosin', 'Urology'),
	('Silodosin', 'Urology'),
	('Dutasteride', 'Urology'),
	('Finasteride', 'Urology'),
	('Dapoxetine', 'Urology'),
	('Sevelamer', 'Nephrology'),
	('Febuxostat', 'Antigout'),
	('Tolvaptan', 'Nephrology'),
	('Ferric Carboxymaltose', 'Haematinic'),
	('Etoricoxib', 'Analgesic/NSAID'),
	('Celecoxib', 'Analgesic/NSAID'),
	('Meloxicam', 'Analgesic/NSAID'),
	('Diclofenac Potassium', 'Analgesic/NSAID'),
	('Thiocolchicoside', 'Muscle Relaxant'),
	('Tizanidine', 'Muscle Relaxant'),
	('Baclofen', 'Muscle Relaxant'),
	('Tapentadol', 'Analgesic/Opioid'),
	('Trypsin + Chymotrypsin', 'Anti-inflammatory Enzyme'),
	('Diacerein', 'Osteoarthritis'),
	('Glucosamine', 'Osteoarthritis'),
	('Isotretinoin', 'Dermatology'),
	('Tretinoin', 'Dermatology'),
	('Adapalene', 'Dermatology'),
	('Benzoyl Peroxide', 'Dermatology'),
	('Azelaic Acid', 'Dermatology'),
	('Salicylic Acid', 'Dermatology'),
	('Minoxidil', 'Dermatology'),
	('Hydroquinone', 'Dermatology'),
	('Dexpanthenol', 'Dermatology'),
	('Timolol', 'Ophthalmic'),
	('Latanoprost', 'Ophthalmic'),
	('Bimatoprost', 'Ophthalmic'),
	('Brimonidine', 'Ophthalmic'),
	('Brinzolamide', 'Ophthalmic'),
	('Carboxymethylcellulose', 'Ophthalmic'),
	('Sodium Hyaluronate', 'Ophthalmic'),
	('Natamycin', 'Ophthalmic'),
	('Methylcobalamin', 'Vitamin/Supplement'),
	('Alpha Lipoic Acid', 'Vitamin/Supplement'),
	('Coenzyme Q10', 'Vitamin/Supplement'),
	('Biotin', 'Vitamin/Supplement'),
	('Vitamin E', 'Vitamin/Supplement'),
	('Oral Rehydration Salts', 'Electrolyte')
ON CONFLICT (name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2) manufacturer_master — Indian, Gulf, African, Asian and global companies
-- ---------------------------------------------------------------------------
INSERT INTO public.manufacturer_master (name, country, website) VALUES
	('Emcure', 'India', 'https://www.emcure.com'),
	('Eris Lifesciences', 'India', 'https://www.eris.co.in'),
	('Hetero', 'India', 'https://www.heteroworld.com'),
	('Natco', 'India', 'https://www.natcopharma.co.in'),
	('Aurobindo', 'India', 'https://www.aurobindo.com'),
	('Wockhardt', 'India', 'https://www.wockhardt.com'),
	('Unichem', 'India', 'https://www.unichemlabs.com'),
	('Indoco', 'India', 'https://www.indoco.com'),
	('FDC', 'India', 'https://www.fdcindia.com'),
	('Blue Cross', 'India', 'https://www.bluecrosslabs.com'),
	('Corona Remedies', 'India', 'https://www.coronaremedies.com'),
	('La Renon', 'India', 'https://www.larenon.com'),
	('Zuventus', 'India', 'https://www.zuventus.com'),
	('Leeford', 'India', 'https://www.leeford.in'),
	('Systopic', 'India', 'https://www.systopic.com'),
	('Troikaa', 'India', 'https://www.troikaapharma.com'),
	('Gufic', 'India', 'https://www.guficbio.com'),
	('Medley', 'India', 'https://www.medleylab.com'),
	('Modi-Mundipharma', 'India', 'https://www.modi-mundipharma.com'),
	('Walter Bushnell', 'India', 'https://www.walterbushnell.com'),
	('Raptakos', 'India', 'https://www.raptakos.com'),
	('TTK Healthcare', 'India', 'https://www.ttkhealthcare.com'),
	('Albert David', 'India', 'https://www.albertdavidindia.com'),
	('Themis Medicare', 'India', 'https://www.themismedicare.com'),
	('Bharat Serums', 'India', 'https://www.bharatserums.com'),
	('Serum Institute of India', 'India', 'https://www.seruminstitute.com'),
	('Bharat Biotech', 'India', 'https://www.bharatbiotech.com'),
	('Biological E', 'India', 'https://www.biologicale.com'),
	('Sanzyme', 'India', 'https://www.sanzyme.com'),
	('Strides Pharma', 'India', 'https://www.strides.com'),
	('Zota Healthcare', 'India', 'https://www.zotahealthcare.com'),
	('PMBI', 'India', 'https://janaushadhi.gov.in'),
	('Akumentis', 'India', 'https://www.akumentis.com'),
	('Bliss GVS', 'India', 'https://www.blissgvs.com'),
	('Dabur', 'India', 'https://www.dabur.com'),
	('Himalaya Wellness', 'India', 'https://himalayawellness.in'),
	('Emami', 'India', 'https://www.emamiltd.in'),
	('Baidyanath', 'India', 'https://www.baidyanath.co.in'),
	('Charak', 'India', 'https://www.charak.com'),
	('Hamdard', 'India', 'https://www.hamdard.in'),
	('Amrutanjan', 'India', 'https://www.amrutanjan.com'),
	('Vicco', 'India', 'https://www.vicco.in'),
	('Zydus Wellness', 'India', 'https://www.zyduswellness.com'),
	('ITC', 'India', 'https://www.itcportal.com'),
	('HMD', 'India', 'https://www.hmdhealthcare.com'),
	('Morepen', 'India', 'https://www.morepen.com'),
	('G.D. Pharmaceuticals', 'India', 'https://www.boroline.com'),
	('Takeda', 'Japan', 'https://www.takeda.com'),
	('Teva', 'Israel', 'https://www.tevapharm.com'),
	('Viatris', 'USA', 'https://www.viatris.com'),
	('Mylan', 'USA', 'https://www.viatris.com'),
	('Organon', 'USA', 'https://www.organon.com'),
	('Haleon', 'UK', 'https://www.haleon.com'),
	('Kenvue', 'USA', 'https://www.kenvue.com'),
	('P&G Health', 'USA', 'https://www.pghealth.com'),
	('Amgen', 'USA', 'https://www.amgen.com'),
	('Gilead', 'USA', 'https://www.gilead.com'),
	('Bristol Myers Squibb', 'USA', 'https://www.bms.com'),
	('AbbVie', 'USA', 'https://www.abbvie.com'),
	('Otsuka', 'Japan', 'https://www.otsuka.com'),
	('Eisai', 'Japan', 'https://www.eisai.com'),
	('Ferring', 'Switzerland', 'https://www.ferring.com'),
	('LEO Pharma', 'Denmark', 'https://www.leo-pharma.com'),
	('Chiesi', 'Italy', 'https://www.chiesi.com'),
	('Zambon', 'Italy', 'https://www.zambon.com'),
	('Krka', 'Slovenia', 'https://www.krka.biz'),
	('Gedeon Richter', 'Hungary', 'https://www.gedeonrichter.com'),
	('Zentiva', 'Czech Republic', 'https://www.zentiva.com'),
	('Sandoz', 'Switzerland', 'https://www.sandoz.com'),
	('Fresenius Kabi', 'Germany', 'https://www.fresenius-kabi.com'),
	('B. Braun', 'Germany', 'https://www.bbraun.com'),
	('Baxter', 'USA', 'https://www.baxter.com'),
	('Alcon', 'Switzerland', 'https://www.alcon.com'),
	('Allergan', 'Ireland', 'https://www.abbvie.com'),
	('Hisamitsu', 'Japan', 'https://www.hisamitsu.co.jp'),
	('Omron Healthcare', 'Japan', 'https://www.omronhealthcare.com'),
	('Nestle', 'Switzerland', 'https://www.nestle.com'),
	('Danone', 'France', 'https://www.danone.com'),
	('Mentholatum', 'USA', 'https://www.mentholatum.com'),
	('Haw Par', 'Singapore', 'https://www.hawpar.com'),
	('Julphar', 'UAE', 'https://www.julphar.net'),
	('Neopharma', 'UAE', 'https://www.neopharmauae.com'),
	('Globalpharma', 'UAE', 'https://www.globalpharma.ae'),
	('Hikma', 'Jordan', 'https://www.hikma.com'),
	('SPIMACO', 'Saudi Arabia', 'https://www.spimaco.com.sa'),
	('Jamjoom Pharma', 'Saudi Arabia', 'https://www.jamjoompharma.com'),
	('Tabuk Pharmaceuticals', 'Saudi Arabia', 'https://www.tabukpharmaceuticals.com'),
	('Riyadh Pharma', 'Saudi Arabia', 'https://www.riyadhpharma.com'),
	('Dar Al Dawa', 'Jordan', 'https://www.dadgroup.com'),
	('National Pharmaceutical Industries', 'Oman', 'https://www.npi.co.om'),
	('Oman Pharmaceutical Products', 'Oman', NULL),
	('Aspen Pharmacare', 'South Africa', 'https://www.aspenpharma.com'),
	('Adcock Ingram', 'South Africa', 'https://www.adcock.com'),
	('Beta Healthcare', 'Kenya', 'https://www.betahealthcare.co.ke'),
	('Cosmos Pharmaceutical', 'Kenya', 'https://www.cosmos-pharm.com'),
	('Universal Corporation', 'Kenya', 'https://www.universalcorporation.com'),
	('Dawa Limited', 'Kenya', 'https://www.dawalimited.co.ke'),
	('Lab & Allied', 'Kenya', 'https://www.laballied.com'),
	('Regal Pharmaceuticals', 'Kenya', 'https://www.regalpharmaceuticals.com'),
	('Shelys Pharmaceuticals', 'Tanzania', 'https://www.shelys.com'),
	('Emzor Pharmaceutical', 'Nigeria', 'https://www.emzorpharma.com'),
	('EIPICO', 'Egypt', 'https://www.eipico.com.eg'),
	('Square Pharmaceuticals', 'Bangladesh', 'https://www.squarepharma.com.bd'),
	('Beximco Pharma', 'Bangladesh', 'https://www.beximcopharma.com'),
	('Incepta', 'Bangladesh', 'https://www.inceptapharma.com'),
	('Getz Pharma', 'Pakistan', 'https://www.getzpharma.com'),
	('Mega Lifesciences', 'Thailand', 'https://www.megawecare.com')
ON CONFLICT (name) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3a) drug_master — Gulf / GCC retail brands (UAE, Saudi, Oman pharmacy
--     staples; supports the AE/OM expansion). MRP NULL — priced in AED/SAR/OMR
--     locally, orgs set their own price at item creation.
-- ---------------------------------------------------------------------------
WITH new_drugs (brand_name, generic_name, salt_composition, manufacturer,
                hsn_code, gst_rate, drug_schedule, dosage_form, pack_size,
                mrp, prescription_required) AS (
	VALUES
	('Panadol Advance', 'Paracetamol', 'Paracetamol 500mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Tablet', '48 Tablets', NULL, false),
	('Panadol Extra', 'Paracetamol + Caffeine', 'Paracetamol 500mg + Caffeine 65mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Panadol Cold + Flu Day', 'Paracetamol + Phenylephrine + Chlorpheniramine', 'Paracetamol 500mg + Phenylephrine 5mg + Chlorpheniramine 2mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Panadol Night', 'Paracetamol + Diphenhydramine', 'Paracetamol 500mg + Diphenhydramine 25mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Panadol Baby Suspension', 'Paracetamol', 'Paracetamol 120mg/5ml', 'Haleon', '3004', 5.00, 'GENERAL', 'Syrup', '100 ml', NULL, false),
	('Adol 500', 'Paracetamol', 'Paracetamol 500mg', 'Julphar', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Adol Extra', 'Paracetamol + Caffeine', 'Paracetamol 500mg + Caffeine 65mg', 'Julphar', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Adol 250 Suppository', 'Paracetamol', 'Paracetamol 250mg', 'Julphar', '3004', 5.00, 'GENERAL', 'Suppository', '10 Suppositories', NULL, false),
	('Profinal 400', 'Ibuprofen', 'Ibuprofen 400mg', 'Julphar', '3004', 5.00, 'GENERAL', 'Tablet', '30 Tablets', NULL, false),
	('Profinal Suspension', 'Ibuprofen', 'Ibuprofen 100mg/5ml', 'Julphar', '3004', 5.00, 'GENERAL', 'Syrup', '100 ml', NULL, false),
	('Fevadol 500', 'Paracetamol', 'Paracetamol 500mg', 'SPIMACO', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Fevadol Extra', 'Paracetamol + Caffeine', 'Paracetamol 500mg + Caffeine 65mg', 'SPIMACO', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Ponstan 500', 'Mefenamic Acid', 'Mefenamic Acid 500mg', 'Pfizer', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Julphamox 500', 'Amoxicillin', 'Amoxicillin 500mg', 'Julphar', '3004', 5.00, 'H', 'Capsule', '20 Capsules', NULL, true),
	('Julmentin 2X 625', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin 500mg + Clavulanic Acid 125mg', 'Julphar', '3004', 5.00, 'H', 'Tablet', '20 Tablets', NULL, true),
	('Megamox 625', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin 500mg + Clavulanic Acid 125mg', 'SPIMACO', '3004', 5.00, 'H', 'Tablet', '20 Tablets', NULL, true),
	('Amoclan 625', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin 500mg + Clavulanic Acid 125mg', 'Hikma', '3004', 5.00, 'H', 'Tablet', '20 Tablets', NULL, true),
	('Suprax 400', 'Cefixime', 'Cefixime 400mg', 'Hikma', '3004', 5.00, 'H1', 'Capsule', '5 Capsules', NULL, true),
	('Klacid 500', 'Clarithromycin', 'Clarithromycin 500mg', 'Abbott', '3004', 5.00, 'H', 'Tablet', '14 Tablets', NULL, true),
	('Zinnat 500', 'Cefuroxime', 'Cefuroxime Axetil 500mg', 'GSK', '3004', 5.00, 'H', 'Tablet', '10 Tablets', NULL, true),
	('Zithromax 500', 'Azithromycin', 'Azithromycin 500mg', 'Pfizer', '3004', 5.00, 'H1', 'Tablet', '3 Tablets', NULL, true),
	('Ciprobay 500', 'Ciprofloxacin HCl', 'Ciprofloxacin 500mg', 'Bayer', '3004', 5.00, 'H', 'Tablet', '10 Tablets', NULL, true),
	('Tavanic 500', 'Levofloxacin', 'Levofloxacin 500mg', 'Sanofi', '3004', 5.00, 'H1', 'Tablet', '7 Tablets', NULL, true),
	('Avelox 400', 'Moxifloxacin', 'Moxifloxacin 400mg', 'Bayer', '3004', 5.00, 'H1', 'Tablet', '5 Tablets', NULL, true),
	('Rocephin 1g Injection', 'Ceftriaxone', 'Ceftriaxone 1g', 'Roche', '3004', 5.00, 'H1', 'Injection', '1 Vial', NULL, true),
	('Tazocin 4.5g Injection', 'Piperacillin + Tazobactam', 'Piperacillin 4g + Tazobactam 500mg', 'Pfizer', '3004', 5.00, 'H', 'Injection', '1 Vial', NULL, true),
	('Meronem 1g Injection', 'Meropenem', 'Meropenem 1g', 'Pfizer', '3004', 5.00, 'H1', 'Injection', '1 Vial', NULL, true),
	('Zyvox 600', 'Linezolid', 'Linezolid 600mg', 'Pfizer', '3004', 5.00, 'H1', 'Tablet', '10 Tablets', NULL, true),
	('Targocid 400 Injection', 'Teicoplanin', 'Teicoplanin 400mg', 'Sanofi', '3004', 5.00, 'H', 'Injection', '1 Vial', NULL, true),
	('Augmentin 1g', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin 875mg + Clavulanic Acid 125mg', 'GSK', '3004', 5.00, 'H', 'Tablet', '14 Tablets', NULL, true),
	('Flagyl 500', 'Metronidazole', 'Metronidazole 500mg', 'Sanofi', '3004', 5.00, 'H', 'Tablet', '20 Tablets', NULL, true),
	('Telfast 180', 'Fexofenadine', 'Fexofenadine 180mg', 'Sanofi', '3004', 5.00, 'GENERAL', 'Tablet', '30 Tablets', NULL, false),
	('Aerius 5mg', 'Desloratadine', 'Desloratadine 5mg', 'Organon', '3004', 5.00, 'GENERAL', 'Tablet', '30 Tablets', NULL, false),
	('Clarinase Repetabs', 'Loratadine + Pseudoephedrine', 'Loratadine 5mg + Pseudoephedrine 120mg', 'Organon', '3004', 5.00, 'GENERAL', 'Tablet', '14 Tablets', NULL, false),
	('Zyrtec 10', 'Cetirizine', 'Cetirizine 10mg', 'UCB', '3004', 5.00, 'GENERAL', 'Tablet', '30 Tablets', NULL, false),
	('Xyzal 5', 'Levocetirizine', 'Levocetirizine 5mg', 'UCB', '3004', 5.00, 'GENERAL', 'Tablet', '30 Tablets', NULL, false),
	('Otrivin 0.1% Nasal Spray', 'Xylometazoline', 'Xylometazoline 0.1%', 'Haleon', '3004', 5.00, 'GENERAL', 'Nasal Spray', '10 ml', NULL, false),
	('Strepsils Original', 'Amylmetacresol + Dichlorobenzyl Alcohol', 'Amylmetacresol 0.6mg + 2,4-Dichlorobenzyl Alcohol 1.2mg', 'Reckitt', '3004', 5.00, 'GENERAL', 'Lozenge', '24 Lozenges', NULL, false),
	('Gaviscon Peppermint Liquid', 'Sodium Alginate', 'Sodium Alginate 250mg + Sodium Bicarbonate 133.5mg/5ml', 'Reckitt', '3004', 5.00, 'GENERAL', 'Suspension', '200 ml', NULL, false),
	('Rennie Spearmint', 'Calcium Carbonate', 'Calcium Carbonate 680mg + Magnesium Carbonate 80mg', 'Bayer', '3004', 5.00, 'GENERAL', 'Chewable Tablet', '36 Tablets', NULL, false),
	('Nexium 40', 'Esomeprazole', 'Esomeprazole 40mg', 'AstraZeneca', '3004', 5.00, 'H', 'Tablet', '14 Tablets', NULL, true),
	('Losec 20', 'Omeprazole', 'Omeprazole 20mg', 'AstraZeneca', '3004', 5.00, 'H', 'Capsule', '14 Capsules', NULL, true),
	('Pariet 20', 'Rabeprazole', 'Rabeprazole 20mg', 'Eisai', '3004', 5.00, 'H', 'Tablet', '14 Tablets', NULL, true),
	('Controloc 40', 'Pantoprazole', 'Pantoprazole 40mg', 'Takeda', '3004', 5.00, 'H', 'Tablet', '14 Tablets', NULL, true),
	('Motilium 10', 'Domperidone', 'Domperidone 10mg', 'Janssen', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Buscopan 10', 'Hyoscine Butylbromide', 'Hyoscine Butylbromide 10mg', 'Boehringer', '3004', 5.00, 'GENERAL', 'Tablet', '20 Tablets', NULL, false),
	('Duspatalin Retard 200', 'Mebeverine', 'Mebeverine 200mg', 'Abbott', '3004', 5.00, 'H', 'Capsule', '30 Capsules', NULL, true),
	('Imodium 2mg', 'Loperamide HCl', 'Loperamide 2mg', 'Janssen', '3004', 5.00, 'GENERAL', 'Capsule', '12 Capsules', NULL, false),
	('Fucidin Cream', 'Fusidic Acid', 'Fusidic Acid 2%', 'LEO Pharma', '3004', 5.00, 'H', 'Cream', '15 g', NULL, true),
	('Elocon Cream', 'Mometasone Furoate', 'Mometasone Furoate 0.1%', 'Organon', '3004', 5.00, 'H', 'Cream', '15 g', NULL, true),
	('Daktarin Oral Gel', 'Miconazole', 'Miconazole 2%', 'Janssen', '3004', 5.00, 'GENERAL', 'Gel', '40 g', NULL, false),
	('Canesten Cream', 'Clotrimazole', 'Clotrimazole 1%', 'Bayer', '3004', 5.00, 'GENERAL', 'Cream', '20 g', NULL, false),
	('Lamisil Cream', 'Terbinafine', 'Terbinafine 1%', 'Haleon', '3004', 5.00, 'GENERAL', 'Cream', '15 g', NULL, false),
	('Bepanthen Ointment', 'Dexpanthenol', 'Dexpanthenol 5%', 'Bayer', '3004', 5.00, 'GENERAL', 'Ointment', '30 g', NULL, false),
	('Cetaphil Gentle Skin Cleanser', NULL, 'Dermatological cleanser (soap-free)', 'Galderma', '3304', 18.00, 'GENERAL', 'Liquid', '250 ml', NULL, false),
	('Voltaren Emulgel', 'Diclofenac Diethylamine', 'Diclofenac Diethylamine 1.16%', 'Novartis', '3004', 5.00, 'GENERAL', 'Gel', '50 g', NULL, false),
	('Cataflam 50', 'Diclofenac Potassium', 'Diclofenac Potassium 50mg', 'Novartis', '3004', 5.00, 'H', 'Tablet', '20 Tablets', NULL, true),
	('Celebrex 200', 'Celecoxib', 'Celecoxib 200mg', 'Pfizer', '3004', 5.00, 'H', 'Capsule', '30 Capsules', NULL, true),
	('Mobic 15', 'Meloxicam', 'Meloxicam 15mg', 'Boehringer', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Concor 5', 'Bisoprolol', 'Bisoprolol 5mg', 'Merck', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Nebilet 5', 'Nebivolol HCl', 'Nebivolol 5mg', 'Menarini', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Exforge 5/80', 'Amlodipine + Valsartan', 'Amlodipine 5mg + Valsartan 80mg', 'Novartis', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Co-Diovan 80/12.5', 'Valsartan + Hydrochlorothiazide', 'Valsartan 80mg + Hydrochlorothiazide 12.5mg', 'Novartis', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Micardis 40', 'Telmisartan', 'Telmisartan 40mg', 'Boehringer', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Norvasc 5', 'Amlodipine', 'Amlodipine 5mg', 'Viatris', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Tritace 5', 'Ramipril', 'Ramipril 5mg', 'Sanofi', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Euthyrox 50', 'Levothyroxine', 'Levothyroxine 50mcg', 'Merck', '3004', 5.00, 'H', 'Tablet', '100 Tablets', NULL, true),
	('Glucophage XR 500', 'Metformin', 'Metformin 500mg', 'Merck', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Forxiga 10', 'Dapagliflozin', 'Dapagliflozin 10mg', 'AstraZeneca', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Jardiance 10', 'Empagliflozin', 'Empagliflozin 10mg', 'Boehringer', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Ozempic 1mg Pen', 'Semaglutide', 'Semaglutide 1mg/dose', 'Novo Nordisk', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Wegovy 2.4mg Pen', 'Semaglutide', 'Semaglutide 2.4mg/dose', 'Novo Nordisk', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Rybelsus 7', 'Semaglutide', 'Semaglutide 7mg', 'Novo Nordisk', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Mounjaro 5mg Vial', 'Tirzepatide', 'Tirzepatide 5mg', 'Eli Lilly', '3004', 5.00, 'H', 'Injection', '1 Vial', NULL, true),
	('Trulicity 1.5mg Pen', 'Dulaglutide', 'Dulaglutide 1.5mg/0.5ml', 'Eli Lilly', '3004', 5.00, 'H', 'Injection', '2 Pens', NULL, true),
	('Victoza Pen', 'Liraglutide', 'Liraglutide 6mg/ml', 'Novo Nordisk', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Saxenda Pen', 'Liraglutide', 'Liraglutide 6mg/ml', 'Novo Nordisk', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('NovoRapid FlexPen', 'Insulin Aspart', 'Insulin Aspart 100IU/ml', 'Novo Nordisk', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Tresiba FlexTouch', 'Insulin Degludec', 'Insulin Degludec 100IU/ml', 'Novo Nordisk', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Levemir FlexPen', 'Insulin Detemir', 'Insulin Detemir 100IU/ml', 'Novo Nordisk', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Toujeo SoloStar', 'Insulin Glargine', 'Insulin Glargine 300IU/ml', 'Sanofi', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Humalog KwikPen', 'Insulin Lispro', 'Insulin Lispro 100IU/ml', 'Eli Lilly', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Xanax 0.5', 'Alprazolam', 'Alprazolam 0.5mg', 'Viatris', '3004', 5.00, 'H1', 'Tablet', '30 Tablets', NULL, true),
	('Lexotanil 3', 'Bromazepam', 'Bromazepam 3mg', 'Roche', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Rivotril 0.5', 'Clonazepam', 'Clonazepam 0.5mg', 'Roche', '3004', 5.00, 'H1', 'Tablet', '30 Tablets', NULL, true),
	('Stilnox 10', 'Zolpidem', 'Zolpidem 10mg', 'Sanofi', '3004', 5.00, 'H1', 'Tablet', '14 Tablets', NULL, true),
	('Cipralex 10', 'Escitalopram', 'Escitalopram 10mg', 'Lundbeck', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Seroxat 20', 'Paroxetine', 'Paroxetine 20mg', 'GSK', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Prozac 20', 'Fluoxetine', 'Fluoxetine 20mg', 'Eli Lilly', '3004', 5.00, 'H', 'Capsule', '28 Capsules', NULL, true),
	('Zoloft 50', 'Sertraline', 'Sertraline 50mg', 'Viatris', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Keppra 500', 'Levetiracetam', 'Levetiracetam 500mg', 'UCB', '3004', 5.00, 'H', 'Tablet', '60 Tablets', NULL, true),
	('Neurontin 300', 'Gabapentin', 'Gabapentin 300mg', 'Viatris', '3004', 5.00, 'H', 'Capsule', '50 Capsules', NULL, true),
	('Lyrica 75', 'Pregabalin', 'Pregabalin 75mg', 'Pfizer', '3004', 5.00, 'H', 'Capsule', '14 Capsules', NULL, true),
	('Depakine Chrono 500', 'Valproate Sodium', 'Sodium Valproate 333mg + Valproic Acid 145mg', 'Sanofi', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Aspirin Protect 100', 'Aspirin', 'Aspirin 100mg', 'Bayer', '3004', 5.00, 'GENERAL', 'Tablet', '30 Tablets', NULL, false),
	('Plavix 75', 'Clopidogrel', 'Clopidogrel 75mg', 'Sanofi', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Xarelto 20', 'Rivaroxaban', 'Rivaroxaban 20mg', 'Bayer', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Eliquis 5', 'Apixaban', 'Apixaban 5mg', 'Pfizer', '3004', 5.00, 'H', 'Tablet', '60 Tablets', NULL, true),
	('Clexane 40 Injection', 'Enoxaparin', 'Enoxaparin 40mg/0.4ml', 'Sanofi', '3004', 5.00, 'H', 'Injection', '2 Prefilled Syringes', NULL, true),
	('Lipitor 20', 'Atorvastatin', 'Atorvastatin 20mg', 'Viatris', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Crestor 10', 'Rosuvastatin', 'Rosuvastatin 10mg', 'AstraZeneca', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Seretide Diskus 250', 'Salmeterol + Fluticasone', 'Salmeterol 50mcg + Fluticasone Propionate 250mcg', 'GSK', '3004', 5.00, 'H', 'Inhaler', '60 Doses', NULL, true),
	('Symbicort Turbuhaler 160/4.5', 'Budesonide + Formoterol', 'Budesonide 160mcg + Formoterol 4.5mcg', 'AstraZeneca', '3004', 5.00, 'H', 'Inhaler', '120 Doses', NULL, true),
	('Nasonex Nasal Spray', 'Mometasone Furoate', 'Mometasone Furoate 50mcg/dose', 'Organon', '3004', 5.00, 'H', 'Nasal Spray', '140 Doses', NULL, true),
	('Avamys Nasal Spray', 'Fluticasone Furoate', 'Fluticasone Furoate 27.5mcg/dose', 'GSK', '3004', 5.00, 'H', 'Nasal Spray', '120 Doses', NULL, true),
	('Omnic Ocas 0.4', 'Tamsulosin HCl', 'Tamsulosin 0.4mg', 'Astellas', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Proscar 5', 'Finasteride', 'Finasteride 5mg', 'Organon', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Cialis 20', 'Tadalafil', 'Tadalafil 20mg', 'Eli Lilly', '3004', 5.00, 'H', 'Tablet', '4 Tablets', NULL, true),
	('Viagra 100', 'Sildenafil Citrate', 'Sildenafil 100mg', 'Viatris', '3004', 5.00, 'H', 'Tablet', '4 Tablets', NULL, true),
	('Vermox 500', 'Mebendazole', 'Mebendazole 500mg', 'Janssen', '3004', 5.00, 'GENERAL', 'Tablet', '1 Tablet', NULL, false),
	('Zentel 400', 'Albendazole', 'Albendazole 400mg', 'GSK', '3004', 5.00, 'GENERAL', 'Tablet', '1 Tablet', NULL, false),
	('Diflucan 150', 'Fluconazole', 'Fluconazole 150mg', 'Pfizer', '3004', 5.00, 'H', 'Capsule', '1 Capsule', NULL, true),
	('Sporanox 100', 'Itraconazole', 'Itraconazole 100mg', 'Janssen', '3004', 5.00, 'H', 'Capsule', '15 Capsules', NULL, true),
	('Valtrex 500', 'Valacyclovir', 'Valacyclovir 500mg', 'GSK', '3004', 5.00, 'H', 'Tablet', '10 Tablets', NULL, true),
	('Tamiflu 75', 'Oseltamivir Phosphate', 'Oseltamivir 75mg', 'Roche', '3004', 5.00, 'H1', 'Capsule', '10 Capsules', NULL, true)
)
INSERT INTO public.drug_master
	(brand_name, generic_name, salt_id, salt_composition, manufacturer,
	 hsn_code, gst_rate, drug_schedule, dosage_form, pack_size, mrp,
	 prescription_required, is_active)
SELECT DISTINCT ON (lower(nd.brand_name))
	nd.brand_name, nd.generic_name, sm.id, nd.salt_composition, nd.manufacturer,
	nd.hsn_code, nd.gst_rate::numeric, nd.drug_schedule, nd.dosage_form,
	nd.pack_size, nd.mrp::numeric, nd.prescription_required::boolean, true
FROM new_drugs nd
LEFT JOIN public.salt_master sm ON lower(sm.name) = lower(nd.generic_name)
WHERE NOT EXISTS (
	SELECT 1 FROM public.drug_master d
	WHERE lower(d.brand_name) = lower(nd.brand_name))
ORDER BY lower(nd.brand_name);

-- ---------------------------------------------------------------------------
-- 3b) drug_master — East & South Africa staples (Kenya focus for the KE
--     expansion; antimalarials + trade OTC every duka la dawa carries).
-- ---------------------------------------------------------------------------
WITH new_drugs (brand_name, generic_name, salt_composition, manufacturer,
                hsn_code, gst_rate, drug_schedule, dosage_form, pack_size,
                mrp, prescription_required) AS (
	VALUES
	('Mara Moja', 'Aspirin + Paracetamol + Caffeine', 'Aspirin 250mg + Paracetamol 250mg + Caffeine 32.5mg', 'Beta Healthcare', '3004', 5.00, 'GENERAL', 'Tablet', '12 Tablets', NULL, false),
	('Hedex', 'Paracetamol', 'Paracetamol 500mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Tablet', '16 Tablets', NULL, false),
	('Hedex Extra', 'Paracetamol + Caffeine', 'Paracetamol 500mg + Caffeine 65mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Tablet', '16 Tablets', NULL, false),
	('Action', 'Aspirin + Caffeine', 'Aspirin 400mg + Caffeine 32mg', 'Shelys Pharmaceuticals', '3004', 5.00, 'GENERAL', 'Tablet', '12 Tablets', NULL, false),
	('Panado 500', 'Paracetamol', 'Paracetamol 500mg', 'Adcock Ingram', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Grand-Pa Headache Powder', 'Aspirin + Paracetamol + Caffeine', 'Aspirin 453mg + Paracetamol 324mg + Caffeine 65mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Powder', '38 Sachets', NULL, false),
	('Med-Lemon Hot Medication', 'Paracetamol + Vitamin C', 'Paracetamol 500mg + Ascorbic Acid 50mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Sachet', '10 Sachets', NULL, false),
	('Corenza C', 'Aspirin + Chlorpheniramine + Vitamin C', 'Aspirin 300mg + Chlorpheniramine 2mg + Ascorbic Acid 100mg', 'Adcock Ingram', '3004', 5.00, 'GENERAL', 'Tablet', '20 Tablets', NULL, false),
	('Sinutab', 'Paracetamol + Pseudoephedrine', 'Paracetamol 500mg + Pseudoephedrine 30mg', 'Kenvue', '3004', 5.00, 'GENERAL', 'Tablet', '25 Tablets', NULL, false),
	('Allergex', 'Chlorpheniramine Maleate', 'Chlorpheniramine 4mg', 'Adcock Ingram', '3004', 5.00, 'GENERAL', 'Tablet', '30 Tablets', NULL, false),
	('Piriton', 'Chlorpheniramine Maleate', 'Chlorpheniramine 4mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Tablet', '30 Tablets', NULL, false),
	('Benylin Wet Cough Syrup', 'Diphenhydramine + Ammonium Chloride + Sodium Citrate', 'Diphenhydramine 14mg + Ammonium Chloride 135mg/5ml', 'Kenvue', '3004', 5.00, 'GENERAL', 'Syrup', '100 ml', NULL, false),
	('Coartem 20/120', 'Artemether + Lumefantrine', 'Artemether 20mg + Lumefantrine 120mg', 'Novartis', '3004', 5.00, 'H', 'Tablet', '24 Tablets', NULL, true),
	('Lonart DS', 'Artemether + Lumefantrine', 'Artemether 80mg + Lumefantrine 480mg', 'Bliss GVS', '3004', 5.00, 'H', 'Tablet', '6 Tablets', NULL, true),
	('Artefan 20/120', 'Artemether + Lumefantrine', 'Artemether 20mg + Lumefantrine 120mg', 'Ajanta', '3004', 5.00, 'H', 'Tablet', '24 Tablets', NULL, true),
	('Lumartem', 'Artemether + Lumefantrine', 'Artemether 20mg + Lumefantrine 120mg', 'Cipla', '3004', 5.00, 'H', 'Tablet', '24 Tablets', NULL, true),
	('P-Alaxin', 'Dihydroartemisinin + Piperaquine', 'Dihydroartemisinin 40mg + Piperaquine 320mg', 'Bliss GVS', '3004', 5.00, 'H', 'Tablet', '9 Tablets', NULL, true),
	('Duo-Cotecxin', 'Dihydroartemisinin + Piperaquine', 'Dihydroartemisinin 40mg + Piperaquine 320mg', 'Various', '3004', 5.00, 'H', 'Tablet', '9 Tablets', NULL, true),
	('Fansidar', 'Sulfadoxine + Pyrimethamine', 'Sulfadoxine 500mg + Pyrimethamine 25mg', 'Roche', '3004', 5.00, 'H', 'Tablet', '3 Tablets', NULL, true),
	('Malaraquin', 'Chloroquine', 'Chloroquine Phosphate 250mg', 'Cosmos Pharmaceutical', '3004', 5.00, 'H', 'Tablet', '10 Tablets', NULL, true),
	('Amoxil 500', 'Amoxicillin', 'Amoxicillin 500mg', 'GSK', '3004', 5.00, 'H', 'Capsule', '20 Capsules', NULL, true),
	('Ampiclox 500', 'Ampicillin + Cloxacillin', 'Ampicillin 250mg + Cloxacillin 250mg', 'GSK', '3004', 5.00, 'H', 'Capsule', '20 Capsules', NULL, true),
	('Septrin 480', 'Co-trimoxazole', 'Sulfamethoxazole 400mg + Trimethoprim 80mg', 'GSK', '3004', 5.00, 'H', 'Tablet', '20 Tablets', NULL, true),
	('Dawanol', 'Paracetamol', 'Paracetamol 500mg', 'Dawa Limited', '3004', 5.00, 'GENERAL', 'Tablet', '20 Tablets', NULL, false),
	('Emzor Paracetamol', 'Paracetamol', 'Paracetamol 500mg', 'Emzor Pharmaceutical', '3004', 5.00, 'GENERAL', 'Tablet', '96 Tablets', NULL, false),
	('Panadrex 500', 'Paracetamol', 'Paracetamol 500mg', 'National Pharmaceutical Industries', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Actal', 'Alexitol Sodium', 'Alexitol Sodium 360mg', 'Sanofi', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Eno Fruit Salt Regular', 'Sodium Bicarbonate + Citric Acid', 'Sodium Bicarbonate 2.32g + Citric Acid 2.18g/5g', 'Haleon', '3004', 5.00, 'GENERAL', 'Powder', '100 g', 55.00, false),
	('Acriptega', 'Tenofovir + Lamivudine + Dolutegravir', 'Tenofovir Disoproxil 300mg + Lamivudine 300mg + Dolutegravir 50mg', 'Mylan', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Truvada', 'Emtricitabine + Tenofovir', 'Emtricitabine 200mg + Tenofovir Disoproxil 300mg', 'Gilead', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Deep Heat Rub', 'Methyl Salicylate + Menthol + Eucalyptus Oil', 'Methyl Salicylate 12.8% + Menthol 5.91%', 'Mentholatum', '3004', 5.00, 'GENERAL', 'Cream', '35 g', NULL, false),
	('Mentholatum Balm', 'Menthol + Camphor', 'Menthol 6% + Camphor 9%', 'Mentholatum', '3004', 5.00, 'GENERAL', 'Balm', '30 g', NULL, false),
	('Tiger Balm Red', 'Menthol + Camphor + Clove Oil', 'Camphor 11% + Menthol 10% + Clove Oil 5%', 'Haw Par', '3004', 5.00, 'GENERAL', 'Balm', '19 g', 120.00, false)
)
INSERT INTO public.drug_master
	(brand_name, generic_name, salt_id, salt_composition, manufacturer,
	 hsn_code, gst_rate, drug_schedule, dosage_form, pack_size, mrp,
	 prescription_required, is_active)
SELECT DISTINCT ON (lower(nd.brand_name))
	nd.brand_name, nd.generic_name, sm.id, nd.salt_composition, nd.manufacturer,
	nd.hsn_code, nd.gst_rate::numeric, nd.drug_schedule, nd.dosage_form,
	nd.pack_size, nd.mrp::numeric, nd.prescription_required::boolean, true
FROM new_drugs nd
LEFT JOIN public.salt_master sm ON lower(sm.name) = lower(nd.generic_name)
WHERE NOT EXISTS (
	SELECT 1 FROM public.drug_master d
	WHERE lower(d.brand_name) = lower(nd.brand_name))
ORDER BY lower(nd.brand_name);

-- ---------------------------------------------------------------------------
-- 3c) drug_master — global US/EU brands (reference completeness for imports,
--     partner-network matching and cross-border lookups). MRP NULL.
-- ---------------------------------------------------------------------------
WITH new_drugs (brand_name, generic_name, salt_composition, manufacturer,
                hsn_code, gst_rate, drug_schedule, dosage_form, pack_size,
                mrp, prescription_required) AS (
	VALUES
	('Tylenol Extra Strength', 'Paracetamol', 'Acetaminophen 500mg', 'Kenvue', '3004', 5.00, 'GENERAL', 'Tablet', '100 Tablets', NULL, false),
	('Tylenol PM', 'Paracetamol + Diphenhydramine', 'Acetaminophen 500mg + Diphenhydramine 25mg', 'Kenvue', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Advil Liqui-Gels', 'Ibuprofen', 'Ibuprofen 200mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Capsule', '40 Capsules', NULL, false),
	('Motrin IB', 'Ibuprofen', 'Ibuprofen 200mg', 'Kenvue', '3004', 5.00, 'GENERAL', 'Tablet', '30 Tablets', NULL, false),
	('Aleve', 'Naproxen', 'Naproxen Sodium 220mg', 'Bayer', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Nurofen 200', 'Ibuprofen', 'Ibuprofen 200mg', 'Reckitt', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Excedrin Migraine', 'Aspirin + Paracetamol + Caffeine', 'Aspirin 250mg + Acetaminophen 250mg + Caffeine 65mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Tablet', '24 Tablets', NULL, false),
	('Alka-Seltzer Original', 'Aspirin + Sodium Bicarbonate + Citric Acid', 'Aspirin 325mg + Sodium Bicarbonate 1916mg + Citric Acid 1000mg', 'Bayer', '3004', 5.00, 'GENERAL', 'Effervescent Tablet', '24 Tablets', NULL, false),
	('Tums Ultra', 'Calcium Carbonate', 'Calcium Carbonate 1000mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Chewable Tablet', '72 Tablets', NULL, false),
	('Pepto-Bismol', 'Bismuth Subsalicylate', 'Bismuth Subsalicylate 262mg/15ml', 'P&G Health', '3004', 5.00, 'GENERAL', 'Suspension', '236 ml', NULL, false),
	('Prilosec OTC', 'Omeprazole', 'Omeprazole 20mg', 'P&G Health', '3004', 5.00, 'GENERAL', 'Tablet', '14 Tablets', NULL, false),
	('Zantac 360', 'Famotidine', 'Famotidine 20mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Tablet', '30 Tablets', NULL, false),
	('Pepcid AC', 'Famotidine', 'Famotidine 10mg', 'Kenvue', '3004', 5.00, 'GENERAL', 'Tablet', '30 Tablets', NULL, false),
	('Miralax', 'Polyethylene Glycol', 'Polyethylene Glycol 3350 17g/dose', 'Bayer', '3004', 5.00, 'GENERAL', 'Powder', '238 g', NULL, false),
	('Metamucil', 'Ispaghula Husk', 'Psyllium Husk 3.4g/dose', 'P&G Health', '3004', 5.00, 'GENERAL', 'Powder', '425 g', NULL, false),
	('Benadryl Allergy', 'Diphenhydramine', 'Diphenhydramine 25mg', 'Kenvue', '3004', 5.00, 'GENERAL', 'Capsule', '24 Capsules', NULL, false),
	('Claritin 10', 'Loratadine', 'Loratadine 10mg', 'Bayer', '3004', 5.00, 'GENERAL', 'Tablet', '30 Tablets', NULL, false),
	('Flonase Allergy Relief', 'Fluticasone Propionate', 'Fluticasone Propionate 50mcg/dose', 'Haleon', '3004', 5.00, 'GENERAL', 'Nasal Spray', '120 Doses', NULL, false),
	('Sudafed PE', 'Phenylephrine', 'Phenylephrine 10mg', 'Kenvue', '3004', 5.00, 'GENERAL', 'Tablet', '36 Tablets', NULL, false),
	('Mucinex 600', 'Guaifenesin', 'Guaifenesin 600mg ER', 'Reckitt', '3004', 5.00, 'GENERAL', 'Tablet', '20 Tablets', NULL, false),
	('Robitussin DM', 'Dextromethorphan + Guaifenesin', 'Dextromethorphan 10mg + Guaifenesin 100mg/5ml', 'Haleon', '3004', 5.00, 'GENERAL', 'Syrup', '118 ml', NULL, false),
	('Vicks NyQuil Cold & Flu', 'Paracetamol + Dextromethorphan + Doxylamine', 'Acetaminophen 325mg + Dextromethorphan 10mg + Doxylamine 6.25mg/15ml', 'P&G Health', '3004', 5.00, 'GENERAL', 'Syrup', '236 ml', NULL, false),
	('Vicks DayQuil Cold & Flu', 'Paracetamol + Dextromethorphan + Phenylephrine', 'Acetaminophen 325mg + Dextromethorphan 10mg + Phenylephrine 5mg/15ml', 'P&G Health', '3004', 5.00, 'GENERAL', 'Syrup', '236 ml', NULL, false),
	('Theraflu Severe Cold', 'Paracetamol + Phenylephrine + Diphenhydramine', 'Acetaminophen 650mg + Phenylephrine 10mg + Diphenhydramine 25mg', 'Haleon', '3004', 5.00, 'GENERAL', 'Sachet', '6 Sachets', NULL, false),
	('ZzzQuil', 'Diphenhydramine', 'Diphenhydramine 50mg/30ml', 'P&G Health', '3004', 5.00, 'GENERAL', 'Syrup', '354 ml', NULL, false),
	('Unisom SleepTabs', 'Doxylamine', 'Doxylamine Succinate 25mg', 'Sanofi', '3004', 5.00, 'GENERAL', 'Tablet', '32 Tablets', NULL, false),
	('Neosporin Ointment', 'Neomycin + Polymyxin B + Bacitracin', 'Neomycin 3.5mg + Polymyxin B 5000IU + Bacitracin 400IU/g', 'Kenvue', '3004', 5.00, 'GENERAL', 'Ointment', '28 g', NULL, false),
	('Bengay Ultra Strength', 'Methyl Salicylate + Menthol + Camphor', 'Methyl Salicylate 30% + Menthol 10% + Camphor 4%', 'Kenvue', '3004', 5.00, 'GENERAL', 'Cream', '113 g', NULL, false),
	('Salonpas Pain Relief Patch', 'Methyl Salicylate + Menthol', 'Methyl Salicylate 10% + Menthol 3%', 'Hisamitsu', '3004', 5.00, 'GENERAL', 'Patch', '9 Patches', NULL, false),
	('Nicorette Gum 2mg', 'Nicotine', 'Nicotine Polacrilex 2mg', 'Kenvue', '3004', 5.00, 'GENERAL', 'Chewing Gum', '30 Pieces', NULL, false),
	('Zovirax Cold Sore Cream', 'Acyclovir', 'Aciclovir 5%', 'GSK', '3004', 5.00, 'GENERAL', 'Cream', '2 g', NULL, false),
	('Centrum Adults', 'Multivitamin + Multimineral', 'Multivitamin + Multimineral', 'Haleon', '2106', 18.00, 'GENERAL', 'Tablet', '60 Tablets', NULL, false),
	('Caltrate 600+D3', 'Calcium + Vitamin D3', 'Calcium 600mg + Vitamin D3 800IU', 'Haleon', '2106', 18.00, 'GENERAL', 'Tablet', '60 Tablets', NULL, false),
	('Systane Ultra', 'Polyethylene Glycol + Propylene Glycol', 'Polyethylene Glycol 400 0.4% + Propylene Glycol 0.3%', 'Alcon', '3004', 5.00, 'GENERAL', 'Eye Drops', '10 ml', NULL, false),
	('Pataday Once Daily', 'Olopatadine', 'Olopatadine 0.7%', 'Alcon', '3004', 5.00, 'GENERAL', 'Eye Drops', '2.5 ml', NULL, false),
	('Zocor 20', 'Simvastatin', 'Simvastatin 20mg', 'Organon', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Repatha SureClick', 'Evolocumab', 'Evolocumab 140mg/ml', 'Amgen', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Entresto 50', 'Sacubitril + Valsartan', 'Sacubitril 24mg + Valsartan 26mg', 'Novartis', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Pradaxa 110', 'Dabigatran Etexilate', 'Dabigatran Etexilate 110mg', 'Boehringer', '3004', 5.00, 'H', 'Capsule', '60 Capsules', NULL, true),
	('Brilinta 90', 'Ticagrelor', 'Ticagrelor 90mg', 'AstraZeneca', '3004', 5.00, 'H', 'Tablet', '56 Tablets', NULL, true),
	('Cozaar 50', 'Losartan Potassium', 'Losartan 50mg', 'Organon', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Hyzaar 50/12.5', 'Losartan + Hydrochlorothiazide', 'Losartan 50mg + Hydrochlorothiazide 12.5mg', 'Organon', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Diovan 80', 'Valsartan', 'Valsartan 80mg', 'Novartis', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Atacand 8', 'Candesartan', 'Candesartan Cilexetil 8mg', 'AstraZeneca', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Lopressor 50', 'Metoprolol Tartrate', 'Metoprolol Tartrate 50mg', 'Novartis', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Actos 30', 'Pioglitazone', 'Pioglitazone 30mg', 'Takeda', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Basaglar KwikPen', 'Insulin Glargine', 'Insulin Glargine 100IU/ml', 'Eli Lilly', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Fiasp FlexTouch', 'Insulin Aspart', 'Insulin Aspart 100IU/ml', 'Novo Nordisk', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Abilify 10', 'Aripiprazole', 'Aripiprazole 10mg', 'Otsuka', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Seroquel 100', 'Quetiapine', 'Quetiapine 100mg', 'AstraZeneca', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Zyprexa 10', 'Olanzapine', 'Olanzapine 10mg', 'Eli Lilly', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Risperdal 2', 'Risperidone', 'Risperidone 2mg', 'Janssen', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Lexapro 10', 'Escitalopram', 'Escitalopram 10mg', 'Lundbeck', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Effexor XR 75', 'Venlafaxine HCl', 'Venlafaxine 75mg ER', 'Viatris', '3004', 5.00, 'H', 'Capsule', '30 Capsules', NULL, true),
	('Wellbutrin XL 300', 'Bupropion', 'Bupropion 300mg ER', 'GSK', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Cymbalta 30', 'Duloxetine HCl', 'Duloxetine 30mg', 'Eli Lilly', '3004', 5.00, 'H', 'Capsule', '28 Capsules', NULL, true),
	('Remeron 15', 'Mirtazapine', 'Mirtazapine 15mg', 'Organon', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Ambien 10', 'Zolpidem', 'Zolpidem 10mg', 'Sanofi', '3004', 5.00, 'H1', 'Tablet', '14 Tablets', NULL, true),
	('Valium 5', 'Diazepam', 'Diazepam 5mg', 'Roche', '3004', 5.00, 'H1', 'Tablet', '30 Tablets', NULL, true),
	('Ritalin 10', 'Methylphenidate', 'Methylphenidate 10mg', 'Novartis', '3004', 5.00, 'X', 'Tablet', '30 Tablets', NULL, true),
	('Concerta 18', 'Methylphenidate', 'Methylphenidate 18mg ER', 'Janssen', '3004', 5.00, 'X', 'Tablet', '30 Tablets', NULL, true),
	('Strattera 25', 'Atomoxetine', 'Atomoxetine 25mg', 'Eli Lilly', '3004', 5.00, 'H', 'Capsule', '28 Capsules', NULL, true),
	('Provigil 200', 'Modafinil', 'Modafinil 200mg', 'Teva', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Namenda 10', 'Memantine', 'Memantine 10mg', 'AbbVie', '3004', 5.00, 'H', 'Tablet', '60 Tablets', NULL, true),
	('Aricept 10', 'Donepezil', 'Donepezil 10mg', 'Eisai', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Exelon Patch 4.6', 'Rivastigmine', 'Rivastigmine 4.6mg/24h', 'Novartis', '3004', 5.00, 'H', 'Patch', '30 Patches', NULL, true),
	('Imitrex 50', 'Sumatriptan', 'Sumatriptan 50mg', 'GSK', '3004', 5.00, 'H', 'Tablet', '9 Tablets', NULL, true),
	('Maxalt 10', 'Rizatriptan', 'Rizatriptan 10mg', 'Organon', '3004', 5.00, 'H', 'Tablet', '6 Tablets', NULL, true),
	('Topamax 50', 'Topiramate', 'Topiramate 50mg', 'Janssen', '3004', 5.00, 'H', 'Tablet', '60 Tablets', NULL, true),
	('Depakote 500', 'Divalproex Sodium', 'Divalproex Sodium 500mg', 'AbbVie', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Dilantin 100', 'Phenytoin Sodium', 'Phenytoin Sodium 100mg', 'Viatris', '3004', 5.00, 'H', 'Capsule', '100 Capsules', NULL, true),
	('Vimpat 100', 'Lacosamide', 'Lacosamide 100mg', 'UCB', '3004', 5.00, 'H', 'Tablet', '60 Tablets', NULL, true),
	('Sinemet Plus', 'Levodopa + Carbidopa', 'Levodopa 100mg + Carbidopa 25mg', 'Organon', '3004', 5.00, 'H', 'Tablet', '100 Tablets', NULL, true),
	('Requip 1', 'Ropinirole', 'Ropinirole 1mg', 'GSK', '3004', 5.00, 'H', 'Tablet', '84 Tablets', NULL, true),
	('Mirapex 0.25', 'Pramipexole', 'Pramipexole 0.25mg', 'Boehringer', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Azilect 1', 'Rasagiline', 'Rasagiline 1mg', 'Teva', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Levaquin 500', 'Levofloxacin', 'Levofloxacin 500mg', 'Janssen', '3004', 5.00, 'H1', 'Tablet', '7 Tablets', NULL, true),
	('Bactrim DS', 'Co-trimoxazole', 'Sulfamethoxazole 800mg + Trimethoprim 160mg', 'Roche', '3004', 5.00, 'H', 'Tablet', '20 Tablets', NULL, true),
	('Vibramycin 100', 'Doxycycline', 'Doxycycline 100mg', 'Pfizer', '3004', 5.00, 'H', 'Capsule', '10 Capsules', NULL, true),
	('Xofluza 40', 'Baloxavir Marboxil', 'Baloxavir Marboxil 40mg', 'Roche', '3004', 5.00, 'H', 'Tablet', '1 Tablet', NULL, true),
	('Paxlovid', 'Nirmatrelvir + Ritonavir', 'Nirmatrelvir 150mg + Ritonavir 100mg', 'Pfizer', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Veklury 100 Injection', 'Remdesivir', 'Remdesivir 100mg', 'Gilead', '3004', 5.00, 'H', 'Injection', '1 Vial', NULL, true),
	('Lagevrio 200', 'Molnupiravir', 'Molnupiravir 200mg', 'MSD', '3004', 5.00, 'H', 'Capsule', '40 Capsules', NULL, true),
	('Famvir 250', 'Famciclovir', 'Famciclovir 250mg', 'Novartis', '3004', 5.00, 'H', 'Tablet', '21 Tablets', NULL, true),
	('Zovirax 400', 'Acyclovir', 'Aciclovir 400mg', 'GSK', '3004', 5.00, 'H', 'Tablet', '35 Tablets', NULL, true),
	('Biktarvy', 'Bictegravir + Emtricitabine + Tenofovir Alafenamide', 'Bictegravir 50mg + Emtricitabine 200mg + Tenofovir Alafenamide 25mg', 'Gilead', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Epclusa', 'Sofosbuvir + Velpatasvir', 'Sofosbuvir 400mg + Velpatasvir 100mg', 'Gilead', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Harvoni', 'Ledipasvir + Sofosbuvir', 'Ledipasvir 90mg + Sofosbuvir 400mg', 'Gilead', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Sovaldi 400', 'Sofosbuvir', 'Sofosbuvir 400mg', 'Gilead', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Keytruda 100 Injection', 'Pembrolizumab', 'Pembrolizumab 100mg/4ml', 'MSD', '3004', 5.00, 'H', 'Injection', '1 Vial', NULL, true),
	('Opdivo 100 Injection', 'Nivolumab', 'Nivolumab 100mg/10ml', 'Bristol Myers Squibb', '3004', 5.00, 'H', 'Injection', '1 Vial', NULL, true),
	('Humira 40 Pen', 'Adalimumab', 'Adalimumab 40mg/0.4ml', 'AbbVie', '3004', 5.00, 'H', 'Injection', '2 Pens', NULL, true),
	('Rinvoq 15', 'Upadacitinib', 'Upadacitinib 15mg ER', 'AbbVie', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Xeljanz 5', 'Tofacitinib', 'Tofacitinib 5mg', 'Pfizer', '3004', 5.00, 'H', 'Tablet', '60 Tablets', NULL, true),
	('Otezla 30', 'Apremilast', 'Apremilast 30mg', 'Amgen', '3004', 5.00, 'H', 'Tablet', '60 Tablets', NULL, true),
	('Cosentyx 150 Pen', 'Secukinumab', 'Secukinumab 150mg/ml', 'Novartis', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Dupixent 300 Pen', 'Dupilumab', 'Dupilumab 300mg/2ml', 'Sanofi', '3004', 5.00, 'H', 'Injection', '2 Pens', NULL, true),
	('Xolair 150 Injection', 'Omalizumab', 'Omalizumab 150mg', 'Novartis', '3004', 5.00, 'H', 'Injection', '1 Vial', NULL, true),
	('Stelara 90 Injection', 'Ustekinumab', 'Ustekinumab 90mg/ml', 'Janssen', '3004', 5.00, 'H', 'Injection', '1 Prefilled Syringe', NULL, true),
	('Enbrel 50 Pen', 'Etanercept', 'Etanercept 50mg/ml', 'Pfizer', '3004', 5.00, 'H', 'Injection', '4 Pens', NULL, true),
	('Remicade 100 Injection', 'Infliximab', 'Infliximab 100mg', 'Janssen', '3004', 5.00, 'H', 'Injection', '1 Vial', NULL, true),
	('Glivec 400', 'Imatinib', 'Imatinib 400mg', 'Novartis', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Tagrisso 80', 'Osimertinib', 'Osimertinib 80mg', 'AstraZeneca', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Iressa 250', 'Gefitinib', 'Gefitinib 250mg', 'AstraZeneca', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Tarceva 150', 'Erlotinib', 'Erlotinib 150mg', 'Roche', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Ibrance 125', 'Palbociclib', 'Palbociclib 125mg', 'Pfizer', '3004', 5.00, 'H', 'Capsule', '21 Capsules', NULL, true),
	('Kisqali 200', 'Ribociclib', 'Ribociclib 200mg', 'Novartis', '3004', 5.00, 'H', 'Tablet', '21 Tablets', NULL, true),
	('Revlimid 10', 'Lenalidomide', 'Lenalidomide 10mg', 'Bristol Myers Squibb', '3004', 5.00, 'H', 'Capsule', '21 Capsules', NULL, true),
	('Velcade 3.5 Injection', 'Bortezomib', 'Bortezomib 3.5mg', 'Janssen', '3004', 5.00, 'H', 'Injection', '1 Vial', NULL, true),
	('Imbruvica 140', 'Ibrutinib', 'Ibrutinib 140mg', 'Janssen', '3004', 5.00, 'H', 'Capsule', '90 Capsules', NULL, true),
	('Xtandi 40', 'Enzalutamide', 'Enzalutamide 40mg', 'Astellas', '3004', 5.00, 'H', 'Capsule', '112 Capsules', NULL, true),
	('Zytiga 250', 'Abiraterone Acetate', 'Abiraterone Acetate 250mg', 'Janssen', '3004', 5.00, 'H', 'Tablet', '120 Tablets', NULL, true),
	('Casodex 50', 'Bicalutamide', 'Bicalutamide 50mg', 'AstraZeneca', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Herceptin 440 Injection', 'Trastuzumab', 'Trastuzumab 440mg', 'Roche', '3004', 5.00, 'H', 'Injection', '1 Vial', NULL, true),
	('Avastin 400 Injection', 'Bevacizumab', 'Bevacizumab 400mg/16ml', 'Roche', '3004', 5.00, 'H', 'Injection', '1 Vial', NULL, true),
	('MabThera 500 Injection', 'Rituximab', 'Rituximab 500mg/50ml', 'Roche', '3004', 5.00, 'H', 'Injection', '1 Vial', NULL, true),
	('Advair Diskus 250', 'Salmeterol + Fluticasone', 'Salmeterol 50mcg + Fluticasone Propionate 250mcg', 'GSK', '3004', 5.00, 'H', 'Inhaler', '60 Doses', NULL, true),
	('Trelegy Ellipta', 'Fluticasone Furoate + Umeclidinium + Vilanterol', 'Fluticasone Furoate 100mcg + Umeclidinium 62.5mcg + Vilanterol 25mcg', 'GSK', '3004', 5.00, 'H', 'Inhaler', '30 Doses', NULL, true),
	('Spiriva Respimat', 'Tiotropium Bromide', 'Tiotropium 2.5mcg/dose', 'Boehringer', '3004', 5.00, 'H', 'Inhaler', '60 Doses', NULL, true),
	('Daxas 500mcg', 'Roflumilast', 'Roflumilast 500mcg', 'Takeda', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Myrbetriq 50', 'Mirabegron', 'Mirabegron 50mg ER', 'Astellas', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Vesicare 5', 'Solifenacin', 'Solifenacin 5mg', 'Astellas', '3004', 5.00, 'H', 'Tablet', '30 Tablets', NULL, true),
	('Flomax 0.4', 'Tamsulosin HCl', 'Tamsulosin 0.4mg', 'Boehringer', '3004', 5.00, 'H', 'Capsule', '30 Capsules', NULL, true),
	('Propecia 1', 'Finasteride', 'Finasteride 1mg', 'Organon', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Rogaine 5% Foam', 'Minoxidil', 'Minoxidil 5%', 'Kenvue', '3004', 5.00, 'GENERAL', 'Foam', '60 g', NULL, false),
	('Synthroid 100mcg', 'Levothyroxine', 'Levothyroxine 100mcg', 'AbbVie', '3004', 5.00, 'H', 'Tablet', '90 Tablets', NULL, true),
	('Prolia 60 Injection', 'Denosumab', 'Denosumab 60mg/ml', 'Amgen', '3004', 5.00, 'H', 'Injection', '1 Prefilled Syringe', NULL, true),
	('Fosamax 70', 'Alendronate', 'Alendronate 70mg', 'Organon', '3004', 5.00, 'H', 'Tablet', '4 Tablets', NULL, true),
	('Forteo Pen', 'Teriparatide', 'Teriparatide 20mcg/dose', 'Eli Lilly', '3004', 5.00, 'H', 'Injection', '1 Pen', NULL, true),
	('Premarin 0.625', 'Conjugated Estrogens', 'Conjugated Estrogens 0.625mg', 'Pfizer', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Yaz', 'Drospirenone + Ethinylestradiol', 'Drospirenone 3mg + Ethinylestradiol 0.02mg', 'Bayer', '3004', 5.00, 'H', 'Tablet', '28 Tablets', NULL, true),
	('Yasmin', 'Drospirenone + Ethinylestradiol', 'Drospirenone 3mg + Ethinylestradiol 0.03mg', 'Bayer', '3004', 5.00, 'H', 'Tablet', '21 Tablets', NULL, true),
	('Postinor-2', 'Levonorgestrel', 'Levonorgestrel 0.75mg', 'Gedeon Richter', '3004', 5.00, 'GENERAL', 'Tablet', '2 Tablets', NULL, false),
	('Xalatan Eye Drops', 'Latanoprost', 'Latanoprost 0.005%', 'Viatris', '3004', 5.00, 'H', 'Eye Drops', '2.5 ml', NULL, true),
	('Lumigan Eye Drops', 'Bimatoprost', 'Bimatoprost 0.01%', 'AbbVie', '3004', 5.00, 'H', 'Eye Drops', '3 ml', NULL, true),
	('Alphagan P Eye Drops', 'Brimonidine', 'Brimonidine 0.15%', 'AbbVie', '3004', 5.00, 'H', 'Eye Drops', '5 ml', NULL, true),
	('Azopt Eye Drops', 'Brinzolamide', 'Brinzolamide 1%', 'Alcon', '3004', 5.00, 'H', 'Eye Drops', '5 ml', NULL, true),
	('Combigan Eye Drops', 'Brimonidine + Timolol', 'Brimonidine 0.2% + Timolol 0.5%', 'AbbVie', '3004', 5.00, 'H', 'Eye Drops', '5 ml', NULL, true),
	('Restasis Eye Drops', 'Cyclosporine', 'Cyclosporine 0.05%', 'AbbVie', '3004', 5.00, 'H', 'Eye Drops', '30 Vials', NULL, true),
	('Prevacid 30', 'Lansoprazole', 'Lansoprazole 30mg', 'Takeda', '3004', 5.00, 'H', 'Capsule', '28 Capsules', NULL, true)
)
INSERT INTO public.drug_master
	(brand_name, generic_name, salt_id, salt_composition, manufacturer,
	 hsn_code, gst_rate, drug_schedule, dosage_form, pack_size, mrp,
	 prescription_required, is_active)
SELECT DISTINCT ON (lower(nd.brand_name))
	nd.brand_name, nd.generic_name, sm.id, nd.salt_composition, nd.manufacturer,
	nd.hsn_code, nd.gst_rate::numeric, nd.drug_schedule, nd.dosage_form,
	nd.pack_size, nd.mrp::numeric, nd.prescription_required::boolean, true
FROM new_drugs nd
LEFT JOIN public.salt_master sm ON lower(sm.name) = lower(nd.generic_name)
WHERE NOT EXISTS (
	SELECT 1 FROM public.drug_master d
	WHERE lower(d.brand_name) = lower(nd.brand_name))
ORDER BY lower(nd.brand_name);

-- ---------------------------------------------------------------------------
-- 3d) drug_master — Jan Aushadhi (PMBI) and DavaIndia (Zota Healthcare)
--     generic ranges. Generic-chain SKUs named by molecule; MRPs are the
--     approximate PMBJP / generic-chain price points (deliberately low).
-- ---------------------------------------------------------------------------
WITH new_drugs (brand_name, generic_name, salt_composition, manufacturer,
                hsn_code, gst_rate, drug_schedule, dosage_form, pack_size,
                mrp, prescription_required) AS (
	VALUES
	('Jan Aushadhi Paracetamol 500', 'Paracetamol', 'Paracetamol 500mg', 'PMBI', '3004', 5.00, 'GENERAL', 'Tablet', '10 Tablets', 7.00, false),
	('Jan Aushadhi Paracetamol 650', 'Paracetamol', 'Paracetamol 650mg', 'PMBI', '3004', 5.00, 'GENERAL', 'Tablet', '10 Tablets', 10.00, false),
	('Jan Aushadhi Aceclofenac + Paracetamol', 'Aceclofenac + Paracetamol', 'Aceclofenac 100mg + Paracetamol 325mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 10.00, true),
	('Jan Aushadhi Diclofenac 50', 'Diclofenac Sodium', 'Diclofenac 50mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 8.00, true),
	('Jan Aushadhi Ibuprofen 400', 'Ibuprofen', 'Ibuprofen 400mg', 'PMBI', '3004', 5.00, 'GENERAL', 'Tablet', '10 Tablets', 9.00, false),
	('Jan Aushadhi Aspirin 75', 'Aspirin', 'Aspirin 75mg', 'PMBI', '3004', 5.00, 'GENERAL', 'Tablet', '14 Tablets', 4.00, false),
	('Jan Aushadhi Amoxicillin 500', 'Amoxicillin', 'Amoxicillin 500mg', 'PMBI', '3004', 5.00, 'H', 'Capsule', '10 Capsules', 39.00, true),
	('Jan Aushadhi Amoxicillin + Clavulanic Acid 625', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin 500mg + Clavulanic Acid 125mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 58.00, true),
	('Jan Aushadhi Azithromycin 500', 'Azithromycin', 'Azithromycin 500mg', 'PMBI', '3004', 5.00, 'H1', 'Tablet', '3 Tablets', 32.00, true),
	('Jan Aushadhi Ciprofloxacin 500', 'Ciprofloxacin HCl', 'Ciprofloxacin 500mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 28.00, true),
	('Jan Aushadhi Ofloxacin 200', 'Ofloxacin', 'Ofloxacin 200mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 22.00, true),
	('Jan Aushadhi Cefixime 200', 'Cefixime', 'Cefixime 200mg', 'PMBI', '3004', 5.00, 'H1', 'Tablet', '10 Tablets', 45.00, true),
	('Jan Aushadhi Doxycycline 100', 'Doxycycline', 'Doxycycline 100mg', 'PMBI', '3004', 5.00, 'H', 'Capsule', '10 Capsules', 18.00, true),
	('Jan Aushadhi Metronidazole 400', 'Metronidazole', 'Metronidazole 400mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 9.00, true),
	('Jan Aushadhi Albendazole 400', 'Albendazole', 'Albendazole 400mg', 'PMBI', '3004', 5.00, 'GENERAL', 'Tablet', '1 Tablet', 9.00, false),
	('Jan Aushadhi Fluconazole 150', 'Fluconazole', 'Fluconazole 150mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '1 Tablet', 8.00, true),
	('Jan Aushadhi Pantoprazole 40', 'Pantoprazole', 'Pantoprazole 40mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 18.00, true),
	('Jan Aushadhi Omeprazole 20', 'Omeprazole', 'Omeprazole 20mg', 'PMBI', '3004', 5.00, 'H', 'Capsule', '10 Capsules', 12.00, true),
	('Jan Aushadhi Rabeprazole 20', 'Rabeprazole', 'Rabeprazole 20mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 15.00, true),
	('Jan Aushadhi Pantoprazole + Domperidone', 'Pantoprazole + Domperidone', 'Pantoprazole 40mg + Domperidone 30mg SR', 'PMBI', '3004', 5.00, 'H', 'Capsule', '10 Capsules', 22.00, true),
	('Jan Aushadhi Ondansetron 4', 'Ondansetron', 'Ondansetron 4mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 12.00, true),
	('Jan Aushadhi Metformin 500', 'Metformin', 'Metformin 500mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '20 Tablets', 8.00, true),
	('Jan Aushadhi Metformin SR 1000', 'Metformin', 'Metformin 1000mg SR', 'PMBI', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 15.00, true),
	('Jan Aushadhi Glimepiride 1', 'Glimepiride', 'Glimepiride 1mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 10.00, true),
	('Jan Aushadhi Glimepiride 2', 'Glimepiride', 'Glimepiride 2mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 14.00, true),
	('Jan Aushadhi Glimepiride + Metformin', 'Glimepiride + Metformin', 'Glimepiride 2mg + Metformin 500mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 18.00, true),
	('Jan Aushadhi Gliclazide 80', 'Gliclazide', 'Gliclazide 80mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 16.00, true),
	('Jan Aushadhi Sitagliptin 100', 'Sitagliptin', 'Sitagliptin 100mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 60.00, true),
	('Jan Aushadhi Amlodipine 5', 'Amlodipine', 'Amlodipine 5mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 6.00, true),
	('Jan Aushadhi Telmisartan 40', 'Telmisartan', 'Telmisartan 40mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 14.00, true),
	('Jan Aushadhi Telmisartan + Amlodipine', 'Telmisartan + Amlodipine', 'Telmisartan 40mg + Amlodipine 5mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 22.00, true),
	('Jan Aushadhi Losartan 50', 'Losartan Potassium', 'Losartan 50mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 12.00, true),
	('Jan Aushadhi Atenolol 50', 'Atenolol', 'Atenolol 50mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '14 Tablets', 7.00, true),
	('Jan Aushadhi Metoprolol 50', 'Metoprolol Succinate', 'Metoprolol Succinate 50mg ER', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 15.00, true),
	('Jan Aushadhi Enalapril 5', 'Enalapril Maleate', 'Enalapril 5mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 8.00, true),
	('Jan Aushadhi Ramipril 5', 'Ramipril', 'Ramipril 5mg', 'PMBI', '3004', 5.00, 'H', 'Capsule', '10 Capsules', 18.00, true),
	('Jan Aushadhi Atorvastatin 10', 'Atorvastatin', 'Atorvastatin 10mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 14.00, true),
	('Jan Aushadhi Rosuvastatin 10', 'Rosuvastatin', 'Rosuvastatin 10mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 28.00, true),
	('Jan Aushadhi Clopidogrel 75', 'Clopidogrel', 'Clopidogrel 75mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 16.00, true),
	('Jan Aushadhi Cetirizine 10', 'Cetirizine', 'Cetirizine 10mg', 'PMBI', '3004', 5.00, 'GENERAL', 'Tablet', '10 Tablets', 5.00, false),
	('Jan Aushadhi Levocetirizine 5', 'Levocetirizine', 'Levocetirizine 5mg', 'PMBI', '3004', 5.00, 'GENERAL', 'Tablet', '10 Tablets', 8.00, false),
	('Jan Aushadhi Montelukast + Levocetirizine', 'Montelukast + Levocetirizine', 'Montelukast 10mg + Levocetirizine 5mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 30.00, true),
	('Jan Aushadhi Salbutamol 4', 'Salbutamol', 'Salbutamol 4mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '20 Tablets', 6.00, true),
	('Jan Aushadhi Levothyroxine 50', 'Levothyroxine', 'Levothyroxine 50mcg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '100 Tablets', 12.00, true),
	('Jan Aushadhi Calcium + Vitamin D3', 'Calcium + Vitamin D3', 'Calcium Carbonate 500mg + Vitamin D3 250IU', 'PMBI', '3004', 5.00, 'GENERAL', 'Tablet', '15 Tablets', 22.00, false),
	('Jan Aushadhi B-Complex', 'Vitamin B Complex', 'Vitamin B Complex', 'PMBI', '3004', 5.00, 'GENERAL', 'Tablet', '20 Tablets', 8.00, false),
	('Jan Aushadhi Multivitamin', 'Multivitamin', 'Multivitamin + Multimineral', 'PMBI', '3004', 5.00, 'GENERAL', 'Tablet', '15 Tablets', 15.00, false),
	('Jan Aushadhi Iron + Folic Acid', 'Ferrous Ascorbate + Folic Acid', 'Ferrous Ascorbate 100mg + Folic Acid 1.5mg', 'PMBI', '3004', 5.00, 'GENERAL', 'Tablet', '10 Tablets', 10.00, false),
	('Jan Aushadhi ORS Sachet', 'Oral Rehydration Salts', 'WHO-ORS Formula 21.8g', 'PMBI', '3004', 5.00, 'GENERAL', 'Powder', '1 Sachet', 6.00, false),
	('Jan Aushadhi Sertraline 50', 'Sertraline', 'Sertraline 50mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 22.00, true),
	('Jan Aushadhi Escitalopram 10', 'Escitalopram', 'Escitalopram 10mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 20.00, true),
	('Jan Aushadhi Alprazolam 0.5', 'Alprazolam', 'Alprazolam 0.5mg', 'PMBI', '3004', 5.00, 'H1', 'Tablet', '10 Tablets', 8.00, true),
	('Jan Aushadhi Amitriptyline 25', 'Amitriptyline HCl', 'Amitriptyline 25mg', 'PMBI', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 12.00, true),
	('Jan Aushadhi Pregabalin 75', 'Pregabalin', 'Pregabalin 75mg', 'PMBI', '3004', 5.00, 'H', 'Capsule', '10 Capsules', 35.00, true),
	('Jan Aushadhi Diclofenac Gel', 'Diclofenac Diethylamine', 'Diclofenac Diethylamine 1.16%', 'PMBI', '3004', 5.00, 'GENERAL', 'Gel', '30 g', 35.00, false),
	('Jan Aushadhi Povidone Iodine Ointment', 'Povidone Iodine', 'Povidone Iodine 5%', 'PMBI', '3004', 5.00, 'GENERAL', 'Ointment', '15 g', 28.00, false),
	('Jan Aushadhi Paracetamol Syrup', 'Paracetamol', 'Paracetamol 125mg/5ml', 'PMBI', '3004', 5.00, 'GENERAL', 'Syrup', '60 ml', 18.00, false),
	('Jan Aushadhi Cough Syrup', 'Dextromethorphan + Chlorpheniramine', 'Dextromethorphan 10mg + Chlorpheniramine 2mg/5ml', 'PMBI', '3004', 5.00, 'GENERAL', 'Syrup', '100 ml', 35.00, false),
	('Jan Aushadhi Amoxicillin + Clavulanic Acid Dry Syrup', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin 200mg + Clavulanic Acid 28.5mg/5ml', 'PMBI', '3004', 5.00, 'H', 'Syrup', '30 ml', 42.00, true),
	('DavaIndia Paracetamol 650', 'Paracetamol', 'Paracetamol 650mg', 'Zota Healthcare', '3004', 5.00, 'GENERAL', 'Tablet', '10 Tablets', 12.00, false),
	('DavaIndia Pantoprazole 40', 'Pantoprazole', 'Pantoprazole 40mg', 'Zota Healthcare', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 25.00, true),
	('DavaIndia Rabeprazole + Domperidone', 'Rabeprazole + Domperidone', 'Rabeprazole 20mg + Domperidone 30mg SR', 'Zota Healthcare', '3004', 5.00, 'H', 'Capsule', '10 Capsules', 35.00, true),
	('DavaIndia Amoxicillin + Clavulanic Acid 625', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin 500mg + Clavulanic Acid 125mg', 'Zota Healthcare', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 75.00, true),
	('DavaIndia Azithromycin 500', 'Azithromycin', 'Azithromycin 500mg', 'Zota Healthcare', '3004', 5.00, 'H1', 'Tablet', '3 Tablets', 38.00, true),
	('DavaIndia Cefixime 200', 'Cefixime', 'Cefixime 200mg', 'Zota Healthcare', '3004', 5.00, 'H1', 'Tablet', '10 Tablets', 55.00, true),
	('DavaIndia Montelukast + Levocetirizine', 'Montelukast + Levocetirizine', 'Montelukast 10mg + Levocetirizine 5mg', 'Zota Healthcare', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 38.00, true),
	('DavaIndia Metformin 500', 'Metformin', 'Metformin 500mg', 'Zota Healthcare', '3004', 5.00, 'H', 'Tablet', '20 Tablets', 10.00, true),
	('DavaIndia Glimepiride 2', 'Glimepiride', 'Glimepiride 2mg', 'Zota Healthcare', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 16.00, true),
	('DavaIndia Telmisartan 40', 'Telmisartan', 'Telmisartan 40mg', 'Zota Healthcare', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 18.00, true),
	('DavaIndia Amlodipine 5', 'Amlodipine', 'Amlodipine 5mg', 'Zota Healthcare', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 8.00, true),
	('DavaIndia Atorvastatin 10', 'Atorvastatin', 'Atorvastatin 10mg', 'Zota Healthcare', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 18.00, true),
	('DavaIndia Rosuvastatin 10', 'Rosuvastatin', 'Rosuvastatin 10mg', 'Zota Healthcare', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 32.00, true),
	('DavaIndia Cetirizine 10', 'Cetirizine', 'Cetirizine 10mg', 'Zota Healthcare', '3004', 5.00, 'GENERAL', 'Tablet', '10 Tablets', 6.00, false),
	('DavaIndia Calcium + Vitamin D3', 'Calcium + Vitamin D3', 'Calcium Carbonate 500mg + Vitamin D3 250IU', 'Zota Healthcare', '3004', 5.00, 'GENERAL', 'Tablet', '15 Tablets', 28.00, false),
	('DavaIndia Multivitamin', 'Multivitamin', 'Multivitamin + Multimineral', 'Zota Healthcare', '3004', 5.00, 'GENERAL', 'Tablet', '15 Tablets', 20.00, false),
	('DavaIndia Methylcobalamin 1500', 'Methylcobalamin', 'Methylcobalamin 1500mcg', 'Zota Healthcare', '3004', 5.00, 'GENERAL', 'Tablet', '10 Tablets', 32.00, false),
	('DavaIndia ORS Orange', 'Oral Rehydration Salts', 'WHO-ORS Formula 21.8g', 'Zota Healthcare', '3004', 5.00, 'GENERAL', 'Powder', '1 Sachet', 8.00, false),
	('DavaIndia Cough Syrup', 'Dextromethorphan + Chlorpheniramine', 'Dextromethorphan 10mg + Chlorpheniramine 2mg/5ml', 'Zota Healthcare', '3004', 5.00, 'GENERAL', 'Syrup', '100 ml', 45.00, false),
	('DavaIndia Pain Relief Gel', 'Diclofenac Diethylamine', 'Diclofenac Diethylamine 1.16% + Menthol', 'Zota Healthcare', '3004', 5.00, 'GENERAL', 'Gel', '30 g', 45.00, false),
	('DavaIndia Aceclofenac + Paracetamol', 'Aceclofenac + Paracetamol', 'Aceclofenac 100mg + Paracetamol 325mg', 'Zota Healthcare', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 15.00, true)
)
INSERT INTO public.drug_master
	(brand_name, generic_name, salt_id, salt_composition, manufacturer,
	 hsn_code, gst_rate, drug_schedule, dosage_form, pack_size, mrp,
	 prescription_required, is_active)
SELECT DISTINCT ON (lower(nd.brand_name))
	nd.brand_name, nd.generic_name, sm.id, nd.salt_composition, nd.manufacturer,
	nd.hsn_code, nd.gst_rate::numeric, nd.drug_schedule, nd.dosage_form,
	nd.pack_size, nd.mrp::numeric, nd.prescription_required::boolean, true
FROM new_drugs nd
LEFT JOIN public.salt_master sm ON lower(sm.name) = lower(nd.generic_name)
WHERE NOT EXISTS (
	SELECT 1 FROM public.drug_master d
	WHERE lower(d.brand_name) = lower(nd.brand_name))
ORDER BY lower(nd.brand_name);

-- ---------------------------------------------------------------------------
-- 3e) drug_master — Indian retail additions: 2024-25 launches, prescription
--     brands the trade asks for, ayurvedic/OTC staples, nutrition, devices
--     and consumables (1mg / Apollo / Marg-style catalogue coverage).
--     Approximate INR MRPs.
-- ---------------------------------------------------------------------------
WITH new_drugs (brand_name, generic_name, salt_composition, manufacturer,
                hsn_code, gst_rate, drug_schedule, dosage_form, pack_size,
                mrp, prescription_required) AS (
	VALUES
	('Vymada 50', 'Sacubitril + Valsartan', 'Sacubitril 24mg + Valsartan 26mg', 'Novartis', '3004', 5.00, 'H', 'Tablet', '14 Tablets', 620.00, true),
	('Azmarda 50', 'Sacubitril + Valsartan', 'Sacubitril 24mg + Valsartan 26mg', 'J B Chemicals', '3004', 5.00, 'H', 'Tablet', '14 Tablets', 480.00, true),
	('Oxra 10', 'Dapagliflozin', 'Dapagliflozin 10mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '14 Tablets', 210.00, true),
	('Dynaglipt 20', 'Teneligliptin', 'Teneligliptin 20mg', 'Torrent', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 105.00, true),
	('Ziten 20', 'Teneligliptin', 'Teneligliptin 20mg', 'Glenmark', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 99.00, true),
	('Ondero 5', 'Linagliptin', 'Linagliptin 5mg', 'Lupin', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 235.00, true),
	('Istavel 100', 'Sitagliptin', 'Sitagliptin 100mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 250.00, true),
	('Rozavel 10', 'Rosuvastatin', 'Rosuvastatin 10mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 190.00, true),
	('Tonact 10', 'Atorvastatin', 'Atorvastatin 10mg', 'Lupin', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 125.00, true),
	('Atorva 10', 'Atorvastatin', 'Atorvastatin 10mg', 'Zydus', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 110.00, true),
	('Roseday 10', 'Rosuvastatin', 'Rosuvastatin 10mg', 'USV', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 195.00, true),
	('Razel 10', 'Rosuvastatin', 'Rosuvastatin 10mg', 'Glenmark', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 140.00, true),
	('Deplatt 75', 'Clopidogrel', 'Clopidogrel 75mg', 'Torrent', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 45.00, true),
	('Clavix 75', 'Clopidogrel', 'Clopidogrel 75mg', 'Intas', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 48.00, true),
	('Axcer 90', 'Ticagrelor', 'Ticagrelor 90mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '14 Tablets', 210.00, true),
	('Nexpro 40', 'Esomeprazole', 'Esomeprazole 40mg', 'Torrent', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 145.00, true),
	('Raciper 40', 'Esomeprazole', 'Esomeprazole 40mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 140.00, true),
	('Etoshine 90', 'Etoricoxib', 'Etoricoxib 90mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 105.00, true),
	('Nucoxia 90', 'Etoricoxib', 'Etoricoxib 90mg', 'Zydus', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 110.00, true),
	('Chymoral Forte', 'Trypsin + Chymotrypsin', 'Trypsin-Chymotrypsin 100000 AU', 'Torrent', '3004', 5.00, 'H', 'Tablet', '20 Tablets', 380.00, true),
	('Signoflam', 'Aceclofenac + Paracetamol + Serratiopeptidase', 'Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg', 'Lupin', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 105.00, true),
	('Myoril 4', 'Thiocolchicoside', 'Thiocolchicoside 4mg', 'Sanofi', '3004', 5.00, 'H', 'Capsule', '10 Capsules', 245.00, true),
	('Tizan 2', 'Tizanidine', 'Tizanidine 2mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 85.00, true),
	('Baclof 10', 'Baclofen', 'Baclofen 10mg', 'Intas', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 95.00, true),
	('Moxikind-CV 625', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin 500mg + Clavulanic Acid 125mg', 'Mankind', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 161.00, true),
	('Clavam 625', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin 500mg + Clavulanic Acid 125mg', 'Alkem', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 200.00, true),
	('Mahacef 200', 'Cefixime', 'Cefixime 200mg', 'Mankind', '3004', 5.00, 'H1', 'Tablet', '10 Tablets', 106.00, true),
	('Moxif 400', 'Moxifloxacin', 'Moxifloxacin 400mg', 'Cipla', '3004', 5.00, 'H1', 'Tablet', '5 Tablets', 255.00, true),
	('Linospan 600', 'Linezolid', 'Linezolid 600mg', 'Cipla', '3004', 5.00, 'H1', 'Tablet', '4 Tablets', 302.00, true),
	('Niftas 100', 'Nitrofurantoin', 'Nitrofurantoin 100mg SR', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 158.00, true),
	('Fosirol 3g Sachet', 'Fosfomycin', 'Fosfomycin Trometamol 3g', 'Zuventus', '3004', 5.00, 'H', 'Powder', '1 Sachet', 470.00, true),
	('R-Cinex', 'Rifampicin + Isoniazid', 'Rifampicin 450mg + Isoniazid 300mg', 'Lupin', '3004', 5.00, 'H', 'Capsule', '10 Capsules', 90.00, true),
	('Combutol 800', 'Ethambutol', 'Ethambutol 800mg', 'Lupin', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 65.00, true),
	('Forecox', 'Rifampicin + Isoniazid + Pyrazinamide + Ethambutol', 'Rifampicin 225mg + Isoniazid 150mg + Pyrazinamide 750mg + Ethambutol 400mg', 'Macleods', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 120.00, true),
	('Rifagut 400', 'Rifaximin', 'Rifaximin 400mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 315.00, true),
	('Ganaton 50', 'Itopride', 'Itopride 50mg', 'Abbott', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 175.00, true),
	('Udiliv 300', 'Ursodeoxycholic Acid', 'Ursodeoxycholic Acid 300mg', 'Abbott', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 550.00, true),
	('Ursocol 300', 'Ursodeoxycholic Acid', 'Ursodeoxycholic Acid 300mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 320.00, true),
	('Hepamerz', 'L-Ornithine L-Aspartate', 'L-Ornithine L-Aspartate 5g/10ml', 'Win Medicare', '3004', 5.00, 'GENERAL', 'Sachet', '6 Sachets', 390.00, false),
	('Sporlac-DS', 'Lactobacillus', 'Lactobacillus Sporogenes 150 Million Spores', 'Sanzyme', '3004', 5.00, 'GENERAL', 'Tablet', '15 Tablets', 105.00, false),
	('Econorm 250 Sachet', 'Saccharomyces Boulardii', 'Saccharomyces Boulardii 250mg', 'Dr Reddy', '3004', 5.00, 'GENERAL', 'Powder', '1 Sachet', 48.00, false),
	('Darolac Sachet', 'Lactobacillus', 'Probiotic Blend 1.25 Billion CFU', 'Aristo', '3004', 5.00, 'GENERAL', 'Powder', '1 Sachet', 25.00, false),
	('Vibact DS', 'Bacillus Clausii', 'Bacillus Clausii + Probiotic Blend', 'USV', '3004', 5.00, 'GENERAL', 'Capsule', '10 Capsules', 130.00, false),
	('Softovac SF', 'Ispaghula Husk', 'Ispaghula + Liquorice + Senna (Sugar Free)', 'Lupin', '3004', 5.00, 'GENERAL', 'Powder', '250 g', 335.00, false),
	('Daflon 500', 'Diosmin + Hesperidin', 'Diosmin 450mg + Hesperidin 50mg', 'Servier', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 385.00, true),
	('Pilex Tablets', NULL, 'Ayurvedic proprietary (haemorrhoid care)', 'Himalaya Wellness', '3004', 5.00, 'GENERAL', 'Tablet', '60 Tablets', 190.00, false),
	('Misoprost 200', 'Misoprostol', 'Misoprostol 200mcg', 'Cipla', '3004', 5.00, 'H', 'Tablet', '4 Tablets', 137.00, true),
	('Doxinate', 'Doxylamine + Pyridoxine', 'Doxylamine 10mg + Pyridoxine 10mg', 'Various', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 140.00, true),
	('Ebast 10', 'Ebastine', 'Ebastine 10mg', 'Micro Labs', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 125.00, true),
	('Ketasma 1', 'Ketotifen', 'Ketotifen 1mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 32.00, true),
	('Nasivion Classic Nasal Spray', 'Oxymetazoline', 'Oxymetazoline 0.05%', 'P&G Health', '3004', 5.00, 'GENERAL', 'Nasal Spray', '10 ml', 105.00, false),
	('Duonase Nasal Spray', 'Azelastine + Fluticasone', 'Azelastine 140mcg + Fluticasone Propionate 50mcg/dose', 'Cipla', '3004', 5.00, 'H', 'Nasal Spray', '70 Doses', 400.00, true),
	('Tugain 5%', 'Minoxidil', 'Minoxidil 5%', 'Cipla', '3004', 5.00, 'GENERAL', 'Solution', '60 ml', 810.00, false),
	('Mintop 5%', 'Minoxidil', 'Minoxidil 5%', 'Dr Reddy', '3004', 5.00, 'GENERAL', 'Solution', '60 ml', 780.00, false),
	('Follihair', 'Biotin', 'Biotin + Amino Acids + Multimineral', 'Abbott', '2106', 18.00, 'GENERAL', 'Tablet', '10 Tablets', 165.00, false),
	('Isotroin 20', 'Isotretinoin', 'Isotretinoin 20mg', 'Cipla', '3004', 5.00, 'H', 'Capsule', '10 Capsules', 320.00, true),
	('Retino-A 0.05%', 'Tretinoin', 'Tretinoin 0.05%', 'Janssen', '3004', 5.00, 'H', 'Cream', '20 g', 185.00, true),
	('Adaferin 0.1%', 'Adapalene', 'Adapalene 0.1%', 'Galderma', '3004', 5.00, 'H', 'Gel', '15 g', 280.00, true),
	('Epiduo Gel', 'Adapalene + Benzoyl Peroxide', 'Adapalene 0.1% + Benzoyl Peroxide 2.5%', 'Galderma', '3004', 5.00, 'H', 'Gel', '15 g', 570.00, true),
	('Benzac AC 2.5%', 'Benzoyl Peroxide', 'Benzoyl Peroxide 2.5%', 'Galderma', '3004', 5.00, 'GENERAL', 'Gel', '20 g', 195.00, false),
	('Acnestar Gel', 'Clindamycin + Nicotinamide', 'Clindamycin 1% + Nicotinamide 4%', 'Mankind', '3004', 5.00, 'H', 'Gel', '22 g', 145.00, true),
	('Melalite Forte', 'Hydroquinone', 'Hydroquinone 4%', 'Abbott', '3004', 5.00, 'H', 'Cream', '30 g', 160.00, true),
	('Kojivit Gel', 'Kojic Acid', 'Kojic Acid + Arbutin + Vitamin C', 'Micro Labs', '3004', 5.00, 'GENERAL', 'Gel', '30 g', 425.00, false),
	('Demelan Cream', 'Glycolic Acid + Arbutin + Kojic Acid', 'Glycolic Acid 10% + Arbutin 5% + Kojic Acid 2%', 'Glenmark', '3004', 5.00, 'GENERAL', 'Cream', '20 g', 385.00, false),
	('Venusia Max Lotion', NULL, 'Emollient moisturiser', 'Dr Reddy', '3304', 18.00, 'GENERAL', 'Lotion', '300 ml', 690.00, false),
	('Lulifin Cream', 'Luliconazole', 'Luliconazole 1%', 'Sun Pharma', '3004', 5.00, 'H', 'Cream', '30 g', 385.00, true),
	('Itch Guard Plus', 'Clotrimazole', 'Clotrimazole 1% + Menthol', 'Reckitt', '3004', 5.00, 'GENERAL', 'Cream', '20 g', 105.00, false),
	('Ring Guard', 'Miconazole', 'Miconazole 2% + Neomycin', 'Reckitt', '3004', 5.00, 'GENERAL', 'Cream', '20 g', 98.00, false),
	('Boroline', NULL, 'Boric Acid + Zinc Oxide + Anhydrous Lanolin', 'G.D. Pharmaceuticals', '3004', 5.00, 'GENERAL', 'Cream', '20 g', 62.00, false),
	('Boroplus Antiseptic Cream', NULL, 'Ayurvedic antiseptic cream', 'Emami', '3004', 5.00, 'GENERAL', 'Cream', '40 g', 75.00, false),
	('Genteal Eye Drops', 'Carboxymethylcellulose', 'Hypromellose 0.3%', 'Alcon', '3004', 5.00, 'GENERAL', 'Eye Drops', '10 ml', 180.00, false),
	('Pred Forte Eye Drops', 'Prednisolone', 'Prednisolone Acetate 1%', 'Allergan', '3004', 5.00, 'H', 'Eye Drops', '5 ml', 235.00, true),
	('Shelcal-XT', 'Calcium + Vitamin D3', 'Calcium Citrate Malate 500mg + Vitamin D3 400IU + Minerals', 'Torrent', '3004', 5.00, 'GENERAL', 'Tablet', '15 Tablets', 190.00, false),
	('Uprise-D3 60K', 'Cholecalciferol', 'Cholecalciferol 60000IU', 'Alkem', '3004', 5.00, 'H', 'Capsule', '4 Capsules', 130.00, true),
	('D-Rise 60K', 'Cholecalciferol', 'Cholecalciferol 60000IU', 'USV', '3004', 5.00, 'H', 'Sachet', '4 Sachets', 125.00, true),
	('Calcirol 60K Sachet', 'Cholecalciferol', 'Cholecalciferol 60000IU Granules', 'Cadila', '3004', 5.00, 'H', 'Powder', '1 Sachet', 33.00, true),
	('Arachitol 6L Injection', 'Cholecalciferol', 'Cholecalciferol 600000IU', 'Abbott', '3004', 5.00, 'H', 'Injection', '1 Ampoule', 95.00, true),
	('Nurokind Plus', 'Methylcobalamin', 'Methylcobalamin 1500mcg + ALA + Folic Acid + Pyridoxine', 'Mankind', '3004', 5.00, 'GENERAL', 'Capsule', '10 Capsules', 110.00, false),
	('Methycobal 500', 'Methylcobalamin', 'Methylcobalamin 500mcg', 'Wockhardt', '3004', 5.00, 'GENERAL', 'Tablet', '10 Tablets', 135.00, false),
	('Optineuron Forte', 'Vitamin B Complex', 'B1 + B6 + Methylcobalamin + Folic Acid', 'Lupin', '3004', 5.00, 'GENERAL', 'Tablet', '10 Tablets', 42.00, false),
	('Revital H', 'Multivitamin + Ginseng + Minerals', 'Multivitamin + Ginseng + Zinc', 'Sun Pharma', '2106', 18.00, 'GENERAL', 'Capsule', '30 Capsules', 350.00, false),
	('Ensure Vanilla 400g', NULL, 'Complete balanced nutrition powder', 'Abbott', '2106', 18.00, 'GENERAL', 'Powder', '400 g', 720.00, false),
	('Pediasure Vanilla 400g', NULL, 'Nutrition supplement for children 2+', 'Abbott', '2106', 18.00, 'GENERAL', 'Powder', '400 g', 655.00, false),
	('Protinex Original 400g', NULL, 'Protein supplement powder', 'Danone', '2106', 18.00, 'GENERAL', 'Powder', '400 g', 640.00, false),
	('Threptin Diskettes 275g', NULL, 'High-protein diskettes', 'Raptakos', '2106', 18.00, 'GENERAL', 'Biscuit', '275 g', 465.00, false),
	('Horlicks Classic Malt 500g', NULL, 'Malted health food drink', 'Haleon', '1901', 5.00, 'GENERAL', 'Powder', '500 g', 275.00, false),
	('Boost Chocolate 500g', NULL, 'Malt-based energy drink', 'Haleon', '1901', 5.00, 'GENERAL', 'Powder', '500 g', 270.00, false),
	('Complan Royale Chocolate 500g', NULL, 'Milk-based health drink', 'Zydus Wellness', '1901', 5.00, 'GENERAL', 'Powder', '500 g', 355.00, false),
	('Glucon-D Original 500g', NULL, 'Glucose-based energy drink', 'Zydus Wellness', '1702', 5.00, 'GENERAL', 'Powder', '500 g', 130.00, false),
	('Enerzal Orange 500g', NULL, 'Electrolyte energy drink powder', 'FDC', '2106', 18.00, 'GENERAL', 'Powder', '500 g', 265.00, false),
	('Zevit Capsules', 'Vitamin B Complex + Zinc', 'B-Complex + Vitamin C + Zinc', 'Haleon', '3004', 5.00, 'GENERAL', 'Capsule', '20 Capsules', 65.00, false),
	('Susten 200', 'Progesterone', 'Micronized Progesterone 200mg', 'Sun Pharma', '3004', 5.00, 'H', 'Capsule', '10 Capsules', 340.00, true),
	('Regestrone 5', 'Norethisterone', 'Norethisterone 5mg', 'Torrent', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 55.00, true),
	('Deviry 10', 'Medroxyprogesterone', 'Medroxyprogesterone 10mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 85.00, true),
	('Krimson 35', 'Ethinylestradiol + Cyproterone', 'Cyproterone 2mg + Ethinylestradiol 0.035mg', 'Walter Bushnell', '3004', 5.00, 'H', 'Tablet', '21 Tablets', 415.00, true),
	('Diane-35', 'Ethinylestradiol + Cyproterone', 'Cyproterone 2mg + Ethinylestradiol 0.035mg', 'Bayer', '3004', 5.00, 'H', 'Tablet', '21 Tablets', 465.00, true),
	('Novelon', 'Desogestrel + Ethinylestradiol', 'Desogestrel 0.15mg + Ethinylestradiol 0.03mg', 'Organon', '3004', 5.00, 'H', 'Tablet', '21 Tablets', 345.00, true),
	('Femilon', 'Desogestrel + Ethinylestradiol', 'Desogestrel 0.15mg + Ethinylestradiol 0.02mg', 'Organon', '3004', 5.00, 'H', 'Tablet', '21 Tablets', 385.00, true),
	('Siphene 50', 'Clomiphene Citrate', 'Clomiphene Citrate 50mg', 'Serum Institute of India', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 92.00, true),
	('Letroz 2.5', 'Letrozole', 'Letrozole 2.5mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '5 Tablets', 215.00, true),
	('Prega News', NULL, 'hCG Pregnancy Test Kit', 'Mankind', '3822', 5.00, 'GENERAL', 'Test Kit', '1 Kit', 60.00, false),
	('Urimax 0.4', 'Tamsulosin HCl', 'Tamsulosin 0.4mg', 'Cipla', '3004', 5.00, 'H', 'Capsule', '15 Capsules', 250.00, true),
	('Veltam 0.4', 'Tamsulosin HCl', 'Tamsulosin 0.4mg', 'Intas', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 240.00, true),
	('Dutas 0.5', 'Dutasteride', 'Dutasteride 0.5mg', 'Dr Reddy', '3004', 5.00, 'H', 'Capsule', '15 Capsules', 320.00, true),
	('Finpecia 1', 'Finasteride', 'Finasteride 1mg', 'Cipla', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 265.00, true),
	('Suhagra 100', 'Sildenafil Citrate', 'Sildenafil 100mg', 'Cipla', '3004', 5.00, 'H', 'Tablet', '4 Tablets', 164.00, true),
	('Caverta 100', 'Sildenafil Citrate', 'Sildenafil 100mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '4 Tablets', 185.00, true),
	('Megalis 20', 'Tadalafil', 'Tadalafil 20mg', 'Macleods', '3004', 5.00, 'H', 'Tablet', '4 Tablets', 255.00, true),
	('Tadacip 20', 'Tadalafil', 'Tadalafil 20mg', 'Cipla', '3004', 5.00, 'H', 'Tablet', '4 Tablets', 236.00, true),
	('Febutaz 40', 'Febuxostat', 'Febuxostat 40mg', 'Sun Pharma', '3004', 5.00, 'H', 'Tablet', '15 Tablets', 265.00, true),
	('Omnacortil 10', 'Prednisolone', 'Prednisolone 10mg', 'Macleods', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 32.00, true),
	('Defcort 6', 'Deflazacort', 'Deflazacort 6mg', 'Macleods', '3004', 5.00, 'H', 'Tablet', '10 Tablets', 115.00, true),
	('Liv.52', NULL, 'Ayurvedic hepatoprotective', 'Himalaya Wellness', '3004', 5.00, 'GENERAL', 'Tablet', '100 Tablets', 165.00, false),
	('Liv.52 DS', NULL, 'Ayurvedic hepatoprotective (double strength)', 'Himalaya Wellness', '3004', 5.00, 'GENERAL', 'Tablet', '60 Tablets', 175.00, false),
	('Cystone', NULL, 'Ayurvedic urinary care', 'Himalaya Wellness', '3004', 5.00, 'GENERAL', 'Tablet', '60 Tablets', 160.00, false),
	('Septilin', NULL, 'Ayurvedic immunity support', 'Himalaya Wellness', '3004', 5.00, 'GENERAL', 'Tablet', '60 Tablets', 170.00, false),
	('Rumalaya Forte', NULL, 'Ayurvedic joint care', 'Himalaya Wellness', '3004', 5.00, 'GENERAL', 'Tablet', '60 Tablets', 185.00, false),
	('Gasex', NULL, 'Ayurvedic digestive', 'Himalaya Wellness', '3004', 5.00, 'GENERAL', 'Tablet', '100 Tablets', 110.00, false),
	('Bonnisan Liquid', NULL, 'Ayurvedic paediatric digestive tonic', 'Himalaya Wellness', '3004', 5.00, 'GENERAL', 'Syrup', '120 ml', 120.00, false),
	('Himalaya Ashvagandha', NULL, 'Ashvagandha (Withania somnifera) 250mg', 'Himalaya Wellness', '3004', 5.00, 'GENERAL', 'Tablet', '60 Tablets', 265.00, false),
	('Dabur Chyawanprash 500g', NULL, 'Ayurvedic rasayana (amla base)', 'Dabur', '3004', 5.00, 'GENERAL', 'Paste', '500 g', 205.00, false),
	('Pudin Hara Pearls', NULL, 'Pudina Satva (mint extract)', 'Dabur', '3004', 5.00, 'GENERAL', 'Capsule', '10 Capsules', 25.00, false),
	('Hajmola Regular', NULL, 'Ayurvedic digestive tablets', 'Dabur', '3004', 5.00, 'GENERAL', 'Tablet', '120 Tablets', 60.00, false),
	('Dabur Honitus Syrup', NULL, 'Ayurvedic cough remedy (honey-tulsi)', 'Dabur', '3004', 5.00, 'GENERAL', 'Syrup', '100 ml', 105.00, false),
	('Dabur Shilajit Gold', NULL, 'Shilajit + Gold + Kesar capsules', 'Dabur', '3004', 5.00, 'GENERAL', 'Capsule', '20 Capsules', 495.00, false),
	('Baidyanath Triphala Churna', NULL, 'Triphala (Amla + Haritaki + Bibhitaki)', 'Baidyanath', '3004', 5.00, 'GENERAL', 'Powder', '100 g', 95.00, false),
	('Safi Syrup', NULL, 'Unani blood purifier', 'Hamdard', '3004', 5.00, 'GENERAL', 'Syrup', '200 ml', 125.00, false),
	('Joshina', NULL, 'Unani herbal cough remedy', 'Hamdard', '3004', 5.00, 'GENERAL', 'Syrup', '100 ml', 90.00, false),
	('Zandu Balm', NULL, 'Ayurvedic pain balm', 'Emami', '3004', 5.00, 'GENERAL', 'Balm', '25 ml', 105.00, false),
	('Amrutanjan Strong Balm', NULL, 'Ayurvedic pain balm (extra strong)', 'Amrutanjan', '3004', 5.00, 'GENERAL', 'Balm', '30 ml', 120.00, false),
	('Omron HEM-7120 BP Monitor', NULL, 'Automatic upper-arm blood pressure monitor', 'Omron Healthcare', '9018', 5.00, 'GENERAL', 'Device', '1 Unit', 2090.00, false),
	('Dr Morepen BP-02 BP Monitor', NULL, 'Automatic upper-arm blood pressure monitor', 'Morepen', '9018', 5.00, 'GENERAL', 'Device', '1 Unit', 1490.00, false),
	('Accu-Chek Active Strips 50', NULL, 'Blood glucose test strips', 'Roche', '3822', 5.00, 'GENERAL', 'Test Strips', '50 Strips', 1120.00, false),
	('Dr Morepen GlucoOne Strips 50', NULL, 'Blood glucose test strips (BG-03)', 'Morepen', '3822', 5.00, 'GENERAL', 'Test Strips', '50 Strips', 899.00, false),
	('Omron NE-C101 Nebulizer', NULL, 'Compressor nebulizer', 'Omron Healthcare', '9019', 5.00, 'GENERAL', 'Device', '1 Unit', 2450.00, false),
	('Dr Morepen Digital Thermometer', NULL, 'Digital clinical thermometer (MT-101)', 'Morepen', '9025', 18.00, 'GENERAL', 'Device', '1 Unit', 199.00, false),
	('Dispovan Syringe 5ml', NULL, 'Single-use sterile syringe with needle', 'HMD', '9018', 5.00, 'GENERAL', 'Syringe', '1 Unit', 8.00, false),
	('Band-Aid Washproof', NULL, 'Adhesive first-aid dressing', 'Kenvue', '3005', 5.00, 'GENERAL', 'Dressing', '20 Strips', 95.00, false),
	('Dettol Antiseptic Liquid 550ml', 'Chloroxylenol', 'Chloroxylenol 4.8%', 'Reckitt', '3808', 18.00, 'GENERAL', 'Liquid', '550 ml', 245.00, false),
	('Savlon Antiseptic Liquid 500ml', 'Chlorhexidine + Cetrimide', 'Chlorhexidine 0.3% + Cetrimide 3%', 'ITC', '3808', 18.00, 'GENERAL', 'Liquid', '500 ml', 220.00, false),
	('Durex Air Condoms', NULL, 'Ultra-thin latex condoms', 'Reckitt', '4014', 0.00, 'GENERAL', 'Condom', '10 Pieces', 300.00, false),
	('Manforce Wild Condoms', NULL, 'Dotted latex condoms', 'Mankind', '4014', 0.00, 'GENERAL', 'Condom', '10 Pieces', 66.00, false),
	('Lactogen 1 400g', NULL, 'Infant formula (0-6 months)', 'Nestle', '1901', 5.00, 'GENERAL', 'Powder', '400 g', 455.00, false),
	('Nan Pro 1 400g', NULL, 'Infant formula with probiotic (0-6 months)', 'Nestle', '1901', 5.00, 'GENERAL', 'Powder', '400 g', 855.00, false),
	('Cerelac Wheat 300g', NULL, 'Infant cereal (6+ months)', 'Nestle', '1901', 5.00, 'GENERAL', 'Powder', '300 g', 245.00, false),
	('Similac Advance 1 400g', NULL, 'Infant formula (0-6 months)', 'Abbott', '1901', 5.00, 'GENERAL', 'Powder', '400 g', 610.00, false),
	('Dexolac 1 400g', NULL, 'Infant formula (0-6 months)', 'Danone', '1901', 5.00, 'GENERAL', 'Powder', '400 g', 425.00, false),
	('Woodwards Gripe Water', NULL, 'Dill oil + Sarjikakshara gripe water', 'TTK Healthcare', '3004', 5.00, 'GENERAL', 'Liquid', '130 ml', 92.00, false)
)
INSERT INTO public.drug_master
	(brand_name, generic_name, salt_id, salt_composition, manufacturer,
	 hsn_code, gst_rate, drug_schedule, dosage_form, pack_size, mrp,
	 prescription_required, is_active)
SELECT DISTINCT ON (lower(nd.brand_name))
	nd.brand_name, nd.generic_name, sm.id, nd.salt_composition, nd.manufacturer,
	nd.hsn_code, nd.gst_rate::numeric, nd.drug_schedule, nd.dosage_form,
	nd.pack_size, nd.mrp::numeric, nd.prescription_required::boolean, true
FROM new_drugs nd
LEFT JOIN public.salt_master sm ON lower(sm.name) = lower(nd.generic_name)
WHERE NOT EXISTS (
	SELECT 1 FROM public.drug_master d
	WHERE lower(d.brand_name) = lower(nd.brand_name))
ORDER BY lower(nd.brand_name);
