-- V36: Seed day-01 unique drug master candidates from reviewed local CSV
-- Source artifact: katixo_drug_master_day01_200.csv
-- Adds only rows not already present in V28/V34 by brand_name + salt_composition + manufacturer.
-- Candidate reference data only. Verify manufacturer, schedule, GST, pack, and MRP before production use.

INSERT INTO salt_master(name, category) VALUES
  ('Paracetamol', 'Analgesic/Antipyretic'),
  ('Ibuprofen', 'NSAID'),
  ('Diclofenac Sodium', 'NSAID'),
  ('Aceclofenac', 'NSAID'),
  ('Aceclofenac + Paracetamol', 'NSAID/Analgesic'),
  ('Aceclofenac + Paracetamol + Serratiopeptidase', 'NSAID/Analgesic'),
  ('Nimesulide', 'NSAID'),
  ('Dicyclomine + Mefenamic Acid', 'Antispasmodic/NSAID'),
  ('Mefenamic Acid', 'NSAID'),
  ('Drotaverine', 'Antispasmodic'),
  ('Drotaverine + Mefenamic Acid', 'Antispasmodic/NSAID'),
  ('Ketorolac', 'NSAID'),
  ('Ibuprofen + Paracetamol', 'NSAID/Analgesic'),
  ('Diclofenac Diethylamine', 'Topical Analgesic'),
  ('Methyl Salicylate + Menthol + Eucalyptus Oil', 'Topical Analgesic'),
  ('Azithromycin', 'Antibiotic'),
  ('Amoxicillin + Clavulanic Acid', 'Antibiotic'),
  ('Amoxicillin', 'Antibiotic'),
  ('Cefixime', 'Antibiotic'),
  ('Cefuroxime Axetil', 'Antibiotic'),
  ('Cefpodoxime Proxetil', 'Antibiotic'),
  ('Levofloxacin', 'Antibiotic'),
  ('Ofloxacin', 'Antibiotic'),
  ('Norfloxacin', 'Antibiotic'),
  ('Norfloxacin + Tinidazole', 'Antibiotic/Antiprotozoal'),
  ('Metronidazole', 'Antiprotozoal/Antibiotic'),
  ('Doxycycline', 'Antibiotic'),
  ('Linezolid', 'Antibiotic'),
  ('Pantoprazole', 'PPI/Antacid'),
  ('Pantoprazole + Domperidone', 'PPI/Prokinetic'),
  ('Rabeprazole', 'PPI/Antacid'),
  ('Rabeprazole + Domperidone', 'PPI/Prokinetic'),
  ('Omeprazole', 'PPI/Antacid'),
  ('Omeprazole + Domperidone', 'PPI/Prokinetic'),
  ('Esomeprazole', 'PPI/Antacid'),
  ('Esomeprazole + Domperidone', 'PPI/Prokinetic'),
  ('Itopride', 'Prokinetic'),
  ('Domperidone', 'Antiemetic/Prokinetic'),
  ('Ondansetron', 'Antiemetic'),
  ('Loperamide', 'Antidiarrheal'),
  ('Bisacodyl', 'Laxative'),
  ('Liquid Paraffin + Milk of Magnesia + Sodium Picosulfate', 'Laxative'),
  ('Lactulose', 'Laxative'),
  ('Aluminium Hydroxide + Magnesium Hydroxide + Simethicone', 'Antacid'),
  ('Cetirizine', 'Antihistamine'),
  ('Levocetirizine', 'Antihistamine'),
  ('Fexofenadine', 'Antihistamine'),
  ('Montelukast + Levocetirizine', 'Anti-allergic/Respiratory'),
  ('Pheniramine Maleate', 'Antihistamine'),
  ('Diphenhydramine + Ammonium Chloride + Sodium Citrate', 'Cough/Cold'),
  ('Ambroxol + Levosalbutamol + Guaifenesin', 'Cough/Respiratory'),
  ('Phenylephrine + Chlorpheniramine + Dextromethorphan', 'Cough/Cold'),
  ('Chlorpheniramine + Dextromethorphan', 'Cough/Cold'),
  ('Dextromethorphan + Chlorpheniramine + Phenylephrine', 'Cough/Cold'),
  ('Paracetamol + Phenylephrine + Chlorpheniramine', 'Cough/Cold'),
  ('Paracetamol + Phenylephrine + Caffeine + Chlorpheniramine', 'Cough/Cold'),
  ('Dextromethorphan + Phenylephrine + Chlorpheniramine', 'Cough/Cold'),
  ('Dextromethorphan + Chlorpheniramine + Ammonium Chloride + Guaifenesin', 'Cough/Cold'),
  ('Metformin', 'Antidiabetic'),
  ('Glimepiride + Metformin', 'Antidiabetic'),
  ('Glimepiride', 'Antidiabetic'),
  ('Vildagliptin', 'Antidiabetic'),
  ('Vildagliptin + Metformin', 'Antidiabetic'),
  ('Sitagliptin', 'Antidiabetic'),
  ('Sitagliptin + Metformin', 'Antidiabetic'),
  ('Teneligliptin', 'Antidiabetic'),
  ('Empagliflozin', 'Antidiabetic'),
  ('Linagliptin', 'Antidiabetic'),
  ('Insulin Glargine', 'Insulin'),
  ('Telmisartan', 'Antihypertensive'),
  ('Telmisartan + Amlodipine', 'Antihypertensive'),
  ('Amlodipine + Atenolol', 'Antihypertensive'),
  ('Amlodipine', 'Antihypertensive'),
  ('Bisoprolol', 'Antihypertensive'),
  ('Metoprolol Succinate', 'Antihypertensive'),
  ('Metoprolol Tartrate', 'Antihypertensive'),
  ('Losartan', 'Antihypertensive'),
  ('Aspirin', 'Antiplatelet'),
  ('Aspirin + Atorvastatin', 'Cardiovascular'),
  ('Clopidogrel', 'Antiplatelet'),
  ('Atorvastatin', 'Lipid-lowering'),
  ('Rosuvastatin', 'Lipid-lowering'),
  ('Spironolactone', 'Diuretic'),
  ('Olmesartan', 'Antihypertensive'),
  ('Calcium + Vitamin D3', 'Calcium/Vitamin'),
  ('Calcium + Vitamin D3 + Minerals', 'Calcium/Vitamin'),
  ('Vitamin B Complex', 'Vitamin'),
  ('Vitamin B Complex + Zinc', 'Vitamin'),
  ('Multivitamin + Multimineral', 'Vitamin'),
  ('Multivitamin + Zinc', 'Vitamin'),
  ('Vitamin C', 'Vitamin'),
  ('Cholecalciferol', 'Vitamin D'),
  ('Folic Acid', 'Vitamin'),
  ('Ferrous Ascorbate + Folic Acid', 'Iron/Folate'),
  ('Ferrous Fumarate + Folic Acid + Vitamin B12', 'Iron/Folate'),
  ('Iron + Folic Acid + Vitamin B12', 'Iron/Folate'),
  ('Multivitamin + Ginseng + Minerals', 'Supplement'),
  ('Levothyroxine', 'Thyroid'),
  ('Phenytoin', 'Antiepileptic'),
  ('Gabapentin', 'Neuropathic pain'),
  ('Pregabalin', 'Neuropathic pain'),
  ('Escitalopram', 'Antidepressant'),
  ('Sertraline', 'Antidepressant'),
  ('Fluoxetine', 'Antidepressant'),
  ('Alprazolam', 'Anxiolytic'),
  ('Clonazepam', 'Anxiolytic/Antiepileptic'),
  ('Zolpidem', 'Sedative'),
  ('Cabergoline', 'Hormonal'),
  ('Norethisterone', 'Hormonal'),
  ('Salbutamol', 'Respiratory'),
  ('Etofylline + Theophylline', 'Respiratory'),
  ('Budesonide', 'Respiratory'),
  ('Budesonide + Formoterol', 'Respiratory'),
  ('Levosalbutamol + Ipratropium', 'Respiratory'),
  ('Mupirocin', 'Topical Antibiotic'),
  ('Framycetin', 'Topical Antibiotic'),
  ('Povidone Iodine', 'Antiseptic'),
  ('Clotrimazole', 'Antifungal'),
  ('Clotrimazole + Beclomethasone', 'Antifungal/Steroid'),
  ('Luliconazole', 'Antifungal'),
  ('Terbinafine', 'Antifungal')
ON CONFLICT (name) DO NOTHING;

WITH seed(brand_name, generic_name, salt_name, salt_composition, manufacturer, hsn_code, gst_rate, drug_schedule, dosage_form, pack_size, mrp, prescription_required) AS (
  VALUES
  ('Crocin 500', 'Paracetamol', 'Paracetamol', 'Paracetamol 500mg', 'GSK', '3004', 12, 'GENERAL', 'Tablet', '15 tablets', NULL, FALSE),
  ('Calpol 500', 'Paracetamol', 'Paracetamol', 'Paracetamol 500mg', 'GSK', '3004', 12, 'GENERAL', 'Tablet', '15 tablets', NULL, FALSE),
  ('Pyrigesic 500', 'Paracetamol', 'Paracetamol', 'Paracetamol 500mg', 'East India Pharmaceutical Works', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('Pacimol 500', 'Paracetamol', 'Paracetamol', 'Paracetamol 500mg', 'Ipca Laboratories', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('Febrinil 650', 'Paracetamol', 'Paracetamol', 'Paracetamol 650mg', 'Alkem Laboratories', '3004', 12, 'GENERAL', 'Tablet', '15 tablets', NULL, FALSE),
  ('Brufen 400', 'Ibuprofen', 'Ibuprofen', 'Ibuprofen 400mg', 'Abbott', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Ibugesic 400', 'Ibuprofen', 'Ibuprofen', 'Ibuprofen 400mg', 'Cipla', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Voveran SR 100', 'Diclofenac Sodium', 'Diclofenac Sodium', 'Diclofenac Sodium 100mg SR', 'Novartis', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Reactin 50', 'Diclofenac Sodium', 'Diclofenac Sodium', 'Diclofenac Sodium 50mg', 'Cipla', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Zerodol 100', 'Aceclofenac', 'Aceclofenac', 'Aceclofenac 100mg', 'Ipca Laboratories', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Zerodol-P', 'Aceclofenac + Paracetamol', 'Aceclofenac + Paracetamol', 'Aceclofenac 100mg + Paracetamol 500mg', 'Ipca Laboratories', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Zerodol-SP', 'Aceclofenac + Paracetamol + Serratiopeptidase', 'Aceclofenac + Paracetamol + Serratiopeptidase', 'Aceclofenac 100mg + Paracetamol 325mg + Serratiopeptidase 15mg', 'Ipca Laboratories', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Hifenac 100', 'Aceclofenac', 'Aceclofenac', 'Aceclofenac 100mg', 'Intas Pharmaceuticals', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Hifenac-P', 'Aceclofenac + Paracetamol', 'Aceclofenac + Paracetamol', 'Aceclofenac 100mg + Paracetamol 500mg', 'Intas Pharmaceuticals', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Nise 100', 'Nimesulide', 'Nimesulide', 'Nimesulide 100mg', 'Dr. Reddy''s Laboratories', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Nimulid 100', 'Nimesulide', 'Nimesulide', 'Nimesulide 100mg', 'Panacea Biotec', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Meftal-Spas', 'Dicyclomine + Mefenamic Acid', 'Dicyclomine + Mefenamic Acid', 'Dicyclomine 10mg + Mefenamic Acid 250mg', 'Blue Cross Laboratories', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Meftal 500', 'Mefenamic Acid', 'Mefenamic Acid', 'Mefenamic Acid 500mg', 'Blue Cross Laboratories', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Drotin', 'Drotaverine', 'Drotaverine', 'Drotaverine 40mg', 'Walter Bushnell', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Drotin-M', 'Drotaverine + Mefenamic Acid', 'Drotaverine + Mefenamic Acid', 'Drotaverine 80mg + Mefenamic Acid 250mg', 'Walter Bushnell', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Ketorol-DT', 'Ketorolac', 'Ketorolac', 'Ketorolac Tromethamine 10mg', 'Dr. Reddy''s Laboratories', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Flexon', 'Ibuprofen + Paracetamol', 'Ibuprofen + Paracetamol', 'Ibuprofen 400mg + Paracetamol 325mg', 'Aristo Pharmaceuticals', '3004', 12, 'GENERAL', 'Tablet', '15 tablets', NULL, FALSE),
  ('Volini Gel', 'Diclofenac Diethylamine', 'Diclofenac Diethylamine', 'Diclofenac Diethylamine 1.16% w/w', 'Sun Pharma', '3004', 12, 'GENERAL', 'Gel', '30g', NULL, FALSE),
  ('Moov Cream', 'Methyl Salicylate + Menthol + Eucalyptus Oil', 'Methyl Salicylate + Menthol + Eucalyptus Oil', 'Topical counter-irritant combination', 'Reckitt', '3004', 12, 'GENERAL', 'Cream', '30g', NULL, FALSE),
  ('Azithral 500', 'Azithromycin', 'Azithromycin', 'Azithromycin 500mg', 'Alembic Pharmaceuticals', '3004', 12, 'H', 'Tablet', '3 tablets', NULL, TRUE),
  ('Zady 500', 'Azithromycin', 'Azithromycin', 'Azithromycin 500mg', 'Mankind Pharma', '3004', 12, 'H', 'Tablet', '3 tablets', NULL, TRUE),
  ('Augmentin 625 Duo', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin 500mg + Clavulanic Acid 125mg', 'GSK', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Moxikind-CV 625', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin 500mg + Clavulanic Acid 125mg', 'Mankind Pharma', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Clavam 625', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin + Clavulanic Acid', 'Amoxicillin 500mg + Clavulanic Acid 125mg', 'Alkem Laboratories', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Mox 500', 'Amoxicillin', 'Amoxicillin', 'Amoxicillin 500mg', 'Sun Pharma', '3004', 12, 'H', 'Capsule', '15 capsules', NULL, TRUE),
  ('Taxim-O 200', 'Cefixime', 'Cefixime', 'Cefixime 200mg', 'Alkem Laboratories', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Mahacef 200', 'Cefixime', 'Cefixime', 'Cefixime 200mg', 'Mankind Pharma', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Ceftum 500', 'Cefuroxime Axetil', 'Cefuroxime Axetil', 'Cefuroxime Axetil 500mg', 'GSK', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Zinnat 500', 'Cefuroxime Axetil', 'Cefuroxime Axetil', 'Cefuroxime Axetil 500mg', 'GSK', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Cepodem 200', 'Cefpodoxime Proxetil', 'Cefpodoxime Proxetil', 'Cefpodoxime Proxetil 200mg', 'Sun Pharma', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Cefpodox 200', 'Cefpodoxime Proxetil', 'Cefpodoxime Proxetil', 'Cefpodoxime Proxetil 200mg', 'Cipla', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Levoflox 500', 'Levofloxacin', 'Levofloxacin', 'Levofloxacin 500mg', 'Cipla', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Glevo 500', 'Levofloxacin', 'Levofloxacin', 'Levofloxacin 500mg', 'Glenmark Pharmaceuticals', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Oflomac 200', 'Ofloxacin', 'Ofloxacin', 'Ofloxacin 200mg', 'Macleods Pharmaceuticals', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Norilet 400', 'Norfloxacin', 'Norfloxacin', 'Norfloxacin 400mg', 'Dr. Reddy''s Laboratories', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Norflox-TZ', 'Norfloxacin + Tinidazole', 'Norfloxacin + Tinidazole', 'Norfloxacin 400mg + Tinidazole 600mg', 'Cipla', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Metrogyl 400', 'Metronidazole', 'Metronidazole', 'Metronidazole 400mg', 'J.B. Chemicals', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Doxy-1 L-DR Forte', 'Doxycycline', 'Doxycycline', 'Doxycycline 100mg', 'USV', '3004', 12, 'H', 'Capsule', '10 capsules', NULL, TRUE),
  ('Doxicip 100', 'Doxycycline', 'Doxycycline', 'Doxycycline 100mg', 'Cipla', '3004', 12, 'H', 'Capsule', '10 capsules', NULL, TRUE),
  ('Zifi 200', 'Cefixime', 'Cefixime', 'Cefixime 200mg', 'FDC', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Almox 500', 'Amoxicillin', 'Amoxicillin', 'Amoxicillin 500mg', 'Alkem Laboratories', '3004', 12, 'H', 'Capsule', '15 capsules', NULL, TRUE),
  ('Linezolid 600', 'Linezolid', 'Linezolid', 'Linezolid 600mg', 'Cipla', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Pan 40', 'Pantoprazole', 'Pantoprazole', 'Pantoprazole 40mg', 'Alkem Laboratories', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Pantocid 40', 'Pantoprazole', 'Pantoprazole', 'Pantoprazole 40mg', 'Sun Pharma', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Pantop 40', 'Pantoprazole', 'Pantoprazole', 'Pantoprazole 40mg', 'Aristo Pharmaceuticals', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Pan-D', 'Pantoprazole + Domperidone', 'Pantoprazole + Domperidone', 'Pantoprazole 40mg + Domperidone 30mg SR', 'Alkem Laboratories', '3004', 12, 'H', 'Capsule', '15 capsules', NULL, TRUE),
  ('Pantocid DSR', 'Pantoprazole + Domperidone', 'Pantoprazole + Domperidone', 'Pantoprazole 40mg + Domperidone 30mg SR', 'Sun Pharma', '3004', 12, 'H', 'Capsule', '15 capsules', NULL, TRUE),
  ('Razo 20', 'Rabeprazole', 'Rabeprazole', 'Rabeprazole 20mg', 'Dr. Reddy''s Laboratories', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Razo-D', 'Rabeprazole + Domperidone', 'Rabeprazole + Domperidone', 'Rabeprazole 20mg + Domperidone 30mg SR', 'Dr. Reddy''s Laboratories', '3004', 12, 'H', 'Capsule', '15 capsules', NULL, TRUE),
  ('Omez 20', 'Omeprazole', 'Omeprazole', 'Omeprazole 20mg', 'Dr. Reddy''s Laboratories', '3004', 12, 'H', 'Capsule', '20 capsules', NULL, TRUE),
  ('Omez-D', 'Omeprazole + Domperidone', 'Omeprazole + Domperidone', 'Omeprazole 20mg + Domperidone 10mg', 'Dr. Reddy''s Laboratories', '3004', 12, 'H', 'Capsule', '20 capsules', NULL, TRUE),
  ('Sompraz 40', 'Esomeprazole', 'Esomeprazole', 'Esomeprazole 40mg', 'Sun Pharma', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Sompraz-D 40', 'Esomeprazole + Domperidone', 'Esomeprazole + Domperidone', 'Esomeprazole 40mg + Domperidone 30mg SR', 'Sun Pharma', '3004', 12, 'H', 'Capsule', '15 capsules', NULL, TRUE),
  ('Ganaton OD', 'Itopride', 'Itopride', 'Itopride 150mg SR', 'Abbott', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Domstal 10', 'Domperidone', 'Domperidone', 'Domperidone 10mg', 'Torrent Pharmaceuticals', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Emeset 4', 'Ondansetron', 'Ondansetron', 'Ondansetron 4mg', 'Cipla', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Ondem 4', 'Ondansetron', 'Ondansetron', 'Ondansetron 4mg', 'Alkem Laboratories', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Eldoper', 'Loperamide', 'Loperamide', 'Loperamide 2mg', 'Micro Labs', '3004', 12, 'H', 'Capsule', '10 capsules', NULL, TRUE),
  ('Dulcoflex 5', 'Bisacodyl', 'Bisacodyl', 'Bisacodyl 5mg', 'Boehringer Ingelheim', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('Cremaffin Plus', 'Liquid Paraffin + Milk of Magnesia + Sodium Picosulfate', 'Liquid Paraffin + Milk of Magnesia + Sodium Picosulfate', 'Laxative combination', 'Abbott', '3004', 12, 'GENERAL', 'Syrup', '225ml', NULL, FALSE),
  ('Duphalac', 'Lactulose', 'Lactulose', 'Lactulose 10g/15ml', 'Abbott', '3004', 12, 'GENERAL', 'Solution', '100ml', NULL, FALSE),
  ('Gelusil MPS', 'Aluminium Hydroxide + Magnesium Hydroxide + Simethicone', 'Aluminium Hydroxide + Magnesium Hydroxide + Simethicone', 'Antacid/antiflatulent combination', 'Pfizer', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('Cetzine 10', 'Cetirizine', 'Cetirizine', 'Cetirizine 10mg', 'GSK', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('Okacet 10', 'Cetirizine', 'Cetirizine', 'Cetirizine 10mg', 'Cipla', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('Levocet 5', 'Levocetirizine', 'Levocetirizine', 'Levocetirizine 5mg', 'Hetero Drugs', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('LCZ 5', 'Levocetirizine', 'Levocetirizine', 'Levocetirizine 5mg', 'Rapross Pharmaceuticals', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('Allegra 120', 'Fexofenadine', 'Fexofenadine', 'Fexofenadine 120mg', 'Sanofi', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('Allegra 180', 'Fexofenadine', 'Fexofenadine', 'Fexofenadine 180mg', 'Sanofi', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('Montair LC', 'Montelukast + Levocetirizine', 'Montelukast + Levocetirizine', 'Montelukast 10mg + Levocetirizine 5mg', 'Cipla', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Telekast-L', 'Montelukast + Levocetirizine', 'Montelukast + Levocetirizine', 'Montelukast 10mg + Levocetirizine 5mg', 'Lupin', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Montek LC', 'Montelukast + Levocetirizine', 'Montelukast + Levocetirizine', 'Montelukast 10mg + Levocetirizine 5mg', 'Sun Pharma', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Avil 25', 'Pheniramine Maleate', 'Pheniramine Maleate', 'Pheniramine Maleate 25mg', 'Sanofi', '3004', 12, 'GENERAL', 'Tablet', '15 tablets', NULL, FALSE),
  ('Benadryl Cough Formula', 'Diphenhydramine + Ammonium Chloride + Sodium Citrate', 'Diphenhydramine + Ammonium Chloride + Sodium Citrate', 'Cough syrup combination', 'J&J', '3004', 12, 'GENERAL', 'Syrup', '150ml', NULL, FALSE),
  ('Ascoril LS', 'Ambroxol + Levosalbutamol + Guaifenesin', 'Ambroxol + Levosalbutamol + Guaifenesin', 'Ambroxol 30mg + Levosalbutamol 1mg + Guaifenesin 50mg/5ml', 'Glenmark Pharmaceuticals', '3004', 12, 'H', 'Syrup', '100ml', NULL, TRUE),
  ('Ascoril D Plus', 'Phenylephrine + Chlorpheniramine + Dextromethorphan', 'Phenylephrine + Chlorpheniramine + Dextromethorphan', 'Cough/cold combination', 'Glenmark Pharmaceuticals', '3004', 12, 'H', 'Syrup', '100ml', NULL, TRUE),
  ('Corex DX', 'Chlorpheniramine + Dextromethorphan', 'Chlorpheniramine + Dextromethorphan', 'Chlorpheniramine Maleate + Dextromethorphan Hydrobromide', 'Pfizer', '3004', 12, 'H', 'Syrup', '100ml', NULL, TRUE),
  ('TusQ-DX', 'Dextromethorphan + Chlorpheniramine + Phenylephrine', 'Dextromethorphan + Chlorpheniramine + Phenylephrine', 'Cough/cold combination', 'Blue Cross Laboratories', '3004', 12, 'H', 'Syrup', '100ml', NULL, TRUE),
  ('Solvin Cold', 'Paracetamol + Phenylephrine + Chlorpheniramine', 'Paracetamol + Phenylephrine + Chlorpheniramine', 'Paracetamol 500mg + Phenylephrine 10mg + Chlorpheniramine 2mg', 'Ipca Laboratories', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('Sinarest', 'Paracetamol + Phenylephrine + Chlorpheniramine', 'Paracetamol + Phenylephrine + Chlorpheniramine', 'Paracetamol 500mg + Phenylephrine 10mg + Chlorpheniramine 2mg', 'Centaur Pharmaceuticals', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('D-Cold Total', 'Paracetamol + Phenylephrine + Caffeine + Chlorpheniramine', 'Paracetamol + Phenylephrine + Caffeine + Chlorpheniramine', 'Cold combination', 'Paras Pharmaceuticals', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('Alex Syrup', 'Dextromethorphan + Phenylephrine + Chlorpheniramine', 'Dextromethorphan + Phenylephrine + Chlorpheniramine', 'Cough/cold combination', 'Glenmark Pharmaceuticals', '3004', 12, 'H', 'Syrup', '100ml', NULL, TRUE),
  ('Grilinctus', 'Dextromethorphan + Chlorpheniramine + Ammonium Chloride + Guaifenesin', 'Dextromethorphan + Chlorpheniramine + Ammonium Chloride + Guaifenesin', 'Cough syrup combination', 'Franco-Indian Pharmaceuticals', '3004', 12, 'H', 'Syrup', '100ml', NULL, TRUE),
  ('Glycomet 500', 'Metformin', 'Metformin', 'Metformin 500mg', 'USV', '3004', 12, 'H', 'Tablet', '20 tablets', NULL, TRUE),
  ('Glycomet SR 500', 'Metformin', 'Metformin', 'Metformin 500mg SR', 'USV', '3004', 12, 'H', 'Tablet', '20 tablets', NULL, TRUE),
  ('Glycomet GP 1', 'Glimepiride + Metformin', 'Glimepiride + Metformin', 'Glimepiride 1mg + Metformin 500mg SR', 'USV', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Glycomet GP 2', 'Glimepiride + Metformin', 'Glimepiride + Metformin', 'Glimepiride 2mg + Metformin 500mg SR', 'USV', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Amaryl 1', 'Glimepiride', 'Glimepiride', 'Glimepiride 1mg', 'Sanofi', '3004', 12, 'H', 'Tablet', '30 tablets', NULL, TRUE),
  ('Amaryl 2', 'Glimepiride', 'Glimepiride', 'Glimepiride 2mg', 'Sanofi', '3004', 12, 'H', 'Tablet', '30 tablets', NULL, TRUE),
  ('Glimestar 1', 'Glimepiride', 'Glimepiride', 'Glimepiride 1mg', 'Mankind Pharma', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Glimestar 2', 'Glimepiride', 'Glimepiride', 'Glimepiride 2mg', 'Mankind Pharma', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Galvus 50', 'Vildagliptin', 'Vildagliptin', 'Vildagliptin 50mg', 'Novartis', '3004', 12, 'H', 'Tablet', '14 tablets', NULL, TRUE),
  ('Galvus Met 50/500', 'Vildagliptin + Metformin', 'Vildagliptin + Metformin', 'Vildagliptin 50mg + Metformin 500mg', 'Novartis', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Januvia 100', 'Sitagliptin', 'Sitagliptin', 'Sitagliptin 100mg', 'MSD Pharmaceuticals', '3004', 12, 'H', 'Tablet', '7 tablets', NULL, TRUE),
  ('Janumet 50/500', 'Sitagliptin + Metformin', 'Sitagliptin + Metformin', 'Sitagliptin 50mg + Metformin 500mg', 'MSD Pharmaceuticals', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Teneligliptin 20', 'Teneligliptin', 'Teneligliptin', 'Teneligliptin 20mg', 'Glenmark Pharmaceuticals', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Tenglyn 20', 'Teneligliptin', 'Teneligliptin', 'Teneligliptin 20mg', 'Zydus Healthcare', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Jardiance 10', 'Empagliflozin', 'Empagliflozin', 'Empagliflozin 10mg', 'Boehringer Ingelheim', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Jardiance 25', 'Empagliflozin', 'Empagliflozin', 'Empagliflozin 25mg', 'Boehringer Ingelheim', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Istamet 50/500', 'Sitagliptin + Metformin', 'Sitagliptin + Metformin', 'Sitagliptin 50mg + Metformin 500mg', 'Sun Pharma', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Trajenta 5', 'Linagliptin', 'Linagliptin', 'Linagliptin 5mg', 'Boehringer Ingelheim', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Lantus Solostar', 'Insulin Glargine', 'Insulin Glargine', 'Insulin Glargine 100IU/ml', 'Sanofi', '3004', 12, 'H', 'Injection', '3ml prefilled pen', NULL, TRUE),
  ('Telma 40', 'Telmisartan', 'Telmisartan', 'Telmisartan 40mg', 'Glenmark Pharmaceuticals', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Telma 80', 'Telmisartan', 'Telmisartan', 'Telmisartan 80mg', 'Glenmark Pharmaceuticals', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Telma-AM', 'Telmisartan + Amlodipine', 'Telmisartan + Amlodipine', 'Telmisartan 40mg + Amlodipine 5mg', 'Glenmark Pharmaceuticals', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Telmikind 40', 'Telmisartan', 'Telmisartan', 'Telmisartan 40mg', 'Mankind Pharma', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Telmikind-AM', 'Telmisartan + Amlodipine', 'Telmisartan + Amlodipine', 'Telmisartan 40mg + Amlodipine 5mg', 'Mankind Pharma', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Amlokind-AT', 'Amlodipine + Atenolol', 'Amlodipine + Atenolol', 'Amlodipine 5mg + Atenolol 50mg', 'Mankind Pharma', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Amlopres 5', 'Amlodipine', 'Amlodipine', 'Amlodipine 5mg', 'Cipla', '3004', 12, 'H', 'Tablet', '30 tablets', NULL, TRUE),
  ('Stamlo 5', 'Amlodipine', 'Amlodipine', 'Amlodipine 5mg', 'Dr. Reddy''s Laboratories', '3004', 12, 'H', 'Tablet', '30 tablets', NULL, TRUE),
  ('Concor 5', 'Bisoprolol', 'Bisoprolol', 'Bisoprolol 5mg', 'Merck', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Metolar XR 50', 'Metoprolol Succinate', 'Metoprolol Succinate', 'Metoprolol Succinate 50mg ER', 'Cipla', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Betaloc 50', 'Metoprolol Tartrate', 'Metoprolol Tartrate', 'Metoprolol Tartrate 50mg', 'AstraZeneca', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Losar 50', 'Losartan', 'Losartan', 'Losartan Potassium 50mg', 'Unichem Laboratories', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Repace 50', 'Losartan', 'Losartan', 'Losartan Potassium 50mg', 'Sun Pharma', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Ecosprin 75', 'Aspirin', 'Aspirin', 'Aspirin 75mg EC', 'USV', '3004', 12, 'H', 'Tablet', '14 tablets', NULL, TRUE),
  ('Ecosprin AV 75/20', 'Aspirin + Atorvastatin', 'Aspirin + Atorvastatin', 'Aspirin 75mg + Atorvastatin 20mg', 'USV', '3004', 12, 'H', 'Capsule', '15 capsules', NULL, TRUE),
  ('Clopilet 75', 'Clopidogrel', 'Clopidogrel', 'Clopidogrel 75mg', 'Sun Pharma', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Atorva 10', 'Atorvastatin', 'Atorvastatin', 'Atorvastatin 10mg', 'Zydus Healthcare', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Atorva 20', 'Atorvastatin', 'Atorvastatin', 'Atorvastatin 20mg', 'Zydus Healthcare', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Rozavel 10', 'Rosuvastatin', 'Rosuvastatin', 'Rosuvastatin 10mg', 'Sun Pharma', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Rosuvas 10', 'Rosuvastatin', 'Rosuvastatin', 'Rosuvastatin 10mg', 'Sun Pharma', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Aldactone 25', 'Spironolactone', 'Spironolactone', 'Spironolactone 25mg', 'RPG Life Sciences', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Olmezest 20', 'Olmesartan', 'Olmesartan', 'Olmesartan Medoxomil 20mg', 'Sun Pharma', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Shelcal 500', 'Calcium + Vitamin D3', 'Calcium + Vitamin D3', 'Calcium Carbonate 500mg + Vitamin D3 250IU', 'Torrent Pharmaceuticals', '3004', 12, 'GENERAL', 'Tablet', '15 tablets', NULL, FALSE),
  ('Shelcal HD', 'Calcium + Vitamin D3', 'Calcium + Vitamin D3', 'Calcium Carbonate 500mg + Vitamin D3 500IU', 'Torrent Pharmaceuticals', '3004', 12, 'GENERAL', 'Tablet', '15 tablets', NULL, FALSE),
  ('Calcimax 500', 'Calcium + Vitamin D3 + Minerals', 'Calcium + Vitamin D3 + Minerals', 'Calcium + Vitamin D3 + mineral combination', 'Meyer Organics', '3004', 12, 'GENERAL', 'Tablet', '30 tablets', NULL, FALSE),
  ('Ostocalcium', 'Calcium + Vitamin D3', 'Calcium + Vitamin D3', 'Calcium + Vitamin D3 supplement', 'GSK', '3004', 12, 'GENERAL', 'Tablet', '30 tablets', NULL, FALSE),
  ('Becosules', 'Vitamin B Complex', 'Vitamin B Complex', 'B-complex vitamins', 'Pfizer', '3004', 12, 'GENERAL', 'Capsule', '20 capsules', NULL, FALSE),
  ('Becosules Z', 'Vitamin B Complex + Zinc', 'Vitamin B Complex + Zinc', 'B-complex vitamins + Zinc', 'Pfizer', '3004', 12, 'GENERAL', 'Capsule', '20 capsules', NULL, FALSE),
  ('Neurobion Forte', 'Vitamin B Complex', 'Vitamin B Complex', 'Thiamine + Riboflavin + Pyridoxine + Cyanocobalamin + Niacinamide', 'Procter & Gamble', '3004', 12, 'GENERAL', 'Tablet', '30 tablets', NULL, FALSE),
  ('A to Z Gold', 'Multivitamin + Multimineral', 'Multivitamin + Multimineral', 'Multivitamin and multimineral combination', 'Alkem Laboratories', '3004', 12, 'GENERAL', 'Capsule', '15 capsules', NULL, FALSE),
  ('Supradyn Daily', 'Multivitamin + Multimineral', 'Multivitamin + Multimineral', 'Multivitamin and multimineral combination', 'Bayer', '3004', 12, 'GENERAL', 'Tablet', '15 tablets', NULL, FALSE),
  ('Zincovit', 'Multivitamin + Zinc', 'Multivitamin + Zinc', 'Multivitamin, multimineral and zinc combination', 'Apex Laboratories', '3004', 12, 'GENERAL', 'Tablet', '15 tablets', NULL, FALSE),
  ('Cel-C 500', 'Vitamin C', 'Vitamin C', 'Ascorbic Acid 500mg', 'Cipla', '3004', 12, 'GENERAL', 'Tablet', '15 tablets', NULL, FALSE),
  ('D-Rise 60K', 'Cholecalciferol', 'Cholecalciferol', 'Vitamin D3 60000IU', 'USV', '3004', 12, 'GENERAL', 'Capsule', '4 capsules', NULL, FALSE),
  ('Uprise-D3 60K', 'Cholecalciferol', 'Cholecalciferol', 'Vitamin D3 60000IU', 'Alkem Laboratories', '3004', 12, 'GENERAL', 'Capsule', '4 capsules', NULL, FALSE),
  ('Tayo 60K', 'Cholecalciferol', 'Cholecalciferol', 'Vitamin D3 60000IU', 'Eris Lifesciences', '3004', 12, 'GENERAL', 'Tablet', '4 tablets', NULL, FALSE),
  ('Folvite 5', 'Folic Acid', 'Folic Acid', 'Folic Acid 5mg', 'Pfizer', '3004', 12, 'GENERAL', 'Tablet', '45 tablets', NULL, FALSE),
  ('Orofer XT', 'Ferrous Ascorbate + Folic Acid', 'Ferrous Ascorbate + Folic Acid', 'Ferrous Ascorbate + Folic Acid', 'Emcure Pharmaceuticals', '3004', 12, 'GENERAL', 'Tablet', '10 tablets', NULL, FALSE),
  ('Autrin', 'Ferrous Fumarate + Folic Acid + Vitamin B12', 'Ferrous Fumarate + Folic Acid + Vitamin B12', 'Iron, folic acid and B12 combination', 'Pfizer', '3004', 12, 'GENERAL', 'Capsule', '30 capsules', NULL, FALSE),
  ('Dexorange', 'Iron + Folic Acid + Vitamin B12', 'Iron + Folic Acid + Vitamin B12', 'Ferric Ammonium Citrate + Folic Acid + Vitamin B12', 'Franco-Indian Pharmaceuticals', '3004', 12, 'GENERAL', 'Syrup', '200ml', NULL, FALSE),
  ('Revital H', 'Multivitamin + Ginseng + Minerals', 'Multivitamin + Ginseng + Minerals', 'Multivitamin, minerals and ginseng combination', 'Sun Pharma', '3004', 12, 'GENERAL', 'Capsule', '30 capsules', NULL, FALSE),
  ('Thyronorm 25', 'Levothyroxine', 'Levothyroxine', 'Levothyroxine Sodium 25mcg', 'Abbott', '3004', 12, 'H', 'Tablet', '120 tablets', NULL, TRUE),
  ('Thyronorm 50', 'Levothyroxine', 'Levothyroxine', 'Levothyroxine Sodium 50mcg', 'Abbott', '3004', 12, 'H', 'Tablet', '120 tablets', NULL, TRUE),
  ('Thyronorm 100', 'Levothyroxine', 'Levothyroxine', 'Levothyroxine Sodium 100mcg', 'Abbott', '3004', 12, 'H', 'Tablet', '120 tablets', NULL, TRUE),
  ('Eltroxin 50', 'Levothyroxine', 'Levothyroxine', 'Levothyroxine Sodium 50mcg', 'GSK', '3004', 12, 'H', 'Tablet', '100 tablets', NULL, TRUE),
  ('Eptoin 100', 'Phenytoin', 'Phenytoin', 'Phenytoin Sodium 100mg', 'Abbott', '3004', 12, 'H', 'Tablet', '120 tablets', NULL, TRUE),
  ('Gabapin 300', 'Gabapentin', 'Gabapentin', 'Gabapentin 300mg', 'Intas Pharmaceuticals', '3004', 12, 'H', 'Capsule', '15 capsules', NULL, TRUE),
  ('Pregaba 75', 'Pregabalin', 'Pregabalin', 'Pregabalin 75mg', 'Torrent Pharmaceuticals', '3004', 12, 'H', 'Capsule', '15 capsules', NULL, TRUE),
  ('Pregalin 75', 'Pregabalin', 'Pregabalin', 'Pregabalin 75mg', 'Torrent Pharmaceuticals', '3004', 12, 'H', 'Capsule', '15 capsules', NULL, TRUE),
  ('Stalopam 10', 'Escitalopram', 'Escitalopram', 'Escitalopram 10mg', 'Lundbeck', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Serta 50', 'Sertraline', 'Sertraline', 'Sertraline 50mg', 'Torrent Pharmaceuticals', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Prodep 20', 'Fluoxetine', 'Fluoxetine', 'Fluoxetine 20mg', 'Sun Pharma', '3004', 12, 'H', 'Capsule', '10 capsules', NULL, TRUE),
  ('Alprax 0.25', 'Alprazolam', 'Alprazolam', 'Alprazolam 0.25mg', 'Torrent Pharmaceuticals', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Clonotril 0.5', 'Clonazepam', 'Clonazepam', 'Clonazepam 0.5mg', 'Torrent Pharmaceuticals', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Zolfresh 10', 'Zolpidem', 'Zolpidem', 'Zolpidem Tartrate 10mg', 'Abbott', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Deplatt 75', 'Clopidogrel', 'Clopidogrel', 'Clopidogrel 75mg', 'Torrent Pharmaceuticals', '3004', 12, 'H', 'Tablet', '15 tablets', NULL, TRUE),
  ('Cabgolin 0.5', 'Cabergoline', 'Cabergoline', 'Cabergoline 0.5mg', 'Sun Pharma', '3004', 12, 'H', 'Tablet', '4 tablets', NULL, TRUE),
  ('Sysron-N', 'Norethisterone', 'Norethisterone', 'Norethisterone 5mg', 'Systopic Laboratories', '3004', 12, 'H', 'Tablet', '10 tablets', NULL, TRUE),
  ('Asthalin Inhaler', 'Salbutamol', 'Salbutamol', 'Salbutamol 100mcg/dose', 'Cipla', '3004', 12, 'H', 'Inhaler', '200 metered doses', NULL, TRUE),
  ('Asthalin Syrup', 'Salbutamol', 'Salbutamol', 'Salbutamol 2mg/5ml', 'Cipla', '3004', 12, 'H', 'Syrup', '100ml', NULL, TRUE),
  ('Deriphyllin Retard 150', 'Etofylline + Theophylline', 'Etofylline + Theophylline', 'Etofylline 115mg + Theophylline 35mg', 'Zydus Healthcare', '3004', 12, 'H', 'Tablet', '30 tablets', NULL, TRUE),
  ('Budecort 200 Inhaler', 'Budesonide', 'Budesonide', 'Budesonide 200mcg/dose', 'Cipla', '3004', 12, 'H', 'Inhaler', '200 metered doses', NULL, TRUE),
  ('Foracort 200 Inhaler', 'Budesonide + Formoterol', 'Budesonide + Formoterol', 'Budesonide 200mcg + Formoterol 6mcg/dose', 'Cipla', '3004', 12, 'H', 'Inhaler', '120 metered doses', NULL, TRUE),
  ('Duolin Inhaler', 'Levosalbutamol + Ipratropium', 'Levosalbutamol + Ipratropium', 'Levosalbutamol + Ipratropium Bromide', 'Cipla', '3004', 12, 'H', 'Inhaler', '200 metered doses', NULL, TRUE),
  ('T-Bact Ointment', 'Mupirocin', 'Mupirocin', 'Mupirocin 2% w/w', 'GSK', '3004', 12, 'H', 'Ointment', '5g', NULL, TRUE),
  ('Soframycin Skin Cream', 'Framycetin', 'Framycetin', 'Framycetin 1% w/w', 'Sanofi', '3004', 12, 'H', 'Cream', '30g', NULL, TRUE),
  ('Betadine Ointment', 'Povidone Iodine', 'Povidone Iodine', 'Povidone Iodine 10% w/w', 'Win Medicare', '3004', 12, 'GENERAL', 'Ointment', '20g', NULL, FALSE),
  ('Candid Cream', 'Clotrimazole', 'Clotrimazole', 'Clotrimazole 1% w/w', 'Glenmark Pharmaceuticals', '3004', 12, 'GENERAL', 'Cream', '30g', NULL, FALSE),
  ('Candid-B Cream', 'Clotrimazole + Beclomethasone', 'Clotrimazole + Beclomethasone', 'Clotrimazole 1% + Beclomethasone Dipropionate 0.025%', 'Glenmark Pharmaceuticals', '3004', 12, 'H', 'Cream', '20g', NULL, TRUE),
  ('Canesten Cream', 'Clotrimazole', 'Clotrimazole', 'Clotrimazole 1% w/w', 'Bayer', '3004', 12, 'GENERAL', 'Cream', '30g', NULL, FALSE),
  ('Lulifin Cream', 'Luliconazole', 'Luliconazole', 'Luliconazole 1% w/w', 'Sun Pharma', '3004', 12, 'H', 'Cream', '30g', NULL, TRUE),
  ('Terbinaforce 250', 'Terbinafine', 'Terbinafine', 'Terbinafine 250mg', 'Mankind Pharma', '3004', 12, 'H', 'Tablet', '7 tablets', NULL, TRUE)
)
INSERT INTO drug_master(brand_name, generic_name, salt_id, salt_composition, manufacturer, hsn_code, gst_rate, drug_schedule, dosage_form, pack_size, mrp, prescription_required)
SELECT s.brand_name, s.generic_name, sm.id, s.salt_composition, s.manufacturer, s.hsn_code, s.gst_rate::NUMERIC(5,2), s.drug_schedule, s.dosage_form, s.pack_size, s.mrp::NUMERIC(15,2), s.prescription_required
FROM seed s
JOIN salt_master sm ON sm.name = s.salt_name
WHERE NOT EXISTS (
  SELECT 1 FROM drug_master dm
  WHERE lower(dm.brand_name) = lower(s.brand_name)
    AND coalesce(lower(dm.salt_composition), '') = coalesce(lower(s.salt_composition), '')
    AND coalesce(lower(dm.manufacturer), '') = coalesce(lower(s.manufacturer), '')
);
