ALTER TABLE sales_receipt_line
    ADD COLUMN IF NOT EXISTS mrp NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS discount_per_unit NUMERIC(19, 2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(19, 2) NOT NULL DEFAULT 0;

