import 'package:flutter/material.dart';
import '../widgets/k_command_palette.dart';
import '../../routing/app_router.dart';

List<KCommand> buildAppCommands() {
  return const [
    // ── Navigation ─────────────────────────────────────────────────
    KCommand(
      label: 'Dashboard',
      icon: Icons.dashboard_rounded,
      section: 'Navigate',
      route: Routes.dashboard,
      keywords: ['home', 'overview'],
    ),
    KCommand(
      label: 'Invoices',
      icon: Icons.receipt_long_rounded,
      section: 'Navigate',
      route: Routes.invoices,
      keywords: ['ar', 'sales', 'receivables'],
    ),
    KCommand(
      label: 'Estimates',
      icon: Icons.request_quote_rounded,
      section: 'Navigate',
      route: Routes.estimates,
      keywords: ['quotes', 'proposals'],
    ),
    KCommand(
      label: 'Recurring Invoices',
      icon: Icons.autorenew_rounded,
      section: 'Navigate',
      route: Routes.recurringInvoices,
      keywords: ['subscription', 'profile'],
    ),
    KCommand(
      label: 'Credit Notes',
      icon: Icons.note_alt_rounded,
      section: 'Navigate',
      route: Routes.creditNotes,
      keywords: ['refund', 'cn'],
    ),
    KCommand(
      label: 'Bills',
      icon: Icons.receipt_rounded,
      section: 'Navigate',
      route: Routes.bills,
      keywords: ['ap', 'purchases', 'payable'],
    ),
    KCommand(
      label: 'Vendor Payments',
      icon: Icons.payments_rounded,
      section: 'Navigate',
      route: Routes.vendorPayments,
      keywords: ['ap', 'pay vendor'],
    ),
    KCommand(
      label: 'Vendor Credits',
      icon: Icons.note_alt_rounded,
      section: 'Navigate',
      route: Routes.vendorCredits,
      keywords: ['ap', 'refund'],
    ),
    KCommand(
      label: 'Expenses',
      icon: Icons.payments_rounded,
      section: 'Navigate',
      route: Routes.expenses,
    ),
    KCommand(
      label: 'Contacts',
      icon: Icons.people_rounded,
      section: 'Navigate',
      route: Routes.contacts,
      keywords: ['customers', 'vendors'],
    ),
    KCommand(
      label: 'Items',
      icon: Icons.inventory_2_rounded,
      section: 'Navigate',
      route: Routes.items,
      keywords: ['products', 'inventory', 'stock'],
    ),
    KCommand(
      label: 'Stock Receipts',
      icon: Icons.local_shipping_rounded,
      section: 'Navigate',
      route: Routes.stockReceipts,
      keywords: ['grn', 'goods received'],
    ),
    KCommand(
      label: 'Price Lists',
      icon: Icons.sell_rounded,
      section: 'Navigate',
      route: Routes.priceLists,
      keywords: ['pricing', 'tier'],
    ),
    KCommand(
      label: 'POS',
      icon: Icons.point_of_sale_rounded,
      section: 'Navigate',
      route: Routes.pos,
      keywords: ['point of sale', 'till', 'billing'],
    ),
    KCommand(
      label: 'AI Chat',
      icon: Icons.auto_awesome_rounded,
      section: 'Navigate',
      route: Routes.aiChat,
      keywords: ['assistant', 'ai', 'inbox'],
    ),
    KCommand(
      label: 'GST Dashboard',
      icon: Icons.account_balance_rounded,
      section: 'Navigate',
      route: Routes.gst,
      keywords: ['tax', 'india', 'gstr', 'compliance'],
    ),
    KCommand(
      label: 'Sales Orders',
      icon: Icons.shopping_cart_rounded,
      section: 'Navigate',
      route: Routes.salesOrders,
      keywords: ['so', 'order', 'distribution'],
    ),
    KCommand(
      label: 'Delivery Challans',
      icon: Icons.local_shipping_rounded,
      section: 'Navigate',
      route: Routes.deliveryChallans,
      keywords: ['dc', 'dispatch', 'challan'],
    ),
    KCommand(
      label: 'Purchase Orders',
      icon: Icons.shopping_bag_rounded,
      section: 'Navigate',
      route: Routes.purchaseOrders,
      keywords: ['po', 'procurement'],
    ),
    KCommand(
      label: 'Debit Notes',
      icon: Icons.note_alt_rounded,
      section: 'Navigate',
      route: Routes.debitNotes,
      keywords: ['purchase return', 'dn'],
    ),
    KCommand(
      label: 'Chart of Accounts',
      icon: Icons.account_tree_rounded,
      section: 'Navigate',
      route: Routes.chartOfAccounts,
      keywords: ['coa', 'ledger', 'accounts'],
    ),
    KCommand(
      label: 'Journal Entries',
      icon: Icons.menu_book_rounded,
      section: 'Navigate',
      route: Routes.journalEntries,
      keywords: ['journal', 'voucher', 'entry'],
    ),
    KCommand(
      label: 'Credit Ledger',
      icon: Icons.account_balance_wallet_rounded,
      section: 'Navigate',
      route: Routes.creditLedger,
      keywords: ['outstanding', 'overdue'],
    ),
    KCommand(
      label: 'Bank Reconciliation',
      icon: Icons.account_balance_rounded,
      section: 'Navigate',
      route: Routes.bankReconciliation,
      keywords: ['bank', 'statement', 'recon'],
    ),
    KCommand(
      label: 'Approval Inbox',
      icon: Icons.checklist_rounded,
      section: 'Navigate',
      route: Routes.approvals,
      keywords: ['workflow', 'approve', 'pending'],
    ),
    KCommand(
      label: 'Item Groups',
      icon: Icons.category_rounded,
      section: 'Navigate',
      route: Routes.itemGroups,
      keywords: ['variants', 'groups'],
    ),
    KCommand(
      label: 'Stock Counts',
      icon: Icons.fact_check_rounded,
      section: 'Navigate',
      route: Routes.stockCounts,
      keywords: ['physical count', 'audit'],
    ),
    KCommand(
      label: 'Transfer Orders',
      icon: Icons.swap_horiz_rounded,
      section: 'Navigate',
      route: Routes.transferOrders,
      keywords: ['warehouse', 'transfer'],
    ),
    KCommand(
      label: 'Picklists',
      icon: Icons.checklist_rounded,
      section: 'Navigate',
      route: Routes.picklists,
      keywords: ['pick', 'warehouse'],
    ),
    KCommand(
      label: 'Reorder',
      icon: Icons.replay_rounded,
      section: 'Navigate',
      route: Routes.reorder,
      keywords: ['low stock', 'replenish'],
    ),
    KCommand(
      label: 'Near Expiry',
      icon: Icons.warning_amber_rounded,
      section: 'Navigate',
      route: Routes.nearExpiry,
      keywords: ['expiry', 'batch', 'pharma'],
    ),
    KCommand(
      label: 'Batch Recall',
      icon: Icons.health_and_safety_rounded,
      section: 'Navigate',
      route: Routes.batchRecall,
      keywords: ['recall', 'batch', 'trace', 'pharma', 'food', 'fda'],
    ),
    KCommand(
      label: 'Sales Receipts',
      icon: Icons.receipt_rounded,
      section: 'Navigate',
      route: Routes.salesReceipts,
      keywords: ['pos', 'receipt'],
    ),
    KCommand(
      label: 'Cash Register',
      icon: Icons.point_of_sale_rounded,
      section: 'Navigate',
      route: Routes.cashRegister,
      keywords: ['day close', 'cash'],
    ),
    KCommand(
      label: 'Schemes',
      icon: Icons.local_offer_rounded,
      section: 'Navigate',
      route: Routes.schemes,
      keywords: ['discount', 'offer', 'promo'],
    ),
    KCommand(
      label: 'Notifications',
      icon: Icons.notifications_rounded,
      section: 'Navigate',
      route: Routes.notifications,
      keywords: ['alerts', 'bell'],
    ),

    // ── Payroll ────────────────────────────────────────────────────
    KCommand(
      label: 'Employees',
      icon: Icons.badge_rounded,
      section: 'Navigate',
      route: Routes.payrollEmployees,
      keywords: ['payroll', 'staff', 'hr'],
    ),
    KCommand(
      label: 'Payroll Runs',
      icon: Icons.date_range_rounded,
      section: 'Navigate',
      route: Routes.payrollRuns,
      keywords: ['salary', 'payslip'],
    ),

    // ── Field Sales ────────────────────────────────────────────────
    KCommand(
      label: 'Beats',
      icon: Icons.map_rounded,
      section: 'Navigate',
      route: Routes.fieldSalesBeats,
      keywords: ['beat', 'territory', 'field sales'],
    ),
    KCommand(
      label: 'Routes',
      icon: Icons.route_rounded,
      section: 'Navigate',
      route: Routes.fieldSalesRoutes,
      keywords: ['route', 'field sales'],
    ),
    KCommand(
      label: 'Vans',
      icon: Icons.local_shipping_rounded,
      section: 'Navigate',
      route: Routes.fieldSalesVans,
      keywords: ['vehicle', 'van stock'],
    ),
    KCommand(
      label: 'Route Executions',
      icon: Icons.play_circle_rounded,
      section: 'Navigate',
      route: Routes.fieldSalesExecutions,
      keywords: ['field visit', 'today'],
    ),
    KCommand(
      label: 'Salesman Dashboard',
      icon: Icons.analytics_rounded,
      section: 'Navigate',
      route: Routes.fieldSalesDashboard,
      keywords: ['target', 'incentive'],
    ),
    KCommand(
      label: 'Live Field Tracking',
      icon: Icons.my_location,
      section: 'Navigate',
      route: Routes.fieldSalesLiveTracking,
      keywords: ['gps', 'location', 'salesman', 'map'],
    ),
    KCommand(
      label: 'MR Approvals',
      icon: Icons.fact_check,
      section: 'Navigate',
      route: Routes.fieldSalesMrApprovals,
      keywords: ['tour plan', 'dcr', 'mtp', 'medical rep'],
    ),
    KCommand(
      label: 'Field Samples & Allowance',
      icon: Icons.inventory_2,
      section: 'Navigate',
      route: Routes.fieldSalesSamples,
      keywords: ['samples', 'promo', 'ta', 'da', 'allowance'],
    ),
    KCommand(
      label: 'HSN / GST Rates',
      icon: Icons.percent_rounded,
      section: 'Navigate',
      route: Routes.hsnMaster,
      keywords: ['hsn', 'gst rate', 'tax'],
    ),
    KCommand(
      label: 'Field Coverage Reports',
      icon: Icons.insights,
      section: 'Navigate',
      route: Routes.fieldSalesCoverage,
      keywords: ['deviation', 'frequency', 'team', 'tour plan'],
    ),
    KCommand(
      label: 'Attendance & Leave',
      icon: Icons.badge,
      section: 'Navigate',
      route: Routes.fieldSalesAttendance,
      keywords: ['punch', 'leave', 'hr'],
    ),
    KCommand(
      label: 'Detail Aids (E-detailing)',
      icon: Icons.auto_stories,
      section: 'Navigate',
      route: Routes.fieldSalesDetailAids,
      keywords: ['brochure', 'visual aid', 'edetailing'],
    ),

    // ── Partner Network ────────────────────────────────────────────
    KCommand(
      label: 'Trading Partners',
      icon: Icons.handshake_rounded,
      section: 'Navigate',
      route: Routes.partnerNetworkPartners,
      keywords: ['b2b', 'supplier', 'buyer'],
    ),
    KCommand(
      label: 'Published Catalog',
      icon: Icons.storefront_rounded,
      section: 'Navigate',
      route: Routes.partnerNetworkCatalog,
      keywords: ['catalog', 'publish'],
    ),
    KCommand(
      label: 'Supplier Search',
      icon: Icons.search_rounded,
      section: 'Navigate',
      route: Routes.partnerNetworkSupplierSearch,
      keywords: ['find supplier', 'b2b'],
    ),

    // ── Manufacturing ──────────────────────────────────────────────
    KCommand(
      label: 'Work Orders',
      icon: Icons.precision_manufacturing_rounded,
      section: 'Navigate',
      route: Routes.manufacturingWorkOrders,
      keywords: ['production', 'wo', 'manufacturing'],
    ),
    KCommand(
      label: 'Job Work',
      icon: Icons.engineering_rounded,
      section: 'Navigate',
      route: Routes.manufacturingJobWork,
      keywords: ['outsource', 'sub-contract'],
    ),
    KCommand(
      label: 'Routings',
      icon: Icons.timeline_rounded,
      section: 'Navigate',
      route: Routes.manufacturingRoutings,
      keywords: ['operation', 'workstation'],
    ),
    KCommand(
      label: 'QC Inspections',
      icon: Icons.verified_rounded,
      section: 'Navigate',
      route: Routes.manufacturingQcInspections,
      keywords: ['quality', 'inspection'],
    ),

    // ── Reports ────────────────────────────────────────────────────
    KCommand(
      label: 'Reports Hub',
      icon: Icons.bar_chart_rounded,
      section: 'Reports',
      route: Routes.reports,
    ),
    KCommand(
      label: 'Trial Balance',
      icon: Icons.balance_rounded,
      section: 'Reports',
      route: Routes.trialBalance,
      subtitle: 'All ledger debits and credits',
    ),
    KCommand(
      label: 'Profit & Loss',
      icon: Icons.show_chart_rounded,
      section: 'Reports',
      route: Routes.profitLoss,
      subtitle: 'Income statement',
      keywords: ['p&l', 'pnl', 'income'],
    ),
    KCommand(
      label: 'Balance Sheet',
      icon: Icons.account_tree_rounded,
      section: 'Reports',
      route: Routes.balanceSheet,
    ),
    KCommand(
      label: 'General Ledger',
      icon: Icons.menu_book_rounded,
      section: 'Reports',
      route: Routes.generalLedger,
      keywords: ['gl'],
    ),
    KCommand(
      label: 'AR Ageing',
      icon: Icons.hourglass_bottom_rounded,
      section: 'Reports',
      route: Routes.ageingReport,
      subtitle: 'Receivables by age bucket',
    ),
    KCommand(
      label: 'AP Ageing',
      icon: Icons.hourglass_bottom_rounded,
      section: 'Reports',
      route: Routes.apAgeingReport,
      subtitle: 'Payables by age bucket',
    ),

    // ── Create ─────────────────────────────────────────────────────
    KCommand(
      label: 'New Invoice',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.invoiceCreate,
      keywords: ['create invoice', 'new sale'],
    ),
    KCommand(
      label: 'New Estimate',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.estimateCreate,
      keywords: ['quote', 'proposal'],
    ),
    KCommand(
      label: 'New Bill',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.billCreate,
      keywords: ['purchase'],
    ),
    KCommand(
      label: 'New Expense',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.expenseCreate,
    ),
    KCommand(
      label: 'New Contact',
      icon: Icons.person_add_rounded,
      section: 'Create',
      route: Routes.contactCreate,
      keywords: ['customer', 'vendor'],
    ),
    KCommand(
      label: 'New Item',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.itemCreate,
      keywords: ['product'],
    ),
    KCommand(
      label: 'New Credit Note',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.creditNoteCreate,
      keywords: ['refund'],
    ),
    KCommand(
      label: 'New Vendor Credit',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.vendorCreditCreate,
    ),
    KCommand(
      label: 'New Sales Order',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.salesOrderCreate,
      keywords: ['so', 'order'],
    ),
    KCommand(
      label: 'New Purchase Order',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.purchaseOrderCreate,
      keywords: ['po', 'procurement'],
    ),
    KCommand(
      label: 'New Delivery Challan',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.deliveryChallanCreate,
      keywords: ['dc', 'dispatch'],
    ),
    KCommand(
      label: 'New Stock Receipt',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.stockReceiptCreate,
      keywords: ['grn', 'goods received'],
    ),
    KCommand(
      label: 'New Journal Entry',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.journalEntryCreate,
      keywords: ['voucher', 'journal'],
    ),
    KCommand(
      label: 'Record Transaction',
      icon: Icons.edit_note_rounded,
      section: 'Create',
      route: Routes.guidedTransactionCreate,
      keywords: ['guided', 'conversational', 'ai entry'],
    ),
    KCommand(
      label: 'New Employee',
      icon: Icons.person_add_rounded,
      section: 'Create',
      route: Routes.payrollEmployeeCreate,
      keywords: ['payroll', 'staff'],
    ),
    KCommand(
      label: 'New Work Order',
      icon: Icons.add_rounded,
      section: 'Create',
      route: Routes.manufacturingWorkOrderCreate,
      keywords: ['production', 'wo'],
    ),

    // ── Settings ───────────────────────────────────────────────────
    KCommand(
      label: 'Settings',
      icon: Icons.settings_rounded,
      section: 'Settings',
      route: Routes.settings,
    ),
    KCommand(
      label: 'Default Accounts',
      icon: Icons.tune_rounded,
      section: 'Settings',
      route: Routes.defaultAccounts,
    ),
    KCommand(
      label: 'Tax Account Mappings',
      icon: Icons.receipt_long_rounded,
      section: 'Settings',
      route: Routes.taxAccountMappings,
    ),
    KCommand(
      label: 'Organisation Details',
      icon: Icons.business_rounded,
      section: 'Settings',
      route: Routes.orgDetails,
    ),
    KCommand(
      label: 'Team Members',
      icon: Icons.group_rounded,
      section: 'Settings',
      route: Routes.teamMembers,
      keywords: ['users', 'roles'],
    ),
    KCommand(
      label: 'Business Policies',
      icon: Icons.policy_rounded,
      section: 'Settings',
      route: Routes.businessPolicies,
      keywords: ['credit limit', 'approval'],
    ),
    KCommand(
      label: 'Workflow Settings',
      icon: Icons.account_tree_rounded,
      section: 'Settings',
      route: Routes.workflowSettings,
      keywords: ['approval', 'workflow'],
    ),
    KCommand(
      label: 'AI Settings',
      icon: Icons.auto_awesome_rounded,
      section: 'Settings',
      route: Routes.aiSettings,
    ),
    KCommand(
      label: 'API Keys',
      icon: Icons.vpn_key_rounded,
      section: 'Settings',
      route: Routes.apiKeys,
      keywords: ['mcp', 'integration'],
    ),
    KCommand(
      label: 'Payroll Settings',
      icon: Icons.settings_rounded,
      section: 'Settings',
      route: Routes.payrollSettings,
      keywords: ['pf', 'esi', 'salary'],
    ),
    KCommand(
      label: 'POS Receipt Settings',
      icon: Icons.receipt_rounded,
      section: 'Settings',
      route: Routes.receiptSettings,
      keywords: ['thermal', 'upi', 'sms', 'whatsapp'],
    ),
    KCommand(
      label: 'Printer Setup',
      icon: Icons.print_rounded,
      section: 'Settings',
      route: Routes.printerSetup,
      keywords: ['thermal', 'bluetooth'],
    ),
    KCommand(
      label: 'Tally Import',
      icon: Icons.upload_file_rounded,
      section: 'Settings',
      route: Routes.tallyImport,
      keywords: ['migration', 'tally'],
    ),
    KCommand(
      label: 'Budgets',
      icon: Icons.savings_rounded,
      section: 'Settings',
      route: Routes.budgets,
    ),
    KCommand(
      label: 'Period Close',
      icon: Icons.lock_clock_rounded,
      section: 'Settings',
      route: Routes.periodClose,
      keywords: ['month close', 'fiscal'],
    ),
  ];
}
